/**
 * list-style-defaults.ts — Shared marker-style defaults for list commands.
 *
 * Single source of truth for the `listStyleType` values that commands use
 * when creating or converting list containers. Kept next to the list
 * commands (and deliberately free of extension imports) so the command
 * layer never depends on the extension layer.
 */

/**
 * Default marker style applied to newly created `bulletList` containers.
 */
export const DEFAULT_BULLET_LIST_STYLE: string = 'disc';

/**
 * Default marker style applied to newly created `orderedList` containers.
 */
export const DEFAULT_ORDERED_LIST_STYLE: string = 'decimal';

/**
 * Build the list-level attribute bag for a newly created or converted list
 * container, including the marker-style default for the target type.
 *
 * @param {string} listType - The logical target list type ('bullet' | 'ordered').
 * @param {string} id - The fresh list id generated by the caller.
 * @returns {object} The complete list-level attribute bag.
 */
export function buildListAttributes(
    listType: 'bullet' | 'ordered',
    id: string
): Record<string, unknown> {
    const attrs: Record<string, unknown> = { id };
    if (listType === 'ordered') {
        attrs['order'] = 1;
        attrs['listStyleType'] = DEFAULT_ORDERED_LIST_STYLE;
    } else {
        attrs['listStyleType'] = DEFAULT_BULLET_LIST_STYLE;
    }
    return attrs;
}
