/** @hidden */
export const DISABLED: string = 'e-disabled';


/** @hidden */
export const locale: string = 'spreadsheetLocale';
/** @hidden */
export const dialog: string = 'dialog';
/** @hidden */
export const fontColor: { [key: string]: string[] } = {
    'Custom': [
        '#ffffff', '#000000', '#e7e6e6', '#44546a', '#4472c4', '#ed7d31', '#a5a5a5', '#ffc000', '#70ad47', '#ff0000',
        '#f2f2f2', '#808080', '#cfcdcd', '#d5dce4', '#d9e2f3', '#fbe4d5', '#ededed', '#fff2cc', '#e2efd9', '#ffcccc',
        '#d9d9d9', '#595959', '#aeaaaa', '#acb9ca', '#b4c6e7', '#f7caac', '#dbdbdb', '#ffe599', '#c5e0b3', '#ff8080',
        '#bfbfbf', '#404040', '#747070', '#8496b0', '#8eaadb', '#f4b083', '#c9c9c9', '#ffd966', '#a8d08d', '#ff3333',
        '#a6a6a6', '#262626', '#3b3838', '#323e4f', '#2f5496', '#c45911', '#7b7b7b', '#bf8f00', '#538135', '#b30000',
        '#7f7f7f', '#0d0d0d', '#161616', '#212934', '#1f3763', '#823b0b', '#525252', '#7f5f00', '#375623', '#660000']
};
/** @hidden */
export const fillColor: { [key: string]: string[] } = {
    'Custom': [
        '#ffffff', '#000000', '#ffff00', '#00ff00', '#00ffff', '#0000ff', '#ff0000', '#000080', '#800080', '#996633',
        '#f2f2f2', '#808080', '#ffffcc', '#b3ffb3', '#ccffff', '#ccccff', '#ffcccc', '#ccccff', '#ff80ff', '#f2e6d9',
        '#d9d9d9', '#595959', '#ffff80', '#80ff80', '#b3ffff', '#8080ff', '#ff8080', '#8080ff', '#ff00ff', '#dfbf9f',
        '#bfbfbf', '#404040', '#ffff33', '#33ff33', '#33ffff', '#3333ff', '#ff3333', '#0000b3', '#b300b3', '#c68c53',
        '#a6a6a6', '#262626', '#e6e600', '#00b300', '#009999', '#000099', '#b30000', '#000066', '#660066', '#86592d',
        '#7f7f7f', '#0d0d0d', '#999900', '#006600', '#006666', '#000066', '#660000', '#00004d', '#4d004d', '#734d26',
    ]
};

/**
 * Default locale text
 * @hidden
 */
export let defaultLocale: object = {
    Cut: 'Cut',
    Copy: 'Copy',
    Paste: 'Paste',
    All: 'All',
    Values: 'Values',
    Formats: 'Formats',
    Bold: 'Bold',
    Font: 'Font',
    FontSize: 'Font Size',
    Italic: 'Italic',
    Underline: 'Underline',
    Strikethrough: 'Strikethrough',
    TextColor: 'Text Color',
    FillColor: 'Fill Color',
    HorizontalAlignment: 'Horizontal Alignment',
    AlignLeft: 'Align Left',
    AlignCenter: 'Center',
    AlignRight: 'Align Right',
    VerticalAlignment: 'Vertical Alignment',
    AlignTop: 'Align Top',
    AlignMiddle: 'Align Middle',
    AlignBottom: 'Align Bottom',
    InsertFunction: 'Insert Function',
    NameBox: 'Name Box',
    ShowHeaders: 'Show Headers',
    HideHeaders: 'Hide Headers',
    ShowGridLines: 'Show Gridlines',
    HideGridLines: 'Hide Gridlines',
    AddSheet: 'Add Sheet',
    ListAllSheets: 'List All Sheets',
    FullScreen: 'Full Screen',
    CollapseToolbar: 'Collapse Toolbar',
    ExpandToolbar: 'Expand Toolbar',
    CollapseFormulaBar: 'Collapse Formula Bar',
    ExpandFormulaBar: 'Expand Formula Bar',
    File: 'File',
    Home: 'Home',
    Formulas: 'Formulas',
    View: 'View',
    New: 'New',
    Open: 'Open',
    SaveAs: 'Save As',
    ExcelXlsx: 'Microsoft Excel',
    ExcelXls: 'Microsoft Excel 97-2003',
    CSV: 'Comma-separated values',
    FormulaBar: 'Formula Bar',
    Ok: 'Ok',
    Close: 'Close',
    Cancel: 'Cancel',
    Apply: 'Apply',
    MoreColors: 'More Colors',
    StandardColors: 'Standard Colors',
    General: 'General',
    Number: 'Number',
    Currency: 'Currency',
    Accounting: 'Accounting',
    ShortDate: 'Short Date',
    LongDate: 'Long Date',
    Time: 'Time',
    Percentage: 'Percentage',
    Fraction: 'Fraction',
    Scientific: 'Scientific',
    Text: 'Text',
    MobileFormulaBarPlaceHolder: 'Enter value or Formula',
    NumberFormat: 'Number Format',
    PasteAlert: 'You can\'t paste this here because the copy area and paste area aren\'t in the same size.' +
    '</br></br>Select just one cell in the paste area or an area that\'s the same size, and try pasting again.',
    DestroyAlert: 'Are you sure you want to destroy the current workbook without saving and create a new workbook?',
    SheetRenameInvalidAlert: 'Sheet name contains invalid character.',
    SheetRenameEmptyAlert: 'Sheet name cannot be empty.',
    SheetRenameAlreadyExistsAlert: 'Sheet name already exists. Please enter another name.',
    DeleteSheetAlert: 'Are you sure you want to delete this sheet?',
    DeleteSingleLastSheetAlert: 'A Workbook must contain at least one visible worksheet.',
    PickACategory: 'Pick a category',
    Description: 'Description',
    UnsupportedFile: 'Unsupported File',
    InvalidUrl: 'Invalid Url',
    SUM: 'Sums all values, cell references or ranges.',
    SUMIFS: 'Sums the cells specified by a given set of conditions or criteria.',
    ABS: 'Returns the absolute value of a number.',
    RAND: 'Return a random number between 0 and 1.',
    FLOOR: 'Returns the round a number down to the nearest multiple of significance.',
    CEILING: 'Returns a number rounded up to a nearest multiple of significance.',
    SUMIF: 'It will sum up cells that meet the given criteria.',
    PRODUCT: 'Multiplies all the numbers given as arguments and returns the product.',
    AVERAGE: 'The sum of the numbers divided by how many numbers are being averaged.',
    AVERAGEIF: 'Computes the average of the numbers in a range that meet the supplied criteria.',
    COUNT: 'Counts the numbers in the list of arguments, exclude text entries.',
    COUNTA: 'Counts the non-empty values in the list of arguments.',
    COUNTIF: 'Counts the number of cells in a range that meet a specified condition.',
    COUNTIFS: 'Counts the number of times each cells in all the ranges that meet the specific conditions.',
    AVERAGEA: 'Calculates the average of values in the list of arguments.Arguments can be numbers, names, arrays or references.',
    AVERAGEIFS: 'Conditionally returns the average of the contents of cells for the set of ranges.',
    MIN: 'Returns the smaller number in set of arguments.',
    MAX: 'Returns the largest number in set of arguments.',
    DATE: 'Returns the date, given the year, month and day of the month.',
    DAY: 'Returns the day of a given date.',
    DAYS: 'Returns the number of days between two dates.',
    IF: 'Returns one value if a logical expression is TRUE and another if it is FALSE',
    AND: 'Returns TRUE if all the arguments are considered TRUE, and FALSE otherwise.',
    IFS: 'Checks multiple conditions and returns a value corresponding to the first TRUE result.',
    IFERROR: 'Returns a value you specify if a formula evaluates to an error; otherwise, it returns the result of the formula.',
    CHOOSE: 'Returns a value from a list, given an index number.',
    INDEX: 'Returns a value from a table, given a row and column number.',
    FIND: 'Returns the position of a string of text within another string.',
    CONCATENATE: 'Used to join two or more strings together.',
    CONCAT: 'Concatenates a list or range of text strings.',
    SUBTOTAL: 'Returns a subtotal in a list or database.',
    RADIANS: 'Converts degrees in to radians.',
    OR: 'Returns TRUE if any arguments considered TRUE, and all the arguments are FALSE it will return FALSE.',
    MATCH: 'Returns the relative position of an checked item in range that matches a specified value in a specified order.',
    DefineNameExists: 'This name is already exists, try different name.'
};