/**
 * service-errors.spec.ts
 *
 * Unit tests for the typed service errors.
 *
 * Coverage note: most branches in this file are generated by the TypeScript
 * `__extends` polyfill at the top of the compiled .js. Those branches are
 * unreachable in any environment that supports `Object.setPrototypeOf`
 * (every modern browser + Node), so they are intentionally not targeted.
 * We only exercise the application code: the constructor bodies, the `.name`
 * assignment, and the `instanceof` chain.
 */
import {
    DuplicateServiceError,
    ServiceNotFoundError,
    CircularDependencyError
} from '../../src/services/service-errors';

describe('DuplicateServiceError', () => {
    it('extends Error and sets .name', () => {
        const e = new DuplicateServiceError('Counter');
        // Note: `instanceof DuplicateServiceError` is unreliable in transpiled ES5
        // because `class X extends Error {}` does not set the prototype chain.
        // We rely on `name` and `message` instead, which are explicit in the
        // constructor body and work in every target environment.
        expect(typeof e).toBe('object');
        expect(e instanceof Error).toBe(true);
        expect(e.name).toBe('DuplicateServiceError');
        expect(e.message).toBe('Service already registered for token "Counter". Use { override: true } to replace it.');
    });
});

describe('ServiceNotFoundError', () => {
    it('extends Error and sets .name', () => {
        const e = new ServiceNotFoundError('EventBus');
        // Note: see DuplicateServiceError above for why we avoid `instanceof`.
        expect(typeof e).toBe('object');
        expect(e instanceof Error).toBe(true);
        expect(e.name).toBe('ServiceNotFoundError');
        expect(e.message).toBe('No service registered for token "EventBus".');
    });
});

describe('CircularDependencyError', () => {
    it('extends Error and sets .name; joins cycle with " → "', () => {
        const cycle = ['A', 'B', 'C'];
        const e = new CircularDependencyError(cycle);
        // Note: see DuplicateServiceError above for why we avoid `instanceof`.
        expect(typeof e).toBe('object');
        expect(e instanceof Error).toBe(true);
        expect(e.name).toBe('CircularDependencyError');
        expect(e.message).toBe('Circular dependency detected: A → B → C');
    });

    it('handles a single-element cycle', () => {
        const e = new CircularDependencyError(['Self']);
        expect(e.message).toBe('Circular dependency detected: Self');
    });

    it('handles an empty cycle array', () => {
        const e = new CircularDependencyError([]);
        expect(e.message).toBe('Circular dependency detected: ');
    });

    it('constructor properly chains to Error and returns instance', () => {
        const e = new CircularDependencyError(['A', 'B']);
        expect(e).toBeTruthy();
        expect(e.name).toBe('CircularDependencyError');
        expect(e instanceof Error).toBe(true);
    });
});
