import { ExpressionEngine } from './expressions/expression-engine';
import { FormValueType } from './utils';

/**
 * Custom Validation Engine
 *
 * Evaluates FormIO-style custom validation expressions:
 * valid = (condition) ? true : 'error message';
 *
 * Reuses ExpressionEngine for dependency extraction and expression parsing
 * @private
 */
export class CustomValidationEngine {
  private expressionEngine: ExpressionEngine;

  constructor() {
    this.expressionEngine = new ExpressionEngine();
  }

  /**
   * Validate field using custom validation expression
   *
   * @param expression - FormIO-style validation expression (generated by UI)
   * @param fieldValue - Current field value (as 'input')
   * @param formValues - All form values for cross-field references
   * @returns true if valid, error message string if invalid
   */
  validate(
    expression: string,
    fieldValue: any,
    formValues: Record<string, FormValueType>
  ): true | string {
    if (!expression || expression.trim() === '') {
      return true; // No validation rule = valid
    }

    try {
      // Inject 'input' as current field value
      const context = {
        ...formValues,
        input: fieldValue,
        valid: true // Initialize valid variable
      };

      // Parse expression - FormIO pattern uses assignment: valid = ...
      // Pattern: valid = (condition) ? true : 'error message'
      const validPattern = /valid\s*=\s*(.+?)\s*\?\s*true\s*:\s*['"](.+?)['"]\s*$/;
      const match = expression.match(validPattern);

      if (!match) {
        return 'Invalid validation expression format';
      }

      const condition = match[1].trim();
      const errorMessage = match[2];

      // Evaluate the condition (should return boolean)
      const conditionResult = this.expressionEngine.evaluate(
        condition,
        context,
        { throwOnError: false },
        true
      );

      // If condition is true, validation passes
      if (conditionResult === true) {
        return true;
      } else {
        // Condition is false, return the error message
        return errorMessage;
      }

    } catch (error) {
      return 'Validation expression error';
    }
  }

  /**
   * Extract field dependencies from validation expression
   *
   * @param expression - Custom validation expression (or just condition)
   * @returns Array of field names referenced in expression
   */
  extractDependencies(expression: string): string[] {
    if (!expression) return [];

    // Extract validation logic (right side of = sign if present)
    const validPattern = /valid\s*=\s*(.+)/;
    const match = expression.match(validPattern);
    const validationLogic = match ? match[1] : expression;

    // Use ExpressionEngine to extract field references
    const deps = this.expressionEngine.extractDependencies(validationLogic);

    // Filter out 'input' as it's the current field, not a dependency
    return deps.filter(dep => dep !== 'input');
  }

  /**
   * Validate condition syntax (simplified - no need for "valid =" check)
   *
   * @param condition - Validation condition (without "valid =" prefix)
   * @param availableFields - Available field names for reference validation
   * @returns Array of validation error messages
   */
  validateConditionSyntax(condition: string, availableFields: string[]): string[] {
    if (!condition || condition.trim() === '') {
      return ['Condition cannot be empty'];
    }

    const errors: string[] = [];

    // Check for balanced parentheses
    const openParens = (condition.match(/\(/g) || []).length;
    const closeParens = (condition.match(/\)/g) || []).length;
    if (openParens !== closeParens) {
      errors.push(`Unbalanced parentheses (${openParens} open, ${closeParens} close)`);
    }

    // Check for balanced braces
    const openBraces = (condition.match(/\{/g) || []).length;
    const closeBraces = (condition.match(/\}/g) || []).length;
    if (openBraces !== closeBraces) {
      errors.push(`Unbalanced braces (${openBraces} open, ${closeBraces} close)`);
    }

    // Validate field references
    const deps: string[] = this.extractDependencies(condition);
    const invalidFields: string[] = deps.filter((field: string) => availableFields.indexOf(field) === -1);
    if (invalidFields.length > 0) {
      errors.push(`Unknown field references: ${invalidFields.join(', ')}`);
    }

    return errors;
  }

  /**
   * Build full FormIO expression from condition and error message
   *
   * @param condition - Validation condition (e.g., "(input === {password})")
   * @param errorMessage - Error message to show when validation fails
   * @returns Full FormIO expression
   */
  buildExpression(condition: string, errorMessage: string): string {
    // Remove outer parentheses if present (we'll add them back in ternary)
    const trimmedCondition = condition.trim();

    // Escape single quotes in error message
    const escapedMessage = errorMessage.replace(/'/g, "\\'");

    // Build FormIO expression
    return `valid = ${trimmedCondition} ? true : '${escapedMessage}'`;
  }

  /**
   * Extract condition and error message from full FormIO expression
   * For editing existing rules
   *
   * @param expression - Full FormIO expression
   * @returns { condition, errorMessage } or null if invalid
   */
  parseExpression(expression: string): { condition: string; errorMessage: string } | null {
    // Pattern: valid = (condition) ? true : 'error message'
    const pattern = /valid\s*=\s*(.+?)\s*\?\s*true\s*:\s*'(.+)'/;
    const match = expression.match(pattern);

    if (match) {
      return {
        condition: match[1].trim(),
        errorMessage: match[2].replace(/\\'/g, "'") // Unescape quotes
      };
    }

    return null;
  }
}
