import { PdfColor } from "../src/pdf/core/pdf-type";
import { PdfTextStyle } from "../src/pdf/core/enumerator";
import { PdfDocument } from "../src/pdf/core/pdf-document";
import { PdfBookmark, PdfBookmarkBase, PdfNamedDestination } from "../src/pdf/core/pdf-outline";
import { PdfDestination, PdfPage } from "../src/pdf/core/pdf-page";
describe('Bookmark Test', () => {
    it('Add single bookmark to empty PDF', () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        let bookmarks: PdfBookmarkBase = document.bookmarks;
        expect(bookmarks).toBeDefined();
        expect(bookmarks.count).toEqual(0);
        let bookmark: PdfBookmark = bookmarks.add('FirstBookmark');
        expect(bookmark.title).toEqual('FirstBookmark');
        expect(bookmark.destination).toBeUndefined();
        bookmark.destination = new PdfDestination(page, { x: 10, y: 10 });
        expect(bookmark.destination).toBeDefined();
        expect(bookmark.destination.pageIndex).toEqual(0);
        expect(bookmark.destination.location).toEqual({ x: 10, y: 10 });
        bookmark.namedDestination = new PdfNamedDestination('FirstDestination');
        expect(bookmark.namedDestination).toBeDefined();
        expect(bookmark.namedDestination.title).toEqual('FirstDestination');
        expect(bookmark._dictionary.get('A').get('D')).toEqual('FirstDestination');
        expect(bookmark._dictionary.get('A').get('S').name).toEqual('GoTo');
        bookmark.color = { r: 255, g: 255, b: 0 };
        bookmark.textStyle = PdfTextStyle.italic | PdfTextStyle.bold;
        expect(bookmarks.count).toEqual(1);
        document.destroy();
    });
    it('Add multiple bookmarks to empty PDF', () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        let bookmarks: PdfBookmarkBase = document.bookmarks;
        expect(bookmarks).toBeDefined();
        expect(bookmarks.count).toEqual(0);
        let bookmark1: PdfBookmark = bookmarks.add('FirstBookmark');
        bookmark1.destination = new PdfDestination(page, { x: 10, y: 10 });
        expect(bookmark1.title).toEqual('FirstBookmark');
        expect(bookmarks.count).toEqual(1);
        let bookmark2: PdfBookmark = bookmarks.add('SecondBookmark');
        bookmark2.destination = new PdfDestination(page, { x: 10, y: 30 });
        expect(bookmark2.title).toEqual('SecondBookmark');
        expect(bookmarks.count).toEqual(2);
        document.destroy();
    });
    it('Add single child bookmark to empty PDF', () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        let bookmarks: PdfBookmarkBase = document.bookmarks;
        expect(bookmarks).toBeDefined();
        expect(bookmarks.count).toEqual(0);
        let parent: PdfBookmark = bookmarks.add('FirstBookmark');
        expect(parent.title).toEqual('FirstBookmark');
        expect(parent.destination).toBeUndefined();
        parent.destination = new PdfDestination(page, { x: 10, y: 10 });
        expect(parent.destination).toBeDefined();
        expect(parent.destination.pageIndex).toEqual(0);
        expect(parent.destination.location).toEqual({ x: 10, y: 10 });
        expect(bookmarks.count).toEqual(1);
        expect(parent.count).toEqual(0);
        let child: PdfBookmark = parent.add('First_1');
        expect(child.title).toEqual('First_1');
        expect(child.destination).toBeUndefined();
        child.destination = new PdfDestination(page, { x: 10, y: 30 });
        expect(child.destination).toBeDefined();
        expect(child.destination.pageIndex).toEqual(0);
        expect(child.destination.location).toEqual({ x: 10, y: 30 });
        expect(bookmarks.count).toEqual(1);
        expect(parent.count).toEqual(1);
        expect(parent.isExpanded).toBeTruthy();
        parent.isExpanded = false;
        expect(parent.isExpanded).toBeFalsy();
        expect(parent.count).toEqual(1);
        expect(parent._dictionary.get('Count')).toEqual(-1);
        parent.isExpanded = true;
        expect(parent.isExpanded).toBeTruthy();
        document.destroy();
    });
    it('Add multiple child bookmarks to empty PDF', () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        let bookmarks: PdfBookmarkBase = document.bookmarks;
        expect(bookmarks).toBeDefined();
        expect(bookmarks.count).toEqual(0);
        let bookmark1: PdfBookmark = bookmarks.add('FirstBookmark');
        bookmark1.destination = new PdfDestination(page, { x: 10, y: 10 });
        expect(bookmark1.title).toEqual('FirstBookmark');
        expect(bookmarks.count).toEqual(1);
        expect(bookmark1.count).toEqual(0);
        let bookmark1_1: PdfBookmark = bookmark1.add('First_1');
        bookmark1_1.destination = new PdfDestination(page, { x: 10, y: 30 });
        expect(bookmark1_1.title).toEqual('First_1');
        expect(bookmark1.count).toEqual(1);
        expect(bookmarks.count).toEqual(1);
        let bookmark1_2: PdfBookmark = bookmark1.add('First_2');
        bookmark1_2.destination = new PdfDestination(page, { x: 10, y: 50 });
        expect(bookmark1_2.title).toEqual('First_2');
        expect(bookmark1.count).toEqual(2);
        expect(bookmarks.count).toEqual(1);
        let bookmark2: PdfBookmark = bookmarks.add('SecondBookmark');
        bookmark2.destination = new PdfDestination(page, { x: 30, y: 10 });
        expect(bookmark2.title).toEqual('SecondBookmark');
        expect(bookmarks.count).toEqual(2);
        expect(bookmark2.count).toEqual(0);
        let bookmark2_1: PdfBookmark = bookmark2.add('Second_1');
        bookmark2_1.destination = new PdfDestination(page, { x: 10, y: 30 });
        expect(bookmark2_1.title).toEqual('Second_1');
        expect(bookmark2.count).toEqual(1);
        expect(bookmarks.count).toEqual(2);
        let bookmark2_2: PdfBookmark = bookmark2.add('Second_2');
        bookmark2_2.destination = new PdfDestination(page, { x: 30, y: 50 });
        expect(bookmark2_2.title).toEqual('Second_2');
        expect(bookmark2.count).toEqual(2);
        expect(bookmarks.count).toEqual(2);
        document.destroy();
    });
    it('Add bookmark with options', () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        let bookmarks: PdfBookmarkBase = document.bookmarks;
        expect(bookmarks).toBeDefined();
        expect(bookmarks.count).toEqual(0);
        let args:
            {
                destination?: PdfDestination,
                namedDestination?: PdfNamedDestination,
                color?: PdfColor,
                textStyle?: PdfTextStyle
            } = {
            destination: new PdfDestination(page, { x: 10, y: 10 }),
            namedDestination: new PdfNamedDestination('FirstDestination'),
            color: { r: 255, b: 0, g: 0 },
            textStyle: PdfTextStyle.regular
        };
        let bookmark: PdfBookmark = bookmarks.add('FirstBookmark', args);
        expect(bookmark.title).toEqual('FirstBookmark');
        expect(bookmark.destination).toBeDefined();
        expect(bookmark.color).toEqual({ r: 255, b: 0, g: 0 });
        expect(bookmark.textStyle).toEqual(PdfTextStyle.regular);
        expect(bookmark.destination.pageIndex).toEqual(0);
        expect(bookmark.destination.location).toEqual({ x: 10, y: 10 });
        expect(bookmark.namedDestination).toBeDefined();
        expect(bookmark.namedDestination.title).toEqual('FirstDestination');
        expect(bookmark._dictionary.get('A').get('D')).toEqual('FirstDestination');
        expect(bookmark._dictionary.get('A').get('S').name).toEqual('GoTo');
        expect(bookmarks.count).toEqual(1);
        document.destroy();
    });
    it('Add bookmark with index at first in non-empty list', () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        let bookmarks: PdfBookmarkBase = document.bookmarks;
        expect(bookmarks).toBeDefined();
        expect(bookmarks.count).toEqual(0);
        let bookmark: PdfBookmark = bookmarks.add('FirstBookmark');
        expect(bookmark.title).toEqual('FirstBookmark');
        expect(bookmark.destination).toBeUndefined();
        bookmark.destination = new PdfDestination(page, { x: 10, y: 10 });
        expect(bookmark.destination).toBeDefined();
        expect(bookmark.destination.pageIndex).toEqual(0);
        expect(bookmark.destination.location).toEqual({ x: 10, y: 10 });
        bookmark.namedDestination = new PdfNamedDestination('FirstDestination');
        expect(bookmark.namedDestination).toBeDefined();
        expect(bookmark.namedDestination.title).toEqual('FirstDestination');
        expect(bookmark._dictionary.get('A').get('D')).toEqual('FirstDestination');
        expect(bookmark._dictionary.get('A').get('S').name).toEqual('GoTo');
        bookmark.color = { r: 255, g: 255, b: 0 };
        bookmark.textStyle = PdfTextStyle.italic | PdfTextStyle.bold;
        expect(bookmarks.count).toEqual(1);
        bookmark = bookmarks.add('SecondBookmark', 0);
        expect(bookmark.title).toEqual('SecondBookmark');
        expect(bookmark.destination).toBeUndefined();
        bookmark.destination = new PdfDestination(page, { x: 10, y: 20 });
        expect(bookmark.destination).toBeDefined();
        expect(bookmark.destination.pageIndex).toEqual(0);
        expect(bookmark.destination.location).toEqual({ x: 10, y: 20 });
        bookmark.namedDestination = new PdfNamedDestination('SecondDestination');
        expect(bookmark.namedDestination).toBeDefined();
        expect(bookmark.namedDestination.title).toEqual('SecondDestination');
        expect(bookmark._dictionary.get('A').get('D')).toEqual('SecondDestination');
        expect(bookmark._dictionary.get('A').get('S').name).toEqual('GoTo');
        bookmark.color = { r: 255, g: 255, b: 0 };
        bookmark.textStyle = PdfTextStyle.italic | PdfTextStyle.bold;
        expect(bookmarks.count).toEqual(2);
        document.destroy();
    });
    it('Add bookmark with index at last', () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        let bookmarks: PdfBookmarkBase = document.bookmarks;
        expect(bookmarks).toBeDefined();
        expect(bookmarks.count).toEqual(0);
        let bookmark: PdfBookmark = bookmarks.add('FirstBookmark', 0);
        expect(bookmark.title).toEqual('FirstBookmark');
        expect(bookmark.destination).toBeUndefined();
        bookmark.destination = new PdfDestination(page, { x: 10, y: 10 });
        expect(bookmark.destination).toBeDefined();
        expect(bookmark.destination.pageIndex).toEqual(0);
        expect(bookmark.destination.location).toEqual({ x: 10, y: 10 });
        bookmark.namedDestination = new PdfNamedDestination('FirstDestination');
        expect(bookmark.namedDestination).toBeDefined();
        expect(bookmark.namedDestination.title).toEqual('FirstDestination');
        expect(bookmark._dictionary.get('A').get('D')).toEqual('FirstDestination');
        expect(bookmark._dictionary.get('A').get('S').name).toEqual('GoTo');
        bookmark.color = { r: 255, g: 255, b: 0 };
        bookmark.textStyle = PdfTextStyle.italic | PdfTextStyle.bold;
        expect(bookmarks.count).toEqual(1);
        bookmark = bookmarks.add('SecondBookmark', bookmarks.count);
        expect(bookmark.title).toEqual('SecondBookmark');
        expect(bookmark.destination).toBeUndefined();
        bookmark.destination = new PdfDestination(page, { x: 10, y: 20 });
        expect(bookmark.destination).toBeDefined();
        expect(bookmark.destination.pageIndex).toEqual(0);
        expect(bookmark.destination.location).toEqual({ x: 10, y: 20 });
        bookmark.namedDestination = new PdfNamedDestination('SecondDestination');
        expect(bookmark.namedDestination).toBeDefined();
        expect(bookmark.namedDestination.title).toEqual('SecondDestination');
        expect(bookmark._dictionary.get('A').get('D')).toEqual('SecondDestination');
        expect(bookmark._dictionary.get('A').get('S').name).toEqual('GoTo');
        bookmark.color = { r: 255, g: 255, b: 0 };
        bookmark.textStyle = PdfTextStyle.italic | PdfTextStyle.bold;
        expect(bookmarks.count).toEqual(2);
        document.destroy();
    });
    it('Add bookmark with index at middle', () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        let bookmarks: PdfBookmarkBase = document.bookmarks;
        expect(bookmarks).toBeDefined();
        expect(bookmarks.count).toEqual(0);
        let bookmark: PdfBookmark = bookmarks.add('FirstBookmark', 0);
        expect(bookmark.title).toEqual('FirstBookmark');
        expect(bookmark.destination).toBeUndefined();
        bookmark.destination = new PdfDestination(page, { x: 10, y: 10 });
        expect(bookmark.destination).toBeDefined();
        expect(bookmark.destination.pageIndex).toEqual(0);
        expect(bookmark.destination.location).toEqual({ x: 10, y: 10 });
        bookmark.namedDestination = new PdfNamedDestination('FirstDestination');
        expect(bookmark.namedDestination).toBeDefined();
        expect(bookmark.namedDestination.title).toEqual('FirstDestination');
        expect(bookmark._dictionary.get('A').get('D')).toEqual('FirstDestination');
        expect(bookmark._dictionary.get('A').get('S').name).toEqual('GoTo');
        bookmark.color = { r: 255, g: 255, b: 0 };
        bookmark.textStyle = PdfTextStyle.italic | PdfTextStyle.bold;
        expect(bookmarks.count).toEqual(1);
        bookmark = bookmarks.add('SecondBookmark');
        expect(bookmark.title).toEqual('SecondBookmark');
        expect(bookmark.destination).toBeUndefined();
        bookmark.destination = new PdfDestination(page, { x: 10, y: 20 });
        expect(bookmark.destination).toBeDefined();
        expect(bookmark.destination.pageIndex).toEqual(0);
        expect(bookmark.destination.location).toEqual({ x: 10, y: 20 });
        bookmark.namedDestination = new PdfNamedDestination('SecondDestination');
        expect(bookmark.namedDestination).toBeDefined();
        expect(bookmark.namedDestination.title).toEqual('SecondDestination');
        expect(bookmark._dictionary.get('A').get('D')).toEqual('SecondDestination');
        expect(bookmark._dictionary.get('A').get('S').name).toEqual('GoTo');
        bookmark.color = { r: 255, g: 255, b: 0 };
        bookmark.textStyle = PdfTextStyle.italic | PdfTextStyle.bold;
        expect(bookmarks.count).toEqual(2);
        bookmark = bookmarks.add('MiddleBookmark', 1);
        expect(bookmark.title).toEqual('MiddleBookmark');
        expect(bookmark.destination).toBeUndefined();
        bookmark.destination = new PdfDestination(page, { x: 10, y: 20 });
        expect(bookmark.destination).toBeDefined();
        expect(bookmark.destination.pageIndex).toEqual(0);
        expect(bookmark.destination.location).toEqual({ x: 10, y: 20 });
        bookmark.namedDestination = new PdfNamedDestination('MiddleDestination');
        expect(bookmark.namedDestination).toBeDefined();
        expect(bookmark.namedDestination.title).toEqual('MiddleDestination');
        expect(bookmark._dictionary.get('A').get('D')).toEqual('MiddleDestination');
        expect(bookmark._dictionary.get('A').get('S').name).toEqual('GoTo');
        bookmark.color = { r: 255, g: 255, b: 0 };
        bookmark.textStyle = PdfTextStyle.italic | PdfTextStyle.bold;
        expect(bookmarks.count).toEqual(3);
        document.destroy();
    });
    it('Remove multiple newly added child bookmarks', () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        let bookmarks: PdfBookmarkBase = document.bookmarks;
        expect(bookmarks).toBeDefined();
        let bookmark1: PdfBookmark = bookmarks.add('FirstBookmark');
        bookmark1.destination = new PdfDestination(page, { x: 10, y: 10 });
        expect(bookmark1.title).toEqual('FirstBookmark');
        expect(bookmarks.count).toEqual(1);
        expect(bookmark1.count).toEqual(0);
        let bookmark1_1: PdfBookmark = bookmark1.add('First_1');
        bookmark1_1.destination = new PdfDestination(page, { x: 10, y: 30 });
        expect(bookmark1_1.title).toEqual('First_1');
        expect(bookmark1.count).toEqual(1);
        expect(bookmarks.count).toEqual(1);
        let bookmark1_2: PdfBookmark = bookmark1.add('First_2');
        bookmark1_2.destination = new PdfDestination(page, { x: 10, y: 50 });
        expect(bookmark1_2.title).toEqual('First_2');
        expect(bookmark1.count).toEqual(2);
        expect(bookmarks.count).toEqual(1);
        let bookmark2: PdfBookmark = bookmarks.add('SecondBookmark');
        bookmark2.destination = new PdfDestination(page, { x: 30, y: 10 });
        expect(bookmark2.title).toEqual('SecondBookmark');
        expect(bookmarks.count).toEqual(2);
        expect(bookmark2.count).toEqual(0);
        let bookmark2_1: PdfBookmark = bookmark2.add('Second_1');
        bookmark2_1.destination = new PdfDestination(page, { x: 10, y: 30 });
        expect(bookmark2_1.title).toEqual('Second_1');
        expect(bookmark2.count).toEqual(1);
        expect(bookmarks.count).toEqual(2);
        let bookmark2_2: PdfBookmark = bookmark2.add('Second_2');
        bookmark2_2.destination = new PdfDestination(page, { x: 30, y: 50 });
        expect(bookmark2_2.title).toEqual('Second_2');
        expect(bookmark2.count).toEqual(2);
        expect(bookmarks.count).toEqual(2);
        let first: PdfBookmark = bookmarks.at(0);
        expect(first.count).toEqual(2);
        let child1: PdfBookmark = first.add('NewChild_1');
        expect(child1.title).toEqual('NewChild_1');
        expect(child1.destination).toBeUndefined();
        child1.destination = new PdfDestination(first.destination.page, { x: first.destination.location.x + 100, y: first.destination.location.y });
        expect(child1.destination).toBeDefined();
        expect(child1.destination.pageIndex).toEqual(0);
        expect(child1.destination.location).toEqual({ x: first.destination.location.x + 100, y: first.destination.location.y });
        expect(bookmarks.count).toEqual(2);
        expect(first.count).toEqual(3);
        let child2: PdfBookmark = first.add('NewChild_2');
        expect(child2.title).toEqual('NewChild_2');
        expect(child2.destination).toBeUndefined();
        child2.destination = new PdfDestination(first.destination.page, { x: first.destination.location.x + 150, y: first.destination.location.y });
        expect(child2.destination).toBeDefined();
        expect(child2.destination.pageIndex).toEqual(0);
        expect(child2.destination.location).toEqual({ x: first.destination.location.x + 150, y: first.destination.location.y });
        expect(bookmarks.count).toEqual(2);
        expect(first.count).toEqual(4);
        let first_2: PdfBookmark = first.at(1);
        expect(first_2.count).toEqual(0);
        let child3: PdfBookmark = first_2.add('NewChild_3');
        expect(first_2.count).toEqual(1);
        expect(child3.title).toEqual('NewChild_3');
        expect(child3.destination).toBeUndefined();
        child3.destination = new PdfDestination(first_2.destination.page, { x: first_2.destination.location.x + 100, y: first_2.destination.location.y });
        expect(child3.destination).toBeDefined();
        expect(child3.destination.pageIndex).toEqual(0);
        expect(child3.destination.location).toEqual({ x: first_2.destination.location.x + 100, y: first_2.destination.location.y });
        expect(bookmarks.count).toEqual(2);
        expect(first.count).toEqual(4);
        let child4: PdfBookmark = first_2.add('NewChild_4');
        expect(first_2.count).toEqual(2);
        expect(child4.title).toEqual('NewChild_4');
        expect(child4.destination).toBeUndefined();
        child4.destination = new PdfDestination(first_2.destination.page, { x: first_2.destination.location.x + 150, y: first_2.destination.location.y });
        expect(child4.destination).toBeDefined();
        expect(child4.destination.pageIndex).toEqual(0);
        expect(child4.destination.location).toEqual({ x: first_2.destination.location.x + 150, y: first_2.destination.location.y });
        expect(bookmarks.count).toEqual(2);
        expect(first.count).toEqual(4);
        expect(child4.count).toEqual(0);
        let child5: PdfBookmark = child4.add('NewChild_5');
        expect(child5.title).toEqual('NewChild_5');
        expect(child5.destination).toBeUndefined();
        child5.destination = new PdfDestination(child4.destination.page, { x: child4.destination.location.x + 50, y: child4.destination.location.y });
        expect(child5.destination).toBeDefined();
        expect(child5.destination.pageIndex).toEqual(0);
        expect(child5.destination.location).toEqual({ x: child4.destination.location.x + 50, y: child4.destination.location.y });
        expect(bookmarks.count).toEqual(2);
        expect(first.count).toEqual(4);
        expect(child4.count).toEqual(1);
        expect(child5.count).toEqual(0);
        bookmarks.remove('SecondBookmark');
        expect(bookmarks.count).toEqual(1);
        bookmarks.remove('NewChild_5');
        expect(child4.count).toEqual(0);
        expect(bookmarks.count).toEqual(1);
        bookmark1.remove('First_1');
        expect(bookmarks.count).toEqual(1);
        expect(bookmark1.count).toEqual(3);
        first.remove(1);
        expect(bookmarks.count).toEqual(1);
        expect(first.count).toEqual(2);
        let chapter1: PdfBookmark = bookmarks.at(0);
        expect(chapter1.title).toEqual('FirstBookmark');
        expect(chapter1.count).toEqual(2);
        let section1_1: PdfBookmark = chapter1.at(0);
        expect(section1_1.title).toEqual('First_2');
        expect(section1_1.count).toEqual(2);
        expect(section1_1.at(0).title).toEqual('NewChild_3');
        expect(section1_1.at(0).count).toEqual(0);
        expect(section1_1.at(1).title).toEqual('NewChild_4');
        expect(section1_1.at(1).count).toEqual(0);
        let section1_2: PdfBookmark = chapter1.at(1);
        expect(section1_2.title).toEqual('NewChild_2');
        expect(section1_2.count).toEqual(0);
        let updatedData = document.save();
        document.destroy();
        document = new PdfDocument(updatedData);
        bookmarks = document.bookmarks;
        expect(bookmarks.count).toEqual(1);
        document.destroy();
    });
    it('clear the bookmark list', () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        let bookmarks: PdfBookmarkBase = document.bookmarks;
        expect(bookmarks).toBeDefined();
        expect(bookmarks.count).toEqual(0);
        let bookmark: PdfBookmark = bookmarks.add('FirstBookmark', 0);
        expect(bookmark.title).toEqual('FirstBookmark');
        expect(bookmark.destination).toBeUndefined();
        bookmark.destination = new PdfDestination(page, { x: 10, y: 10 });
        expect(bookmark.destination).toBeDefined();
        expect(bookmark.destination.pageIndex).toEqual(0);
        expect(bookmark.destination.location).toEqual({ x: 10, y: 10 });
        bookmark.namedDestination = new PdfNamedDestination('FirstDestination');
        expect(bookmark.namedDestination).toBeDefined();
        expect(bookmark.namedDestination.title).toEqual('FirstDestination');
        expect(bookmark._dictionary.get('A').get('D')).toEqual('FirstDestination');
        expect(bookmark._dictionary.get('A').get('S').name).toEqual('GoTo');
        bookmark.color = { r: 255, g: 255, b: 0 };
        bookmark.textStyle = PdfTextStyle.italic | PdfTextStyle.bold;
        expect(bookmarks.count).toEqual(1);
        expect(bookmarks.contains(bookmark)).toBeTruthy();
        bookmark = bookmarks.add('SecondBookmark');
        expect(bookmark.title).toEqual('SecondBookmark');
        expect(bookmark.destination).toBeUndefined();
        bookmark.destination = new PdfDestination(page, { x: 10, y: 20 });
        expect(bookmark.destination).toBeDefined();
        expect(bookmark.destination.pageIndex).toEqual(0);
        expect(bookmark.destination.location).toEqual({ x: 10, y: 20 });
        bookmark.namedDestination = new PdfNamedDestination('SecondDestination');
        expect(bookmark.namedDestination).toBeDefined();
        expect(bookmark.namedDestination.title).toEqual('SecondDestination');
        expect(bookmark._dictionary.get('A').get('D')).toEqual('SecondDestination');
        expect(bookmark._dictionary.get('A').get('S').name).toEqual('GoTo');
        bookmark.color = { r: 255, g: 255, b: 0 };
        bookmark.textStyle = PdfTextStyle.italic | PdfTextStyle.bold;
        expect(bookmarks.count).toEqual(2);
        expect(bookmarks.contains(bookmark)).toBeTruthy();
        bookmark = bookmarks.add('MiddleBookmark', 1);
        expect(bookmark.title).toEqual('MiddleBookmark');
        expect(bookmark.destination).toBeUndefined();
        bookmark.destination = new PdfDestination(page, { x: 10, y: 15 });
        expect(bookmark.destination).toBeDefined();
        expect(bookmark.destination.pageIndex).toEqual(0);
        expect(bookmark.destination.location).toEqual({ x: 10, y: 15 });
        bookmark.namedDestination = new PdfNamedDestination('MiddleDestination');
        expect(bookmark.namedDestination).toBeDefined();
        expect(bookmark.namedDestination.title).toEqual('MiddleDestination');
        expect(bookmark._dictionary.get('A').get('D')).toEqual('MiddleDestination');
        expect(bookmark._dictionary.get('A').get('S').name).toEqual('GoTo');
        bookmark.color = { r: 255, g: 255, b: 0 };
        bookmark.textStyle = PdfTextStyle.italic | PdfTextStyle.bold;
        expect(bookmarks.count).toEqual(3);
        expect(bookmarks.contains(bookmark)).toBeTruthy();
        bookmarks.clear();
        expect(bookmarks.count).toEqual(0);
        expect(bookmarks.contains(bookmark)).toBeFalsy();
        document.destroy();
    });
    it('isExpanded set value else branch', () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        let bookmarks: PdfBookmarkBase = document.bookmarks;
        expect(bookmarks).toBeDefined();
        expect(bookmarks.count).toEqual(0);
        let parent: PdfBookmark = bookmarks.add('FirstBookmark');
        expect(parent.title).toEqual('FirstBookmark');
        expect(parent.destination).toBeUndefined();
        parent.destination = new PdfDestination(page, { x: 10, y: 10 });
        expect(parent.destination).toBeDefined();
        expect(parent.destination.pageIndex).toEqual(0);
        expect(parent.destination.location).toEqual({ x: 10, y: 10 });
        expect(bookmarks.count).toEqual(1);
        expect(parent.count).toEqual(0);
        let child: PdfBookmark = parent.add('First_1');
        expect(child.title).toEqual('First_1');
        expect(child.destination).toBeUndefined();
        child.destination = new PdfDestination(page, { x: 10, y: 30 });
        expect(child.destination).toBeDefined();
        expect(child.destination.pageIndex).toEqual(0);
        expect(child.destination.location).toEqual({ x: 10, y: 30 });
        expect(bookmarks.count).toEqual(1);
        expect(parent.count).toEqual(1);
        expect(parent.isExpanded).toBeTruthy();
        bookmarks.remove('FirstBookmark');
        bookmarks.isExpanded = false;
        expect(bookmarks.isExpanded).toBeFalsy();
        expect(bookmarks.count).toEqual(0);
        document.destroy();
    });
    it("at - method branches check", () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        try {
            let bookmark: PdfBookmarkBase = document.bookmarks.at(0);
        } catch (error) {
            expect(error.message).toBe('Index out of range.');
        }
        let bookmarks: PdfBookmarkBase = document.bookmarks;
        document.destroy();
    });
    it("add- method check", () => {
        let document: PdfDocument = new PdfDocument();
        let bookmarks: any = document.bookmarks;
        bookmarks._dictionary = undefined;
        let bookmark = bookmarks.add("FirstBookmark");
        expect(bookmark).toBeUndefined();
    });

});