import { PdfAnnotation, PdfListFieldItem, PdfTextWebLinkAnnotation } from './../src/pdf/core/annotations/annotation';
import { _ContentParser, _PdfRecord } from './../src/pdf/core/content-parser';
import { _SignatureFlag } from './../src/pdf/core/enumerator';
import { PdfFont, PdfFontFamily, PdfFontStyle } from './../src/pdf/core/fonts/pdf-standard-font';
import { _PdfReader } from './../src/pdf/core/graphics/images/jbig2-image';
import { PdfBrush, PdfGraphics, PdfPen } from './../src/pdf/core/graphics/pdf-graphics';
import { PdfDocument, PdfMargins, PdfPageSettings } from './../src/pdf/core/pdf-document';
import { PdfPage } from './../src/pdf/core/pdf-page';
import { _PdfDictionary, _PdfName } from './../src/pdf/core/pdf-primitives';
import { _PdfFlateStream } from './../src/pdf/core/flate-stream';
import { _PdfStream } from './../src/pdf/core/base-stream';
describe('Default and Getting started', () => {
    it('default sample in the SB samples', () => {
        function drawHeaderPoint(g: PdfGraphics, text: string, y: number, bulletFont: PdfFont, bodyFont: PdfFont, white: PdfBrush, violet: PdfBrush) {
            g.drawString('l', bulletFont, { x: 220, y: y, width: 100, height: 100 }, violet);
            g.drawString(text, bodyFont, { x: 240, y: y, width: 400, height: 100 }, white);
            return y + 15;
        }
        function drawBodyContent(g: PdfGraphics, text: string, y: number, bulletBodyFont: PdfFont, bodyContentFont: PdfFont, white: PdfBrush, violet: PdfBrush) {
            g.drawString('3', bulletBodyFont, { x: 35, y: y, width: 100, height: 100 }, violet);
            g.drawString(text, bodyContentFont, { x: 60, y: y, width: 500, height: 100 }, white);
            return y + 25;
        }
        let pdf: PdfDocument = new PdfDocument();
        let settings: PdfPageSettings = new PdfPageSettings({ margins: new PdfMargins(0) });
        let page: PdfPage = pdf.addPage(settings);
        let g: PdfGraphics = page.graphics;
        let gray: PdfBrush = new PdfBrush({ r: 64, g: 64, b: 64 });
        let black: PdfBrush = new PdfBrush({ r: 0, g: 0, b: 0 });
        let white: PdfBrush = new PdfBrush({ r: 255, g: 255, b: 255 });
        let violet: PdfBrush = new PdfBrush({ r: 255, g: 153, b: 255 });
        let redPen: PdfPen = new PdfPen({ r: 255, g: 0, b: 0 }, 2);
        let violetPen: PdfPen = new PdfPen({ r: 148, g: 0, b: 211 }, 2);
        let greenPen: PdfPen = new PdfPen({ r: 0, g: 128, b: 0 }, 2);
        let bluePen: PdfPen = new PdfPen({ r: 0, g: 0, b: 255 }, 2);
        g.drawRectangle({ x: 0, y: 0, width: g.clientSize.width, height: g.clientSize.height }, gray);
        g.drawRectangle({ x: 0, y: 0, width: g.clientSize.width, height: 130 }, black);
        g.drawRectangle({ x: 0, y: 400, width: g.clientSize.width, height: g.clientSize.height - 450 }, white);
        let headerFont: PdfFont = pdf.embedFont(PdfFontFamily.timesRoman, 35, PdfFontStyle.regular);
        g.drawString('Enterprise', headerFont, { x: 10, y: 20, width: 150, height: 200 }, violet);
        g.drawRectangle({ x: 10, y: 63, width: 140, height: 35 }, violet);
        let subHeadingFont: PdfFont = pdf.embedFont(PdfFontFamily.timesRoman, 16, PdfFontStyle.regular);
        g.drawString('Reporting Solutions', subHeadingFont, { x: 15, y: 70, width: 130, height: 200 }, black);
        let yPos: number = 30;
        // Header points
        let bodyFont: PdfFont = pdf.embedFont(PdfFontFamily.timesRoman, 11, PdfFontStyle.regular);
        let bulletHeaderFont: PdfFont = pdf.embedFont(PdfFontFamily.zapfDingbats, 10, PdfFontStyle.regular);
        yPos = drawHeaderPoint(g, 'Develop cloud-ready reporting applications in as little as 20% of the time.', yPos, bulletHeaderFont, bodyFont, white, violet);
        yPos = drawHeaderPoint(g, 'Proven, reliable platform thousands of users over the past 10 years.', yPos, bulletHeaderFont, bodyFont, white, violet);
        yPos = drawHeaderPoint(g, 'Microsoft Excel, Word, Adobe PDF, RDL display and editing.', yPos, bulletHeaderFont, bodyFont, white, violet);
        yPos = drawHeaderPoint(g, 'Why start from scratch? Rely on our dependable solution frameworks', yPos, bulletHeaderFont, bodyFont, white, violet);
        // Body content
        yPos += 105;
        let bulletBodyFont: PdfFont = pdf.embedFont(PdfFontFamily.zapfDingbats, 16, PdfFontStyle.regular);
        let bodyContentFont: PdfFont = pdf.embedFont(PdfFontFamily.timesRoman, 17, PdfFontStyle.regular);
        yPos = drawBodyContent(g, 'Deployment-ready framework tailored to your needs.', yPos, bulletBodyFont, bodyContentFont, white, violet);
        yPos = drawBodyContent(g, 'Our architects and developers have years of reporting experience.', yPos, bulletBodyFont, bodyContentFont, white, violet);
        yPos = drawBodyContent(g, 'Solutions available for web, desktop, and mobile applications.', yPos, bulletBodyFont, bodyContentFont, white, violet);
        yPos = drawBodyContent(g, 'Backed by our end-to-end product maintenance infrastructure.', yPos, bulletBodyFont, bodyContentFont, white, violet);
        yPos = drawBodyContent(g, 'The quickest path from concept to delivery.', yPos, bulletBodyFont, bodyContentFont, white, violet);
        let headerBulletsXposition: number = 45;
        yPos = 350;
        // Section 1: The Experts
        let titleFont: PdfFont = pdf.embedFont(PdfFontFamily.timesRoman, 20, PdfFontStyle.regular);
        g.drawLine(redPen, { x: headerBulletsXposition, y: yPos + 92 }, { x: headerBulletsXposition, y: yPos + 145 });
        g.drawString('The Experts', titleFont, { x: headerBulletsXposition + 10, y: yPos + 90, width: 150, height: 200 }, black);
        g.drawLine(violetPen, { x: headerBulletsXposition + 280, y: yPos + 92 }, { x: headerBulletsXposition + 280, y: yPos + 145 });
        g.drawString('Accurate Estimates', titleFont, { x: headerBulletsXposition + 290, y: yPos + 90, width: 300, height: 200 }, black);
        g.drawString('A substantial number of .NET reporting applications use our frameworks', bodyFont, { x: headerBulletsXposition + 10, y: yPos + 115, width: 250, height: 200 }, black);
        g.drawString('Given our expertise, you can expect estimates to be accurate.', bodyFont, { x: headerBulletsXposition + 290, y: yPos + 115, width: 250, height: 200 }, black);
        // Section 2: Product Licensing
        yPos += 200;
        g.drawLine(greenPen, { x: headerBulletsXposition, y: yPos + 32 }, { x: headerBulletsXposition, y: yPos + 85 });
        g.drawString('Product Licensing', titleFont, { x: headerBulletsXposition + 10, y: yPos + 30, width: 250, height: 200 }, black);
        g.drawLine(bluePen, { x: headerBulletsXposition + 280, y: yPos + 32 }, { x: headerBulletsXposition + 280, y: yPos + 85 });
        g.drawString('About Syncfusion', titleFont, { x: headerBulletsXposition + 290, y: yPos + 30, width: 250, height: 200 }, black);
        g.drawString('Solution packages can be combined with product licensing for great cost savings.', bodyFont, { x: headerBulletsXposition + 10, y: yPos + 55, width: 250, height: 200 }, black);
        g.drawString('Syncfusion has more than 7,000 customers including large financial institutions and Fortune 100 companies.', bodyFont, { x: headerBulletsXposition + 290, y: yPos + 55, width: 250, height: 200 }, black);
        // Footer
        let footerFont: PdfFont = pdf.embedFont(PdfFontFamily.timesRoman, 8, PdfFontStyle.italic);
        g.drawString('All trademarks mentioned belong to their owners.', footerFont, { x: 10, y: g.clientSize.height - 30, width: 250, height: 200 }, white);
        let annot: PdfTextWebLinkAnnotation = new PdfTextWebLinkAnnotation(
            { x: g.clientSize.width - 100, y: g.clientSize.height - 30, width: 70, height: 10 },
            { r: 255, g: 255, b: 255 },
            { r: 0, g: 0, b: 0 },
            0,
            { text: 'www.syncfusion.com', font: footerFont, url: 'http://www.syncfusion.com' }
        );
        page.annotations.add(annot);
        const bytes = pdf.save();
        pdf.destroy();
        const parsed: PdfDocument = new PdfDocument(bytes);
        const parsedPage: PdfPage = parsed.getPage(0);
        const contents = parsedPage._pageDictionary.get('Contents');
        const ref = contents[2];
        const stream = parsedPage._crossReference._fetch(ref);
        const parser: _ContentParser = new _ContentParser(stream.getBytes());
        const result: _PdfRecord[] = parser._readContent();
        const fontDictionary: _PdfDictionary = parsedPage._pageDictionary.get('Resources').get('Font');
        const timesRomanRegularRef: string = result[20]._operands[0];
        const zapfDingbatsRef: string = result[39]._operands[0];
        const timesRomanItalicRef = result[235]._operands[0];
        const timesRomanRegular: _PdfName = fontDictionary.get(timesRomanRegularRef.slice(1)).get('BaseFont');
        const zapfDingbats: _PdfName = fontDictionary.get(zapfDingbatsRef.slice(1)).get('BaseFont');
        const timesRomanItalic: _PdfName = fontDictionary.get(timesRomanItalicRef.slice(1)).get('BaseFont');
        //Font check
        expect(timesRomanRegular.name).toEqual('Times-Roman');
        expect(zapfDingbats.name).toEqual('ZapfDingbats');
        expect(timesRomanItalic.name).toEqual('Times-Italic');
        //content level check
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands.length).toBe(0);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['0.000', '0.000', '595.000', '-842.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands.length).toBe(0);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands.length).toBe(0);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands.length).toBe(0);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('rg');
        expect(result[9]._operands).toEqual(['0.251', '0.251', '0.251']);
        expect(result[10]._operator).toEqual('re');
        expect(result[10]._operands).toEqual(['0.000', '0.000', '595.000', '-842.000']);
        expect(result[11]._operator).toEqual('f');
        expect(result[11]._operands.length).toBe(0);
        expect(result[12]._operator).toEqual('rg');
        expect(result[12]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[13]._operator).toEqual('re');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '595.000', '-130.000']);
        expect(result[14]._operator).toEqual('f');
        expect(result[14]._operands.length).toBe(0);
        expect(result[15]._operator).toEqual('rg');
        expect(result[15]._operands).toEqual(['1.000', '1.000', '1.000']);
        expect(result[16]._operator).toEqual('re');
        expect(result[16]._operands).toEqual(['0.000', '-400.000', '595.000', '-392.000']);
        expect(result[17]._operator).toEqual('f');
        expect(result[17]._operands.length).toBe(0);
        expect(result[18]._operator).toEqual('BT');
        expect(result[18]._operands.length).toBe(0);
        expect(result[19]._operator).toEqual('rg');
        expect(result[19]._operands).toEqual(['1.000', '0.600', '1.000']);
        expect(result[20]._operator).toEqual('Tf');
        expect(result[20]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[20]._operands[1]).toEqual('35.000')
        expect(result[21]._operator).toEqual('Tr');
        expect(result[21]._operands).toEqual(['0']);
        expect(result[22]._operator).toEqual('Tc');
        expect(result[22]._operands).toEqual(['0.000']);
        expect(result[23]._operator).toEqual('Tw');
        expect(result[23]._operands).toEqual(['0.000']);
        expect(result[24]._operator).toEqual('Tz');
        expect(result[24]._operands).toEqual(['100.000']);
        expect(result[25]._operator).toEqual('Tm');
        expect(result[25]._operands).toEqual(['1.00', '.00', '.00', '1.00', '10.00', '-51.43']);
        expect(result[26]._operator).toEqual("'");
        expect(result[26]._operands).toEqual(['(Enterprise)']);
        expect(result[27]._operator).toEqual('ET');
        expect(result[27]._operands.length).toBe(0);
        expect(result[28]._operator).toEqual('rg');
        expect(result[28]._operands).toEqual(['1.000', '0.600', '1.000']);
        expect(result[29]._operator).toEqual('re');
        expect(result[29]._operands).toEqual(['10.000', '-63.000', '140.000', '-35.000']);
        expect(result[30]._operator).toEqual('f');
        expect(result[30]._operands.length).toBe(0);
        expect(result[31]._operator).toEqual('BT');
        expect(result[31]._operands.length).toBe(0);
        expect(result[32]._operator).toEqual('rg');
        expect(result[32]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[33]._operator).toEqual('Tf');
        expect(result[33]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[33]._operands[1]).toEqual('16.000');
        expect(result[34]._operator).toEqual('Tm');
        expect(result[34]._operands).toEqual(['1.00', '.00', '.00', '1.00', '15.00', '-84.37']);
        expect(result[35]._operator).toEqual("'");
        expect(result[35]._operands).toEqual(['(Reporting Solutions)']);
        expect(result[36]._operator).toEqual('ET');
        expect(result[36]._operands.length).toBe(0);
        expect(result[37]._operator).toEqual('BT');
        expect(result[37]._operands.length).toBe(0);
        expect(result[38]._operator).toEqual('rg');
        expect(result[38]._operands).toEqual(['1.000', '0.600', '1.000']);
        expect(result[39]._operator).toEqual('Tf');
        expect(result[39]._operands[0]).toEqual(zapfDingbatsRef);
        expect(result[39]._operands[1]).toEqual('10.000');
        expect(result[40]._operator).toEqual('Tm');
        expect(result[40]._operands).toEqual(['1.00', '.00', '.00', '1.00', '220.00', '-38.20']);
        expect(result[41]._operator).toEqual("'");
        expect(result[41]._operands).toEqual(['(l)']);
        expect(result[42]._operator).toEqual('ET');
        expect(result[42]._operands.length).toBe(0);
        //Header point check
        expect(result[43]._operator).toEqual('BT');
        expect(result[43]._operands.length).toBe(0);
        expect(result[44]._operator).toEqual('rg');
        expect(result[44]._operands).toEqual(['1.000', '1.000', '1.000']);
        expect(result[45]._operator).toEqual('Tf');
        expect(result[45]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[45]._operands[1]).toEqual('11.000');
        expect(result[46]._operator).toEqual('Tm');
        expect(result[46]._operands).toEqual(['1.00', '.00', '.00', '1.00', '240.00', '-39.88']);
        expect(result[47]._operator).toEqual("'");
        expect(result[47]._operands).toEqual(['(Develop cloud-ready reporting applications in as little as 20% of the time.)']);
        expect(result[48]._operator).toEqual('ET');
        expect(result[48]._operands.length).toBe(0);
        expect(result[49]._operator).toEqual('BT');
        expect(result[49]._operands.length).toBe(0);
        expect(result[50]._operator).toEqual('rg');
        expect(result[50]._operands).toEqual(['1.000', '0.600', '1.000']);
        expect(result[51]._operator).toEqual('Tf');
        expect(result[51]._operands[0]).toEqual(zapfDingbatsRef);
        expect(result[51]._operands[1]).toEqual('10.000');
        expect(result[52]._operator).toEqual('Tm');
        expect(result[52]._operands).toEqual(['1.00', '.00', '.00', '1.00', '220.00', '-53.20']);
        expect(result[53]._operator).toEqual("'");
        expect(result[53]._operands).toEqual(['(l)']);
        expect(result[54]._operator).toEqual('ET');
        expect(result[54]._operands.length).toBe(0);
        expect(result[55]._operator).toEqual('BT');
        expect(result[55]._operands.length).toBe(0);
        expect(result[56]._operator).toEqual('rg');
        expect(result[56]._operands).toEqual(['1.000', '1.000', '1.000']);
        expect(result[57]._operator).toEqual('Tf');
        expect(result[57]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[57]._operands[1]).toEqual('11.000');
        expect(result[58]._operator).toEqual('Tm');
        expect(result[58]._operands).toEqual(['1.00', '.00', '.00', '1.00', '240.00', '-54.88']);
        expect(result[59]._operator).toEqual("'");
        expect(result[59]._operands).toEqual(['(Proven, reliable platform thousands of users over the past 10 years.)']);
        expect(result[60]._operator).toEqual('ET');
        expect(result[60]._operands.length).toBe(0);
        expect(result[61]._operator).toEqual('BT');
        expect(result[61]._operands.length).toBe(0);
        expect(result[62]._operator).toEqual('rg');
        expect(result[62]._operands).toEqual(['1.000', '0.600', '1.000']);
        expect(result[63]._operator).toEqual('Tf');
        expect(result[63]._operands[0]).toEqual(zapfDingbatsRef);
        expect(result[63]._operands[1]).toEqual('10.000');
        expect(result[64]._operator).toEqual('Tm');
        expect(result[64]._operands).toEqual(['1.00', '.00', '.00', '1.00', '220.00', '-68.20']);
        expect(result[65]._operator).toEqual("'");
        expect(result[65]._operands).toEqual(['(l)']);
        expect(result[66]._operator).toEqual('ET');
        expect(result[66]._operands.length).toBe(0);
        expect(result[67]._operator).toEqual('BT');
        expect(result[67]._operands.length).toBe(0);
        expect(result[68]._operator).toEqual('rg');
        expect(result[68]._operands).toEqual(['1.000', '1.000', '1.000']);
        expect(result[69]._operator).toEqual('Tf');
        expect(result[69]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[69]._operands[1]).toEqual('11.000');
        expect(result[70]._operator).toEqual('Tm');
        expect(result[70]._operands).toEqual(['1.00', '.00', '.00', '1.00', '240.00', '-69.88']);
        expect(result[71]._operator).toEqual("'");
        expect(result[71]._operands).toEqual(['(Microsoft Excel, Word, Adobe PDF, RDL display and editing.)']);
        expect(result[72]._operator).toEqual('ET');
        expect(result[72]._operands.length).toBe(0);
        expect(result[73]._operator).toEqual('BT');
        expect(result[73]._operands.length).toBe(0);
        expect(result[74]._operator).toEqual('rg');
        expect(result[74]._operands).toEqual(['1.000', '0.600', '1.000']);
        expect(result[75]._operator).toEqual('Tf');
        expect(result[75]._operands[0]).toEqual(zapfDingbatsRef);
        expect(result[75]._operands[1]).toEqual('10.000');
        expect(result[76]._operator).toEqual('Tm');
        expect(result[76]._operands).toEqual(['1.00', '.00', '.00', '1.00', '220.00', '-83.20']);
        expect(result[77]._operator).toEqual("'");
        expect(result[77]._operands).toEqual(['(l)']);
        expect(result[78]._operator).toEqual('ET');
        expect(result[78]._operands.length).toBe(0);
        expect(result[79]._operator).toEqual('BT');
        expect(result[79]._operands.length).toBe(0);
        expect(result[80]._operator).toEqual('rg');
        expect(result[80]._operands).toEqual(['1.000', '1.000', '1.000']);
        expect(result[81]._operator).toEqual('Tf');
        expect(result[81]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[81]._operands[1]).toEqual('11.000');
        expect(result[82]._operator).toEqual('Tm');
        expect(result[82]._operands).toEqual(['1.00', '.00', '.00', '1.00', '240.00', '-84.88']);
        expect(result[83]._operator).toEqual("'");
        expect(result[83]._operands).toEqual(['(Why start from scratch? Rely on our dependable solution frameworks)']);
        expect(result[84]._operator).toEqual('ET');
        expect(result[84]._operands.length).toBe(0);
        expect(result[85]._operator).toEqual('BT');
        expect(result[85]._operands.length).toBe(0);
        expect(result[86]._operator).toEqual('rg');
        expect(result[86]._operands).toEqual(['1.000', '0.600', '1.000']);
        expect(result[87]._operator).toEqual('Tf');
        expect(result[87]._operands[0]).toEqual(zapfDingbatsRef);
        expect(result[87]._operands[1]).toEqual('16.000');
        expect(result[88]._operator).toEqual('Tm');
        expect(result[88]._operands).toEqual(['1.00', '.00', '.00', '1.00', '35.00', '-208.12']);
        expect(result[89]._operator).toEqual("'");
        expect(result[89]._operands).toEqual(['(3)']);
        expect(result[90]._operator).toEqual('ET');
        expect(result[90]._operands.length).toBe(0);
        expect(result[91]._operator).toEqual('BT');
        expect(result[91]._operands.length).toBe(0);
        expect(result[92]._operator).toEqual('rg');
        expect(result[92]._operands).toEqual(['1.000', '1.000', '1.000']);
        expect(result[93]._operator).toEqual('Tf');
        expect(result[93]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[93]._operands[1]).toEqual('17.000');
        expect(result[94]._operator).toEqual('Tm');
        expect(result[94]._operands).toEqual(['1.00', '.00', '.00', '1.00', '60.00', '-210.27']);
        expect(result[95]._operator).toEqual("'");
        expect(result[95]._operands).toEqual(['(Deployment-ready framework tailored to your needs.)']);
        expect(result[96]._operator).toEqual('ET');
        expect(result[96]._operands.length).toBe(0);
        expect(result[97]._operator).toEqual('BT');
        expect(result[97]._operands.length).toBe(0);
        expect(result[98]._operator).toEqual('rg');
        expect(result[98]._operands).toEqual(['1.000', '0.600', '1.000']);
        expect(result[99]._operator).toEqual('Tf');
        expect(result[99]._operands[0]).toEqual(zapfDingbatsRef);
        expect(result[99]._operands[1]).toEqual('16.000');
        expect(result[100]._operator).toEqual('Tm');
        expect(result[100]._operands).toEqual(['1.00', '.00', '.00', '1.00', '35.00', '-233.12']);
        expect(result[101]._operator).toEqual("'");
        expect(result[101]._operands).toEqual(['(3)']);
        expect(result[102]._operator).toEqual('ET');
        expect(result[102]._operands.length).toBe(0);
        expect(result[103]._operator).toEqual('BT');
        expect(result[103]._operands.length).toBe(0);
        expect(result[104]._operator).toEqual('rg');
        expect(result[104]._operands).toEqual(['1.000', '1.000', '1.000']);
        expect(result[105]._operator).toEqual('Tf');
        expect(result[105]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[105]._operands[1]).toEqual('17.000');
        expect(result[106]._operator).toEqual('Tm');
        expect(result[106]._operands).toEqual(['1.00', '.00', '.00', '1.00', '60.00', '-235.27']);
        expect(result[107]._operator).toEqual("'");
        expect(result[107]._operands).toEqual(['(Our architects and developers have years of reporting experience.)']);
        expect(result[108]._operator).toEqual('ET');
        expect(result[108]._operands.length).toBe(0);
        expect(result[109]._operator).toEqual('BT');
        expect(result[109]._operands.length).toBe(0);
        expect(result[110]._operator).toEqual('rg');
        expect(result[110]._operands).toEqual(['1.000', '0.600', '1.000']);
        expect(result[111]._operator).toEqual('Tf');
        expect(result[111]._operands[0]).toEqual(zapfDingbatsRef);
        expect(result[111]._operands[1]).toEqual('16.000');
        expect(result[112]._operator).toEqual('Tm');
        expect(result[112]._operands).toEqual(['1.00', '.00', '.00', '1.00', '35.00', '-258.12']);
        expect(result[113]._operator).toEqual("'");
        expect(result[113]._operands).toEqual(['(3)']);
        expect(result[114]._operator).toEqual('ET');
        expect(result[114]._operands.length).toBe(0);
        expect(result[115]._operator).toEqual('BT');
        expect(result[115]._operands.length).toBe(0);
        expect(result[116]._operator).toEqual('rg');
        expect(result[116]._operands).toEqual(['1.000', '1.000', '1.000']);
        expect(result[117]._operator).toEqual('Tf');
        expect(result[117]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[117]._operands[1]).toEqual('17.000');
        expect(result[118]._operator).toEqual('Tm');
        expect(result[118]._operands).toEqual(['1.00', '.00', '.00', '1.00', '60.00', '-260.27']);
        expect(result[119]._operator).toEqual("'");
        expect(result[119]._operands).toEqual(['(Solutions available for web, desktop, and mobile applications.)']);
        expect(result[120]._operator).toEqual('ET');
        expect(result[120]._operands.length).toBe(0);
        expect(result[121]._operator).toEqual('BT');
        expect(result[121]._operands.length).toBe(0);
        expect(result[122]._operator).toEqual('rg');
        expect(result[122]._operands).toEqual(['1.000', '0.600', '1.000']);
        expect(result[123]._operator).toEqual('Tf');
        expect(result[123]._operands[0]).toEqual(zapfDingbatsRef);
        expect(result[123]._operands[1]).toEqual('16.000');
        expect(result[124]._operator).toEqual('Tm');
        expect(result[124]._operands).toEqual(['1.00', '.00', '.00', '1.00', '35.00', '-283.12']);
        expect(result[125]._operator).toEqual("'");
        expect(result[125]._operands).toEqual(['(3)']);
        expect(result[126]._operator).toEqual('ET');
        expect(result[126]._operands.length).toBe(0);
        expect(result[127]._operator).toEqual('BT');
        expect(result[127]._operands.length).toBe(0);
        expect(result[128]._operator).toEqual('rg');
        expect(result[128]._operands).toEqual(['1.000', '1.000', '1.000']);
        expect(result[129]._operator).toEqual('Tf');
        expect(result[129]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[129]._operands[1]).toEqual('17.000');
        expect(result[130]._operator).toEqual('Tm');
        expect(result[130]._operands).toEqual(['1.00', '.00', '.00', '1.00', '60.00', '-285.27']);
        expect(result[131]._operator).toEqual("'");
        expect(result[131]._operands).toEqual(['(Backed by our end-to-end product maintenance infrastructure.)']);
        expect(result[132]._operator).toEqual('ET');
        expect(result[132]._operands.length).toBe(0);
        expect(result[133]._operator).toEqual('BT');
        expect(result[133]._operands.length).toBe(0);
        expect(result[134]._operator).toEqual('rg');
        expect(result[134]._operands).toEqual(['1.000', '0.600', '1.000']);
        expect(result[135]._operator).toEqual('Tf');
        expect(result[135]._operands[0]).toEqual(zapfDingbatsRef);
        expect(result[135]._operands[1]).toEqual('16.000');
        expect(result[136]._operator).toEqual('Tm');
        expect(result[136]._operands).toEqual(['1.00', '.00', '.00', '1.00', '35.00', '-308.12']);
        expect(result[137]._operator).toEqual("'");
        expect(result[137]._operands).toEqual(['(3)']);
        expect(result[138]._operator).toEqual('ET');
        expect(result[138]._operands.length).toBe(0);
        expect(result[139]._operator).toEqual('BT');
        expect(result[139]._operands.length).toBe(0);
        expect(result[140]._operator).toEqual('rg');
        expect(result[140]._operands).toEqual(['1.000', '1.000', '1.000']);
        expect(result[141]._operator).toEqual('Tf');
        expect(result[141]._operator).toEqual('Tf');
        expect(result[141]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[129]._operands[1]).toEqual('17.000');
        expect(result[142]._operator).toEqual('Tm');
        expect(result[142]._operands).toEqual(['1.00', '.00', '.00', '1.00', '60.00', '-310.27']);
        expect(result[143]._operator).toEqual("'");
        expect(result[143]._operands).toEqual(['(The quickest path from concept to delivery.)']);
        expect(result[144]._operator).toEqual('ET');
        expect(result[144]._operands.length).toBe(0);
        expect(result[145]._operator).toEqual('d');
        expect(result[145]._operands).toEqual(['[]', '0']);
        expect(result[146]._operator).toEqual('w');
        expect(result[146]._operands).toEqual(['2.000']);
        expect(result[147]._operator).toEqual('j');
        expect(result[147]._operands).toEqual(['0']);
        expect(result[148]._operator).toEqual('J');
        expect(result[148]._operands).toEqual(['0']);
        expect(result[149]._operator).toEqual('RG');
        expect(result[149]._operands).toEqual(['1.000', '0.000', '0.000']);
        expect(result[150]._operator).toEqual('m');
        expect(result[150]._operands).toEqual(['45.000', '-442.000']);
        expect(result[151]._operator).toEqual('l');
        expect(result[151]._operands).toEqual(['45.000', '-495.000']);
        expect(result[152]._operator).toEqual('S');
        expect(result[152]._operands.length).toBe(0);
        //Section one check
        expect(result[153]._operator).toEqual('BT');
        expect(result[153]._operands.length).toBe(0);
        expect(result[154]._operator).toEqual('rg');
        expect(result[154]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[155]._operator).toEqual('Tf');
        expect(result[155]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[155]._operands[1]).toEqual('20.000');
        expect(result[156]._operator).toEqual('Tm');
        expect(result[156]._operands).toEqual(['1.00', '.00', '.00', '1.00', '55.00', '-457.96']);
        expect(result[157]._operator).toEqual("'");
        expect(result[157]._operands).toEqual(['(The Experts)']);
        expect(result[158]._operator).toEqual('ET');
        expect(result[158]._operands.length).toBe(0);
        expect(result[159]._operator).toEqual('d');
        expect(result[159]._operands).toEqual(['[]', '0']);
        expect(result[160]._operator).toEqual('w');
        expect(result[160]._operands).toEqual(['2.000']);
        expect(result[161]._operator).toEqual('j');
        expect(result[161]._operands).toEqual(['0']);
        expect(result[162]._operator).toEqual('J');
        expect(result[162]._operands).toEqual(['0']);
        expect(result[163]._operator).toEqual('RG');
        expect(result[163]._operands).toEqual(['0.580', '0.000', '0.827']);
        expect(result[164]._operator).toEqual('m');
        expect(result[164]._operands).toEqual(['325.000', '-442.000']);
        expect(result[165]._operator).toEqual('l');
        expect(result[165]._operands).toEqual(['325.000', '-495.000']);
        expect(result[166]._operator).toEqual('S');
        expect(result[166]._operands.length).toBe(0);
        expect(result[167]._operator).toEqual('BT');
        expect(result[167]._operands.length).toBe(0);
        expect(result[168]._operator).toEqual('rg');
        expect(result[168]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[169]._operator).toEqual('Tf');
        expect(result[169]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[169]._operands[1]).toEqual('20.000');
        expect(result[170]._operator).toEqual('Tm');
        expect(result[170]._operands).toEqual(['1.00', '.00', '.00', '1.00', '335.00', '-457.96']);
        expect(result[171]._operator).toEqual("'");
        expect(result[171]._operands).toEqual(['(Accurate Estimates)']);
        expect(result[172]._operator).toEqual('ET');
        expect(result[172]._operands.length).toBe(0);
        expect(result[173]._operator).toEqual('BT');
        expect(result[173]._operands.length).toBe(0);
        expect(result[174]._operator).toEqual('rg');
        expect(result[174]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[175]._operator).toEqual('Tf');
        expect(result[175]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[175]._operands[1]).toEqual('11.000');
        expect(result[176]._operator).toEqual('Tm');
        expect(result[176]._operands).toEqual(['1.00', '.00', '.00', '1.00', '55.00', '-474.88']);
        expect(result[177]._operator).toEqual("'");
        expect(result[177]._operands).toEqual(['(A substantial number of .NET reporting applications use)']);
        expect(result[178]._operator).toEqual('Tm');
        expect(result[178]._operands).toEqual(['1.00', '.00', '.00', '1.00', '55.00', '-487.15']);
        expect(result[179]._operator).toEqual("'");
        expect(result[179]._operands).toEqual(['(our frameworks)']);
        expect(result[180]._operator).toEqual('ET');
        expect(result[180]._operands.length).toBe(0);
        expect(result[181]._operator).toEqual('BT');
        expect(result[181]._operands.length).toBe(0);
        expect(result[182]._operator).toEqual('rg');
        expect(result[182]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[183]._operator).toEqual('Tf');
        expect(result[183]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[183]._operands[1]).toEqual('11.000');
        expect(result[184]._operator).toEqual('Tm');
        expect(result[184]._operands).toEqual(['1.00', '.00', '.00', '1.00', '335.00', '-474.88']);
        expect(result[185]._operator).toEqual("'");
        expect(result[185]._operands).toEqual(['(Given our expertise, you can expect estimates to be)']);
        expect(result[186]._operator).toEqual('Tm');
        expect(result[186]._operands).toEqual(['1.00', '.00', '.00', '1.00', '335.00', '-487.15']);
        expect(result[187]._operator).toEqual("'");
        expect(result[187]._operands).toEqual(['(accurate.)']);
        expect(result[188]._operator).toEqual('ET');
        expect(result[188]._operands.length).toBe(0);
        expect(result[189]._operator).toEqual('d');
        expect(result[189]._operands).toEqual(['[]', '0']);
        expect(result[190]._operator).toEqual('w');
        expect(result[190]._operands).toEqual(['2.000']);
        expect(result[191]._operator).toEqual('j');
        expect(result[191]._operands).toEqual(['0']);
        expect(result[192]._operator).toEqual('J');
        expect(result[192]._operands).toEqual(['0']);
        expect(result[193]._operator).toEqual('RG');
        expect(result[193]._operands).toEqual(['0.000', '0.502', '0.000']);
        expect(result[194]._operator).toEqual('m');
        expect(result[194]._operands).toEqual(['45.000', '-582.000']);
        expect(result[195]._operator).toEqual('l');
        expect(result[195]._operands).toEqual(['45.000', '-635.000']);
        expect(result[196]._operator).toEqual('S');
        expect(result[196]._operands.length).toBe(0);
        // Section Two check
        expect(result[197]._operator).toEqual('BT');
        expect(result[197]._operands.length).toBe(0);
        expect(result[198]._operator).toEqual('rg');
        expect(result[198]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[199]._operator).toEqual('Tf');
        expect(result[199]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[199]._operands[1]).toEqual('20.000');
        expect(result[200]._operator).toEqual('Tm');
        expect(result[200]._operands).toEqual(['1.00', '.00', '.00', '1.00', '55.00', '-597.96']);
        expect(result[201]._operator).toEqual("'");
        expect(result[201]._operands).toEqual(['(Product Licensing)']);
        expect(result[202]._operator).toEqual('ET');
        expect(result[202]._operands.length).toBe(0);
        expect(result[203]._operator).toEqual('d');
        expect(result[203]._operands).toEqual(['[]', '0']);
        expect(result[204]._operator).toEqual('w');
        expect(result[204]._operands).toEqual(['2.000']);
        expect(result[205]._operator).toEqual('j');
        expect(result[205]._operands).toEqual(['0']);
        expect(result[206]._operator).toEqual('J');
        expect(result[206]._operands).toEqual(['0']);
        expect(result[207]._operator).toEqual('RG');
        expect(result[207]._operands).toEqual(['0.000', '0.000', '1.000']);
        expect(result[208]._operator).toEqual('m');
        expect(result[208]._operands).toEqual(['325.000', '-582.000']);
        expect(result[209]._operator).toEqual('l');
        expect(result[209]._operands).toEqual(['325.000', '-635.000']);
        expect(result[210]._operator).toEqual('S');
        expect(result[210]._operands.length).toBe(0);
        expect(result[211]._operator).toEqual('BT');
        expect(result[211]._operands.length).toBe(0);
        expect(result[212]._operator).toEqual('rg');
        expect(result[212]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[213]._operator).toEqual('Tf');
        expect(result[213]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[213]._operands[1]).toEqual('20.000');
        expect(result[214]._operator).toEqual('Tm');
        expect(result[214]._operands).toEqual(['1.00', '.00', '.00', '1.00', '335.00', '-597.96']);
        expect(result[215]._operator).toEqual("'");
        expect(result[215]._operands).toEqual(['(About Syncfusion)']);
        expect(result[216]._operator).toEqual('ET');
        expect(result[216]._operands.length).toBe(0);
        expect(result[217]._operator).toEqual('BT');
        expect(result[217]._operands.length).toBe(0);
        expect(result[218]._operator).toEqual('rg');
        expect(result[218]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[219]._operator).toEqual('Tf');
        expect(result[219]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[219]._operands[1]).toEqual('11.000');
        expect(result[220]._operator).toEqual('Tm');
        expect(result[220]._operands).toEqual(['1.00', '.00', '.00', '1.00', '55.00', '-614.88']);
        expect(result[221]._operator).toEqual("'");
        expect(result[221]._operands).toEqual(['(Solution packages can be combined with product)']);
        expect(result[222]._operator).toEqual('Tm');
        expect(result[222]._operands).toEqual(['1.00', '.00', '.00', '1.00', '55.00', '-627.15']);
        expect(result[223]._operator).toEqual("'");
        expect(result[223]._operands).toEqual(['(licensing for great cost savings.)']);
        expect(result[224]._operator).toEqual('ET');
        expect(result[224]._operands.length).toBe(0);
        expect(result[225]._operator).toEqual('BT');
        expect(result[225]._operands.length).toBe(0);
        expect(result[226]._operator).toEqual('rg');
        expect(result[226]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[227]._operator).toEqual('Tf');
        expect(result[227]._operands[0]).toEqual(timesRomanRegularRef);
        expect(result[227]._operands[1]).toEqual('11.000');
        expect(result[228]._operator).toEqual('Tm');
        expect(result[228]._operands).toEqual(['1.00', '.00', '.00', '1.00', '335.00', '-614.88']);
        expect(result[229]._operator).toEqual("'");
        expect(result[229]._operands).toEqual(['(Syncfusion has more than 7,000 customers including)']);
        expect(result[230]._operator).toEqual('Tm');
        expect(result[230]._operands).toEqual(['1.00', '.00', '.00', '1.00', '335.00', '-627.15']);
        expect(result[231]._operator).toEqual("'");
        expect(result[231]._operands).toEqual(['(large financial institutions and Fortune 100 companies.)']);
        expect(result[232]._operator).toEqual('ET');
        expect(result[232]._operands.length).toBe(0);
        //Footer check
        expect(result[233]._operator).toEqual('BT');
        expect(result[233]._operands.length).toBe(0);
        expect(result[234]._operator).toEqual('rg');
        expect(result[234]._operands).toEqual(['1.000', '1.000', '1.000']);
        expect(result[235]._operator).toEqual('Tf');
        expect(result[235]._operands[0]).toEqual(timesRomanItalicRef);
        expect(result[235]._operands[1]).toEqual('8.000');
        expect(result[236]._operator).toEqual('Tm');
        expect(result[236]._operands).toEqual(['1.00', '.00', '.00', '1.00', '10.00', '-819.06']);
        expect(result[237]._operator).toEqual("'");
        expect(result[237]._operands).toEqual(['(All trademarks mentioned belong to their owners.)']);
        expect(result[238]._operator).toEqual('ET');
        expect(result[238]._operands.length).toBe(0);
        //Annotation Check 
        const annotation: PdfAnnotation = parsedPage.annotations.at(0);
        expect(annotation._dictionary.get('Contents')).toEqual('www.syncfusion.com');
        const url = annotation._dictionary.get('A').get('URI');
        expect(url).toEqual('http://www.syncfusion.com');
        parsed.destroy();
    });
    it('Hello World Sample', () => {
        // Create a new PDF document
        let pdf = new PdfDocument();
        // Add a new page
        let page = pdf.addPage();
        // Access graphics of the page
        let graphics = page.graphics;
        // Create a new PDF standard font
        let font = pdf.embedFont(PdfFontFamily.helvetica, 36, PdfFontStyle.regular);
        // Create a new black brush
        let brush = new PdfBrush({ r: 0, g: 0, b: 0 });
        // Draw the text
        graphics.drawString('Hello World!!!', font, { x: 20, y: 20, width: graphics.clientSize.width - 20, height: 60 }, brush);
        // Save and download PDF
        const bytes = pdf.save();
        // Destroy the PDF document instance
        pdf.destroy();
        const parsed: PdfDocument = new PdfDocument(bytes);
        const parsedPage: PdfPage = parsed.getPage(0);
        const contents = parsedPage._pageDictionary.get('Contents');
        const ref = contents[2];
        const stream = parsedPage._crossReference._fetch(ref);
        const parser: _ContentParser = new _ContentParser(stream.getBytes());
        const result: _PdfRecord[] = parser._readContent();
        //Font check
        const fontDictionary: _PdfDictionary = parsedPage._pageDictionary.get('Resources').get('Font');
        const HelveticaRef: string = result[11]._operands[0];
        const Helvetica: _PdfName = fontDictionary.get(HelveticaRef.slice(1)).get('BaseFont');
        //Content level check
        expect(Helvetica.name).toEqual('Helvetica');
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands.length).toBe(0);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['40.000', '-40.000', '515.000', '-762.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands.length).toBe(0);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands.length).toBe(0);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands.length).toBe(0);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '40.00', '-40.00']);
        expect(result[7]._operator).toEqual('BT');
        expect(result[7]._operands.length).toBe(0);
        expect(result[8]._operator).toEqual('CS');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('cs');
        expect(result[9]._operands).toEqual(['/DeviceRGB']);
        expect(result[10]._operator).toEqual('rg');
        expect(result[10]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[11]._operator).toEqual('Tf');
        expect(result[11]._operands[0]).toEqual(HelveticaRef);
        expect(result[11]._operands[1]).toEqual('36.000');
        expect(result[12]._operator).toEqual('Tr');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('Tc');
        expect(result[13]._operands).toEqual(['0.000']);
        expect(result[14]._operator).toEqual('Tw');
        expect(result[14]._operands).toEqual(['0.000']);
        expect(result[15]._operator).toEqual('Tz');
        expect(result[15]._operands).toEqual(['100.000']);
        expect(result[16]._operator).toEqual('Tm');
        expect(result[16]._operands).toEqual(['1.00', '.00', '.00', '1.00', '20.00', '-53.52']);
        expect(result[17]._operator).toEqual("'");
        expect(result[17]._operands).toEqual(['(Hello World!!!)']);
        expect(result[18]._operator).toEqual('ET');
        expect(result[18]._operands.length).toBe(0);
        parsed.destroy();
    });
    it('Removing and adding page to document', () => {
        // Create a new PDF document
        let pdf = new PdfDocument();
        // Add a new page
        pdf.addPage();
        expect(pdf.pageCount).toBe(1);
        // Get page to check remove
        let removablePage = pdf.getPage(pdf.pageCount - 1);
        // Remove the page
        pdf.removePage(removablePage);
        expect(pdf.pageCount).toBe(0);
        // Destroy the PDF document instance
        pdf.destroy();
        
    });
});

