import { _PdfContentStream } from '../src/pdf/core/base-stream';
import { _ContentParser, _PdfRecord } from '../src/pdf/core/content-parser';
import { PdfCjkFontFamily, PdfCjkStandardFont, PdfFontFamily, PdfFontStyle, PdfStandardFont, PdfTrueTypeFont } from '../src/pdf/core/fonts/pdf-standard-font';
import { PdfBrush, PdfPen } from '../src/pdf/core/graphics/pdf-graphics';
import { PdfTemplate } from '../src/pdf/core/graphics/pdf-template';
import { PdfDocument } from '../src/pdf/core/pdf-document';
import { PdfPage } from '../src/pdf/core/pdf-page';
import { _PdfDictionary } from '../src/pdf/core/pdf-primitives';
import { ttfData } from './inputs.spec';
describe('998488 - Easy access to embedded font', () => {
    it('998488 - check1', () => {
        const doc: PdfDocument = new PdfDocument();
        const cjkfont: PdfCjkStandardFont = doc.embedFont(PdfCjkFontFamily.heiseiKakuGothicW5, 16, PdfFontStyle.regular, true);
        cjkfont.getFont(17, PdfFontStyle.regular);
        cjkfont.getFont(18, PdfFontStyle.regular);
        cjkfont.getFont(19, PdfFontStyle.regular);
        expect(doc._fontCollection.size).toEqual(1);
        doc.destroy();
    });
    it('998488 - check2', () => {
        const doc: PdfDocument = new PdfDocument();
        const standardfont: PdfStandardFont =  doc.embedFont(PdfFontFamily.timesRoman, 16, PdfFontStyle.regular);
        standardfont.getFont(17, PdfFontStyle.regular);
        standardfont.getFont(18, PdfFontStyle.regular);
        standardfont.getFont(19, PdfFontStyle.regular);
        expect(doc._fontCollection.size).toEqual(1);
        doc.destroy();
    });
    it('998488 - check3', () => {
        const doc: PdfDocument = new PdfDocument();
        const standardfont: PdfTrueTypeFont =  doc.embedFont(ttfData, 16);
        standardfont.getFont(17);
        standardfont.getFont(18);
        standardfont.getFont(19);
        expect(doc._fontCollection.size).toEqual(1);
        doc.destroy();
    });
    it('998488 - check4', () => {
        const doc: PdfDocument = new PdfDocument();
        const cjkfont: PdfCjkStandardFont =  doc.embedFont(PdfCjkFontFamily.heiseiKakuGothicW5, 16, PdfFontStyle.italic, true);
        cjkfont.getFont(16, PdfFontStyle.bold);
        cjkfont.getFont(16, PdfFontStyle.regular);
        expect(doc._fontCollection.size).toEqual(3);
        doc.destroy();
    });
    it('998488 - check5', () => {
        const doc: PdfDocument = new PdfDocument();
        const standardfont: PdfStandardFont =  doc.embedFont(PdfFontFamily.timesRoman, 16, PdfFontStyle.regular);
        standardfont.getFont(16, PdfFontStyle.italic);
        standardfont.getFont(16, PdfFontStyle.bold);
        expect(doc._fontCollection.size).toEqual(3);
        doc.destroy();
    });
    it('998488 - check6', () => {
        const doc: PdfDocument = new PdfDocument();
        let embedded = doc.embedFont(PdfFontFamily.timesRoman, 16, PdfFontStyle.regular);
        let embedded1 = embedded.getFont(15, PdfFontStyle.italic);
        let embedded2 = embedded.getFont(14, PdfFontStyle.bold);
        expect(doc._fontCollection.size).toEqual(3);
        doc.destroy();
    });
	it('998488 - check7', () => {
        const doc: PdfDocument = new PdfDocument();
        const standardfont: PdfTrueTypeFont =  doc.embedFont(ttfData, 16);
        standardfont.getFont(17, PdfFontStyle.strikeout);
        standardfont.getFont(18, PdfFontStyle.underline);
        standardfont.getFont(19, PdfFontStyle.regular);
        expect(doc._fontCollection.size).toEqual(1);
        doc.destroy();
    });
	it('998488 - single page - embedded standardFont with different styles', () => {
        let doc: PdfDocument = new PdfDocument();
        let page: PdfPage = doc.addPage();
        let pen: any;
        const embedded = doc.embedFont(PdfFontFamily.timesRoman, 12,  PdfFontStyle.regular);
        page.graphics.drawString('timesRoman with regular', embedded, {x: 10, y: 10, width: 300, height: 24}, pen);
        const embedded1 = embedded.getFont(14, PdfFontStyle.bold);
        page.graphics.drawString('timesRoman with bold', embedded1, {x: 10, y: 50, width: 300, height: 24}, pen);
        const embedded2 = embedded.getFont(15, PdfFontStyle.italic);
        page.graphics.drawString('timesRoman with bold', embedded2, {x: 10, y: 100, width: 300, height: 24}, pen);
        const embedded3 = doc.embedFont(PdfCjkFontFamily.hanyangSystemsGothicMedium, 12,  PdfFontStyle.regular , true);
        page.graphics.drawString('Cjkfont with regular', embedded3, {x: 200, y: 10, width: 300, height: 24}, pen);
        const embedded4 = embedded3.getFont(14, PdfFontStyle.bold);
        page.graphics.drawString('Cjkfont with bold', embedded4, {x: 200, y: 50, width: 300, height: 24}, pen);
        const embedded5 = embedded3.getFont(15, PdfFontStyle.italic);
        page.graphics.drawString('Cjkfont with bold', embedded5, {x: 200, y: 100, width: 300, height: 24}, pen);
        const output = doc.save();
        expect(output.length).toBeGreaterThan(0);
        doc = new PdfDocument(output);
        page = doc.getPage(0);
        let resources: _PdfDictionary = page._pageDictionary.get('Resources') as _PdfDictionary;
        expect(resources).not.toBeUndefined();
        let fontEntry: _PdfDictionary = resources.get('Font');
        expect(fontEntry.size).toEqual(6);
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        expect(result.length).toEqual(41);
        expect(result[8]._operator).toEqual('Tf');
        expect(result[8]._operands[1]).toEqual('12.000');
        let fontKey1: string = result[8]._operands[0].slice(1);
        let fontDic: _PdfDictionary = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Times-Roman');
        expect(result[17]._operator).toEqual('Tf');
        expect(result[17]._operands[1]).toEqual('14.000');
        let fontKey2: string = result[17]._operands[0].slice(1);
        fontDic = fontEntry.get(fontKey2) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Times-Bold');
        expect(result[22]._operator).toEqual('Tf');
        expect(result[22]._operands[1]).toEqual('15.000');
        let fontKey3: string = result[22]._operands[0].slice(1);
        fontDic = fontEntry.get(fontKey3) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Times-Italic');
        expect(result[27]._operator).toEqual('Tf');
        expect(result[27]._operands[1]).toEqual('12.000');
        let fontKey4: string = result[27]._operands[0].slice(1);
        fontDic = fontEntry.get(fontKey4) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(fontDic.get('BaseFont').name).toEqual('HYGoThic-Medium');
        expect(result[32]._operator).toEqual('Tf');
        expect(result[32]._operands[1]).toEqual('14.000');
        let fontKey5: string = result[32]._operands[0].slice(1);
        fontDic = fontEntry.get(fontKey5) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(fontDic.get('BaseFont').name).toEqual('HYGoThic-Medium,Bold');
        expect(result[37]._operator).toEqual('Tf');
        expect(result[37]._operands[1]).toEqual('15.000');
        let fontKey6: string = result[37]._operands[0].slice(1);
        fontDic = fontEntry.get(fontKey6) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(fontDic.get('BaseFont').name).toEqual('HYGoThic-Medium,Italic');
        doc.destroy();
    });
	it('998488 - single page - embedded standardFont with same styles', () => {
        let doc: PdfDocument = new PdfDocument();
        let page: PdfPage = doc.addPage();
        let pen: any;
        let embedded = doc.embedFont(PdfFontFamily.symbol, 11, PdfFontStyle.regular);
        page.graphics.drawString('String with font size 11', embedded, {x: 10, y: 10, width: 300, height: 200}, new PdfPen({r: 255, g: 0, b:255}, 1), new PdfBrush({r: 255, g: 0, b:255}));
        embedded = embedded.getFont(13, PdfFontStyle.regular);
        page.graphics.drawString('String with font size 13', embedded, {x: 10, y: 30, width: 300, height: 200}, new PdfPen({r: 255, g: 0, b:255}, 1), new PdfBrush({r: 255, g: 0, b:255}));
        embedded = embedded.getFont(14, PdfFontStyle.regular);
        page.graphics.drawString('String with font size 14', embedded, {x: 10, y: 60, width: 300, height: 200}, pen);
        embedded = embedded.getFont(15, PdfFontStyle.regular);
        page.graphics.drawString('String with font size 15', embedded, {x: 10, y: 90, width: 300, height: 200}, pen);
        const output = doc.save() as Uint8Array;
        expect(output.length).toBeGreaterThan(0);
		doc.destroy();
        doc = new PdfDocument(output);
        page = doc.getPage(0);
        let resources: _PdfDictionary = page._pageDictionary.get('Resources') as _PdfDictionary;
        let fontEntry: any = resources.get('Font');
        expect(fontEntry.size).toEqual(1);
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        expect(result.length).toEqual(46);
        expect(result[16]._operator).toEqual('Tf');
        expect(result[16]._operands[1]).toEqual('11.000');
        let fontKey1: string = result[16]._operands[0].slice(1);
        let fontDic: _PdfDictionary = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Symbol');
        expect(result[31]._operator).toEqual('Tf');
        expect(result[31]._operands[1]).toEqual('13.000');
        expect(result[31]._operands[0].slice(1)).toEqual(fontKey1);
        expect(result[36]._operator).toEqual('Tf');
        expect(result[36]._operands[1]).toEqual('14.000');
        expect(result[36]._operands[0].slice(1)).toEqual(fontKey1);
        expect(result[42]._operator).toEqual('Tf');
        expect(result[42]._operands[1]).toEqual('15.000');
        expect(result[42]._operands[0].slice(1)).toEqual(fontKey1);
        doc.destroy();
    });
	it('998488 - single page - embedded cjkFont with same styles', () => {
        let doc: PdfDocument = new PdfDocument();
        let page: PdfPage = doc.addPage();
        let pen: any;
        let embedded = doc.embedFont(PdfCjkFontFamily.heiseiMinchoW3, 18, PdfFontStyle.regular, true);
        page.graphics.drawString('こんにちは世界', embedded, {x: 10, y: 10, width: 400, height: 100}, pen);
        embedded = embedded.getFont(20, PdfFontStyle.regular);
        page.graphics.drawString('こんにちは世界', embedded, {x: 10, y: 30, width: 400, height: 100}, pen);
        embedded = embedded.getFont(22, PdfFontStyle.regular);
        page.graphics.drawString('こんにちは世界', embedded, {x: 10, y: 60, width: 400, height: 100}, pen);
        const output = doc.save() as Uint8Array;
        expect(output.length).toBeGreaterThan(0);
        doc = new PdfDocument(output);
        page = doc.getPage(0);
        let resources: _PdfDictionary = page._pageDictionary.get('Resources') as _PdfDictionary;
        let fontEntry: any = resources.get('Font');
        expect(fontEntry.size).toEqual(1);
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        expect(result.length).toEqual(26);
        expect(result[8]._operator).toEqual('Tf');
        expect(result[8]._operands[1]).toEqual('18.000');
        let fontKey1: string = result[8]._operands[0].slice(1);
        let fontDic: _PdfDictionary = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(fontDic.get('BaseFont').name).toEqual('HeiseiMin-W3');
        expect(result[17]._operator).toEqual('Tf');
        expect(result[17]._operands[1]).toEqual('20.000');
        expect(result[17]._operands[0].slice(1)).toEqual(fontKey1);
        expect(result[22]._operator).toEqual('Tf');
        expect(result[22]._operands[1]).toEqual('22.000');
        expect(result[22]._operands[0].slice(1)).toEqual(fontKey1);
        doc.destroy();
    });
	it('998488 - two page - embedded ttf Font with same styles', () => {
        let doc: PdfDocument = new PdfDocument();
        const embedded = doc.embedFont(ttfData, 12);
        const page1 = doc.addPage();
        let pen: any;
        page1.graphics.drawString('Alpha', embedded, {x: 10, y: 10, width: 200, height: 200}, pen);
        page1.graphics.drawString('Alpha', embedded, {x: 10, y: 50, width: 200, height: 200}, pen);
        page1.graphics.drawString('Alpha', embedded, {x: 10, y: 70, width: 200, height: 200}, pen);
        const embedded2 = embedded.getFont(24);
        const page2 = doc.addPage();
        page2.graphics.drawString('Omega', embedded2, {x: 50, y: 50, width: 100, height: 100}, pen);
        page2.graphics.drawString('Omega', embedded2, {x: 50, y: 70, width: 100, height: 100}, pen);
        page2.graphics.drawString('Omega', embedded2, {x: 50, y: 90, width: 100, height: 100}, pen);
        let update = doc.save();
		doc.destroy();	
        doc= new PdfDocument(update);
        let page = doc.getPage(1);
        let resources: _PdfDictionary = page._pageDictionary.get('Resources') as _PdfDictionary;
        let fontEntry: any = resources.get('Font');
        expect(fontEntry.size).toEqual(1);
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        expect(result.length).toEqual(29);
        expect(result[8]._operator).toEqual('Tf');
        expect(result[8]._operands[1]).toEqual('24.000');
        let fontKey1: string = result[8]._operands[0].slice(1);
        let fontDic: _PdfDictionary = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(result[18]._operator).toEqual('Tf');
        expect(result[18]._operands[1]).toEqual('24.000');
        expect(result[18]._operands[0].slice(1)).toEqual(fontKey1);
        expect(result[24]._operator).toEqual('Tf');
        expect(result[24]._operands[1]).toEqual('24.000');
        expect(result[24]._operands[0].slice(1)).toEqual(fontKey1);
        page = doc.getPage(0);
        resources = page._pageDictionary.get('Resources') as _PdfDictionary;
        fontEntry = resources.get('Font');
        expect(fontEntry.size).toEqual(1);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result.length).toEqual(29);
        expect(result[8]._operator).toEqual('Tf');
        expect(result[8]._operands[1]).toEqual('12.000');
        fontKey1 = result[8]._operands[0].slice(1);
        fontDic = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(result[18]._operator).toEqual('Tf');
        expect(result[18]._operands[1]).toEqual('12.000');
        expect(result[18]._operands[0].slice(1)).toEqual(fontKey1);
        expect(result[24]._operator).toEqual('Tf');
        expect(result[24]._operands[1]).toEqual('12.000');
        expect(result[24]._operands[0].slice(1)).toEqual(fontKey1);
        doc.destroy();
    });
	it('998488 - two page - normal standard Font with same styles', () => {
        let doc: PdfDocument = new PdfDocument();
        let page: PdfPage = doc.addPage();
        let pen: any;
        let embedded = new PdfStandardFont(PdfFontFamily.symbol, 11, PdfFontStyle.regular);
        page.graphics.drawString('String with font size 11', embedded, {x: 10, y: 10, width: 300, height: 200}, new PdfPen({r: 255, g: 0, b:255}, 1), new PdfBrush({r: 255, g: 0, b:255}));
        let embedded1 = embedded.getFont(13, PdfFontStyle.regular);
        page.graphics.drawString('String with font size 13', embedded1, {x: 10, y: 30, width: 300, height: 200}, new PdfPen({r: 255, g: 0, b:255}, 1), new PdfBrush({r: 255, g: 0, b:255}));
        let embedded2 = embedded.getFont(14, PdfFontStyle.regular);
        page.graphics.drawString('String with font size 14', embedded2, {x: 10, y: 60, width: 300, height: 200}, pen);
        let embedded3 = embedded.getFont(15, PdfFontStyle.regular);
        page.graphics.drawString('String with font size 15', embedded3, {x: 10, y: 90, width: 300, height: 200}, pen);
        page = doc.addPage();
        page.graphics.drawString('String with font size 11', embedded, {x: 10, y: 10, width: 300, height: 200}, new PdfPen({r: 255, g: 0, b:255}, 1), new PdfBrush({r: 255, g: 0, b:255}));
        page.graphics.drawString('String with font size 13', embedded1, {x: 10, y: 30, width: 300, height: 200}, new PdfPen({r: 255, g: 0, b:255}, 1), new PdfBrush({r: 255, g: 0, b:255}));
        page.graphics.drawString('String with font size 14', embedded2, {x: 10, y: 60, width: 300, height: 200}, pen);
        page.graphics.drawString('String with font size 15', embedded3, {x: 10, y: 90, width: 300, height: 200}, pen);
        const output = doc.save() as Uint8Array;
        expect(output.length).toBeGreaterThan(0);
		doc.destroy();
        doc = new PdfDocument(output);
        page = doc.getPage(0);
        let resources: _PdfDictionary = page._pageDictionary.get('Resources') as _PdfDictionary;
        let fontEntry: any = resources.get('Font');
        expect(fontEntry.size).toEqual(4);
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        expect(result.length).toEqual(46);
        expect(result[16]._operator).toEqual('Tf');
        expect(result[16]._operands[1]).toEqual('11.000');
        let fontKey1: string = result[16]._operands[0].slice(1);
        let fontDic: _PdfDictionary = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Symbol');
        expect(result[31]._operator).toEqual('Tf');
        expect(result[31]._operands[1]).toEqual('13.000');
        let fontKey2: string = result[31]._operands[0].slice(1);
        fontDic = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Symbol');
        expect(result[36]._operator).toEqual('Tf');
        expect(result[36]._operands[1]).toEqual('14.000');
        let fontKey3: string = result[36]._operands[0].slice(1);
        fontDic = fontEntry.get(fontKey3) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Symbol');
        expect(result[42]._operator).toEqual('Tf');
        expect(result[42]._operands[1]).toEqual('15.000');
        let fontKey4: string = result[42]._operands[0].slice(1);
        fontDic = fontEntry.get(fontKey4) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Symbol');
        page = doc.getPage(1);
        resources = page._pageDictionary.get('Resources') as _PdfDictionary;
        fontEntry = resources.get('Font');
        expect(fontEntry.size).toEqual(4);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result.length).toEqual(46);
        expect(result[16]._operator).toEqual('Tf');
        expect(result[16]._operands[1]).toEqual('11.000');
        expect(result[16]._operands[0].slice(1)).toEqual(fontKey1);
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Symbol');
        expect(result[31]._operator).toEqual('Tf');
        expect(result[31]._operands[1]).toEqual('13.000');
        expect(result[31]._operands[0].slice(1)).toEqual(fontKey2);
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Symbol');
        expect(result[36]._operator).toEqual('Tf');
        expect(result[36]._operands[1]).toEqual('14.000');
        expect(result[36]._operands[0].slice(1)).toEqual(fontKey3);
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Symbol');
        expect(result[42]._operator).toEqual('Tf');
        expect(result[42]._operands[1]).toEqual('15.000');
        expect(result[42]._operands[0].slice(1)).toEqual(fontKey4);
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Symbol');
        doc.destroy();
    });
	it('998488 - two page - normal cjk Font with same styles', () => {
        let doc: PdfDocument = new PdfDocument();
        let page: PdfPage = doc.addPage();
        let pen: any;
        let embedded = new PdfCjkStandardFont(PdfCjkFontFamily.heiseiMinchoW3, 18, PdfFontStyle.regular);
        page.graphics.drawString('こんにちは世界', embedded, {x: 10, y: 10, width: 400, height: 100}, pen);
        let embedded1 = embedded.getFont(20, PdfFontStyle.regular);
        page.graphics.drawString('こんにちは世界', embedded1, {x: 10, y: 30, width: 400, height: 100}, pen);
        let embedded2 = embedded.getFont(22, PdfFontStyle.regular);
        page.graphics.drawString('こんにちは世界', embedded2, {x: 10, y: 60, width: 400, height: 100}, pen);
        page = doc.addPage();
        page.graphics.drawString('こんにちは世界', embedded, {x: 10, y: 10, width: 400, height: 100}, pen);
        page.graphics.drawString('こんにちは世界', embedded1, {x: 10, y: 30, width: 400, height: 100}, pen);
        page.graphics.drawString('こんにちは世界', embedded2, {x: 10, y: 60, width: 400, height: 100}, pen);
        const output = doc.save() as Uint8Array;
        expect(output.length).toBeGreaterThan(0);
        doc = new PdfDocument(output);
        page = doc.getPage(0);
        let resources: _PdfDictionary = page._pageDictionary.get('Resources') as _PdfDictionary;
        let fontEntry: any = resources.get('Font');
        expect(fontEntry.size).toEqual(3);
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        expect(result.length).toEqual(26);
        expect(result[8]._operator).toEqual('Tf');
        expect(result[8]._operands[1]).toEqual('18.000');
        let fontKey1: string = result[8]._operands[0].slice(1);
        let fontDic: _PdfDictionary = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(result[17]._operator).toEqual('Tf');
        expect(result[17]._operands[1]).toEqual('20.000');
        let fontKey2: string = result[17]._operands[0].slice(1);
        fontDic = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(result[22]._operator).toEqual('Tf');
        expect(result[22]._operands[1]).toEqual('22.000');
        let fontKey3: string = result[22]._operands[0].slice(1);
        fontDic = fontEntry.get(fontKey3) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        page = doc.getPage(1);
        resources = page._pageDictionary.get('Resources') as _PdfDictionary;
        fontEntry = resources.get('Font');
        expect(fontEntry.size).toEqual(3);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result.length).toEqual(26);
        expect(result[8]._operator).toEqual('Tf');
        expect(result[8]._operands[1]).toEqual('18.000');
        expect(result[8]._operands[0].slice(1)).toEqual(fontKey1);
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(result[17]._operator).toEqual('Tf');
        expect(result[17]._operands[1]).toEqual('20.000');
        expect(result[17]._operands[0].slice(1)).toEqual(fontKey2);
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(result[22]._operator).toEqual('Tf');
        expect(result[22]._operands[1]).toEqual('22.000');
        expect(result[22]._operands[0].slice(1)).toEqual(fontKey3);
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        doc.destroy();
    });
	it('998488 - two page - normal ttf Font with same styles', () => {
        let doc: PdfDocument = new PdfDocument();
        const embedded = new PdfTrueTypeFont(ttfData, 12);
        const page1 = doc.addPage();
        let pen: any;
        page1.graphics.drawString('Alpha', embedded, {x: 10, y: 10, width: 200, height: 200}, pen);
        page1.graphics.drawString('Alpha', embedded, {x: 10, y: 50, width: 200, height: 200}, pen);
        page1.graphics.drawString('Alpha', embedded, {x: 10, y: 70, width: 200, height: 200}, pen);
        const embedded2 = embedded.getFont(24);
        const page2 = doc.addPage();
        page2.graphics.drawString('Omega', embedded2, {x: 50, y: 50, width: 100, height: 100}, pen);
        page2.graphics.drawString('Omega', embedded2, {x: 50, y: 70, width: 100, height: 100}, pen);
        page2.graphics.drawString('Omega', embedded2, {x: 50, y: 90, width: 100, height: 100}, pen);
        let update = doc.save();
		doc.destroy();	
        doc= new PdfDocument(update);
        let page = doc.getPage(1);
        let resources: _PdfDictionary = page._pageDictionary.get('Resources') as _PdfDictionary;
        let fontEntry: any = resources.get('Font');
        expect(fontEntry.size).toEqual(1);
        page = doc.getPage(1);
        resources = page._pageDictionary.get('Resources') as _PdfDictionary;
        fontEntry= resources.get('Font');
        expect(fontEntry.size).toEqual(1);
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        expect(result.length).toEqual(29);
        expect(result[8]._operator).toEqual('Tf');
        expect(result[8]._operands[1]).toEqual('24.000');
        let fontKey1: string = result[8]._operands[0].slice(1);
        let fontDic: _PdfDictionary = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(result[18]._operator).toEqual('Tf');
        expect(result[18]._operands[1]).toEqual('24.000');
        expect(result[18]._operands[0].slice(1)).toEqual(fontKey1);
        expect(result[24]._operator).toEqual('Tf');
        expect(result[24]._operands[1]).toEqual('24.000');
        expect(result[24]._operands[0].slice(1)).toEqual(fontKey1);
        page = doc.getPage(0);
        resources = page._pageDictionary.get('Resources') as _PdfDictionary;
        fontEntry = resources.get('Font');
        expect(fontEntry.size).toEqual(1);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result.length).toEqual(29);
        expect(result[8]._operator).toEqual('Tf');
        expect(result[8]._operands[1]).toEqual('12.000');
        fontKey1 = result[8]._operands[0].slice(1);
        fontDic = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(result[18]._operator).toEqual('Tf');
        expect(result[18]._operands[1]).toEqual('12.000');
        expect(result[18]._operands[0].slice(1)).toEqual(fontKey1);
        expect(result[24]._operator).toEqual('Tf');
        expect(result[24]._operands[1]).toEqual('12.000');
        expect(result[24]._operands[0].slice(1)).toEqual(fontKey1);
        doc.destroy();
    });
    it('998488 - two page - embedded standard Font with same styles', () => {
        let doc: PdfDocument = new PdfDocument();
        let page: PdfPage = doc.addPage();
        let pen: any;
        let embedded = doc.embedFont(PdfFontFamily.symbol, 11, PdfFontStyle.regular);
        page.graphics.drawString('String with font size 11', embedded, {x: 10, y: 10, width: 300, height: 200}, new PdfPen({r: 255, g: 0, b:255}, 1), new PdfBrush({r: 255, g: 0, b:255}));
        let embedded1 = embedded.getFont(13, PdfFontStyle.regular);
        page.graphics.drawString('String with font size 13', embedded1, {x: 10, y: 30, width: 300, height: 200}, new PdfPen({r: 255, g: 0, b:255}, 1), new PdfBrush({r: 255, g: 0, b:255}));
        let embedded2 = embedded.getFont(14, PdfFontStyle.regular);
        page.graphics.drawString('String with font size 14', embedded2, {x: 10, y: 60, width: 300, height: 200}, pen);
        let embedded3 = embedded.getFont(15, PdfFontStyle.regular);
        page.graphics.drawString('String with font size 15', embedded3, {x: 10, y: 90, width: 300, height: 200}, pen);
        page = doc.addPage();
        page.graphics.drawString('String with font size 11', embedded, {x: 10, y: 10, width: 300, height: 200}, new PdfPen({r: 255, g: 0, b:255}, 1), new PdfBrush({r: 255, g: 0, b:255}));
        page.graphics.drawString('String with font size 13', embedded1, {x: 10, y: 30, width: 300, height: 200}, new PdfPen({r: 255, g: 0, b:255}, 1), new PdfBrush({r: 255, g: 0, b:255}));
        page.graphics.drawString('String with font size 14', embedded2, {x: 10, y: 60, width: 300, height: 200}, pen);
        page.graphics.drawString('String with font size 15', embedded3, {x: 10, y: 90, width: 300, height: 200}, pen);
        const output = doc.save() as Uint8Array;
        expect(output.length).toBeGreaterThan(0);
		doc.destroy();
        doc = new PdfDocument(output);
        page = doc.getPage(0);
        let resources: _PdfDictionary = page._pageDictionary.get('Resources') as _PdfDictionary;
        let fontEntry: any = resources.get('Font');
        expect(fontEntry.size).toEqual(1);
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        expect(result.length).toEqual(46);
        expect(result[16]._operator).toEqual('Tf');
        expect(result[16]._operands[1]).toEqual('11.000');
        let fontKey1: string = result[16]._operands[0].slice(1);
        let fontDic: _PdfDictionary = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Symbol');
        expect(result[31]._operator).toEqual('Tf');
        expect(result[31]._operands[1]).toEqual('13.000');
        expect(result[31]._operands[0].slice(1)).toEqual(fontKey1);
        expect(result[36]._operator).toEqual('Tf');
        expect(result[36]._operands[1]).toEqual('14.000');
        expect(result[36]._operands[0].slice(1)).toEqual(fontKey1);
        expect(result[42]._operator).toEqual('Tf');
        expect(result[42]._operands[1]).toEqual('15.000');
        expect(result[42]._operands[0].slice(1)).toEqual(fontKey1);
        page = doc.getPage(1);
        resources = page._pageDictionary.get('Resources') as _PdfDictionary;
        fontEntry = resources.get('Font');
        expect(fontEntry.size).toEqual(1);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result.length).toEqual(46);
        expect(result[16]._operator).toEqual('Tf');
        expect(result[16]._operands[1]).toEqual('11.000');
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Symbol');
        expect(result[31]._operator).toEqual('Tf');
        expect(result[31]._operands[1]).toEqual('13.000');
        expect(result[31]._operands[0].slice(1)).toEqual(fontKey1);
        expect(result[36]._operator).toEqual('Tf');
        expect(result[36]._operands[1]).toEqual('14.000');
        expect(result[36]._operands[0].slice(1)).toEqual(fontKey1);
        expect(result[42]._operator).toEqual('Tf');
        expect(result[42]._operands[1]).toEqual('15.000');
        expect(result[42]._operands[0].slice(1)).toEqual(fontKey1);
        doc.destroy();
    });
    it('998488 - two page - embedded cjk Font with same styles', () => {
        let doc: PdfDocument = new PdfDocument();
        let page: PdfPage = doc.addPage();
        let pen: any;
        let embedded = doc.embedFont(PdfCjkFontFamily.heiseiMinchoW3, 18, PdfFontStyle.regular, true);
        page.graphics.drawString('こんにちは世界', embedded, {x: 10, y: 10, width: 400, height: 100}, pen);
        let embedded1 = embedded.getFont(20, PdfFontStyle.regular);
        page.graphics.drawString('こんにちは世界', embedded1, {x: 10, y: 30, width: 400, height: 100}, pen);
        let embedded2 = embedded.getFont(22, PdfFontStyle.regular);
        page.graphics.drawString('こんにちは世界', embedded2, {x: 10, y: 60, width: 400, height: 100}, pen);
        page = doc.addPage();
        page.graphics.drawString('こんにちは世界', embedded, {x: 10, y: 10, width: 400, height: 100}, pen);
        page.graphics.drawString('こんにちは世界', embedded1, {x: 10, y: 30, width: 400, height: 100}, pen);
        page.graphics.drawString('こんにちは世界', embedded2, {x: 10, y: 60, width: 400, height: 100}, pen);
        const output = doc.save() as Uint8Array;
        expect(output.length).toBeGreaterThan(0);
        doc = new PdfDocument(output);
        page = doc.getPage(0);
        let resources: _PdfDictionary = page._pageDictionary.get('Resources') as _PdfDictionary;
        let fontEntry: any = resources.get('Font');
        expect(fontEntry.size).toEqual(1);
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        expect(result.length).toEqual(26);
        expect(result[8]._operator).toEqual('Tf');
        expect(result[8]._operands[1]).toEqual('18.000');
        let fontKey1: string = result[8]._operands[0].slice(1);
        let fontDic: _PdfDictionary = fontEntry.get(fontKey1) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(result[17]._operator).toEqual('Tf');
        expect(result[17]._operands[1]).toEqual('20.000');
        expect(result[17]._operands[0].slice(1)).toEqual(fontKey1);
        expect(result[22]._operator).toEqual('Tf');
        expect(result[22]._operands[1]).toEqual('22.000');
        expect(result[22]._operands[0].slice(1)).toEqual(fontKey1);
        page = doc.getPage(1);
        resources = page._pageDictionary.get('Resources') as _PdfDictionary;
        fontEntry = resources.get('Font');
        expect(fontEntry.size).toEqual(1);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result.length).toEqual(26);
        expect(result[8]._operator).toEqual('Tf');
        expect(result[8]._operands[1]).toEqual('18.000');
        expect(result[8]._operands[0].slice(1)).toEqual(fontKey1);
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(result[17]._operator).toEqual('Tf');
        expect(result[17]._operands[1]).toEqual('20.000');
        expect(result[17]._operands[0].slice(1)).toEqual(fontKey1);
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(result[22]._operator).toEqual('Tf');
        expect(result[22]._operands[1]).toEqual('22.000');
        expect(result[22]._operands[0].slice(1)).toEqual(fontKey1);
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        doc.destroy();
    });
    it('998488 - standard font templates', () => {
        let doc: PdfDocument = new PdfDocument();
        let page: PdfPage = doc.addPage();
        let pen: any;
        let template: PdfTemplate = new PdfTemplate({ width: 595, height: 842 });
        let embedded = doc.embedFont(PdfFontFamily.symbol, 11, PdfFontStyle.regular);
        template.graphics.drawString('String with font size 11', embedded, {x: 10, y: 10, width: 300, height: 200}, new PdfPen({r: 255, g: 0, b:255}, 1), new PdfBrush({r: 255, g: 0, b:255}));
        let embedded1 = embedded.getFont(13, PdfFontStyle.regular);
        template.graphics.drawString('String with font size 13', embedded1, {x: 10, y: 30, width: 300, height: 200}, new PdfPen({r: 255, g: 0, b:255}, 1), new PdfBrush({r: 255, g: 0, b:255}));
        let embedded2 = embedded.getFont(14, PdfFontStyle.regular);
        template.graphics.drawString('String with font size 14', embedded2, {x: 10, y: 60, width: 300, height: 200}, pen);
        let embedded3 = embedded.getFont(15, PdfFontStyle.regular);
        template.graphics.drawString('String with font size 15', embedded3, {x: 10, y: 90, width: 300, height: 200}, pen);
        page.graphics.drawTemplate(template, {x: 0, y: 0, width: 595, height: 842});
        const output = doc.save() as Uint8Array;
        expect(output.length).toBeGreaterThan(0);
		doc.destroy();
        doc = new PdfDocument(output);
        page = doc.getPage(0);
        let resources: _PdfDictionary = page._pageDictionary.get('Resources') as _PdfDictionary;
        let xobjectEntry: any = resources.get('XObject');
        expect(xobjectEntry.size).toEqual(1);
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        expect(result.length).toEqual(11);
        expect(result[9]._operator).toEqual('Do');
        let fontKey1: string = result[9]._operands[0].slice(1);
        let fontDic = xobjectEntry.get(fontKey1);
        let dictionary = fontDic.stream.dictionary.get('Resources'). get('Font');
        parser = new _ContentParser(fontDic.getBytes());
        result = parser._readContent();
        expect(result.length).toEqual(40);
        expect(result[10]._operator).toEqual('Tf');
        expect(result[10]._operands[1]).toEqual('11.000');
        let fontKey2: string = result[10]._operands[0].slice(1);
        fontDic = dictionary.get(fontKey2);
        expect(fontDic.get('Subtype').name).toEqual('Type1');
        expect(fontDic.get('BaseFont').name).toEqual('Symbol');
        expect(result[25]._operator).toEqual('Tf');
        expect(result[25]._operands[1]).toEqual('13.000');
        expect(result[25]._operands[0].slice(1)).toEqual(fontKey2);
        expect(result[30]._operator).toEqual('Tf');
        expect(result[30]._operands[1]).toEqual('14.000');
        expect(result[30]._operands[0].slice(1)).toEqual(fontKey2);
        expect(result[36]._operator).toEqual('Tf');
        expect(result[36]._operands[1]).toEqual('15.000');
        expect(result[36]._operands[0].slice(1)).toEqual(fontKey2);
        doc.destroy();
    });
    it('998488 - cjk font templates', () => {
        let doc: PdfDocument = new PdfDocument();
        let page: PdfPage = doc.addPage();
        let pen: any;
        let template: PdfTemplate = new PdfTemplate({ width: 595, height: 842 });
        let embedded = doc.embedFont(PdfCjkFontFamily.heiseiMinchoW3, 18, PdfFontStyle.regular, true);
        template.graphics.drawString('こんにちは世界', embedded, {x: 10, y: 10, width: 400, height: 100}, pen);
        embedded = embedded.getFont(20, PdfFontStyle.regular);
        template.graphics.drawString('こんにちは世界', embedded, {x: 10, y: 30, width: 400, height: 100}, pen);
        embedded = embedded.getFont(22, PdfFontStyle.regular);
        template.graphics.drawString('こんにちは世界', embedded, {x: 10, y: 60, width: 400, height: 100}, pen);
        page.graphics.drawTemplate(template, {x: 0, y: 0, width: 595, height: 842});``
        const output = doc.save() as Uint8Array;
        expect(output.length).toBeGreaterThan(0);
        doc = new PdfDocument(output);
        page = doc.getPage(0);
        let resources: _PdfDictionary = page._pageDictionary.get('Resources') as _PdfDictionary;
        let xobjectEntry: any = resources.get('XObject');
        expect(xobjectEntry.size).toEqual(1);
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        expect(result.length).toEqual(11);
        expect(result[9]._operator).toEqual('Do');
        let fontKey1: string = result[9]._operands[0].slice(1);
        let fontDic = xobjectEntry.get(fontKey1);
        let dictionary = fontDic.stream.dictionary.get('Resources'). get('Font');
        parser = new _ContentParser(fontDic.getBytes());
        result = parser._readContent();
        expect(result.length).toEqual(20);
        expect(result[2]._operator).toEqual('Tf');
        expect(result[2]._operands[1]).toEqual('18.000');
        let fontKey2: string = result[2]._operands[0].slice(1);
        fontDic = dictionary.get(fontKey2) as _PdfDictionary;
        expect(fontDic.get('Subtype').name).toEqual('Type0');
        expect(fontDic.get('BaseFont').name).toEqual('HeiseiMin-W3');
        expect(result[11]._operator).toEqual('Tf');
        expect(result[11]._operands[1]).toEqual('20.000');
        expect(result[11]._operands[0].slice(1)).toEqual(fontKey2);
        expect(result[16]._operator).toEqual('Tf');
        expect(result[16]._operands[1]).toEqual('22.000');
        expect(result[16]._operands[0].slice(1)).toEqual(fontKey2);
        doc.destroy();
    });
});
