import { _PdfStream } from "./../src/pdf/core/base-stream";
import { _ContentParser, _PdfRecord } from "./../src/pdf/core/content-parser";
import { PdfLineJoin } from "./../src/pdf/core/enumerator";
import { PdfFont, PdfFontFamily, PdfFontStyle } from "./../src/pdf/core/fonts/pdf-standard-font";
import { PdfBitmap } from "./../src/pdf/core/graphics/images/pdf-bitmap";
import { PdfBrush, PdfGraphics, PdfPen } from "./../src/pdf/core/graphics/pdf-graphics";
import { PdfDocument } from "./../src/pdf/core/pdf-document";
import { PdfPage } from "./../src/pdf/core/pdf-page";
import { _PdfDictionary, _PdfName } from "./../src/pdf/core/pdf-primitives";
import { jpgBytes, pngBytes } from "./image-input.spec";
describe('Graphics', () => {
    it('Shapes', () => {
        function makeRegularPolygon(
            cx: number,
            cy: number,
            r: number,
            pointNum: number
        ): Array<{ x: number; y: number }> {
            const pts: Array<{ x: number; y: number }> = [];
            const f = (360.0 / pointNum) * Math.PI / 180.0;
            for (let i = 0; i < pointNum; i++) {
                const theta = i * f;
                pts.push({
                    x: Math.cos(theta) * r + cx,
                    y: Math.sin(theta) * r + cy
                });
            }
            return pts;
        }
        const doc = new PdfDocument();
        const page: PdfPage = doc.addPage();
        const g: PdfGraphics = page.graphics;
        // Fonts
        const headerFont = doc.embedFont(PdfFontFamily.helvetica, 14, PdfFontStyle.bold);
        let pen = new PdfPen({ r: 0, g: 0, b: 0 }, 3);
        const pointNum = 16;
        const radius = 100;
        const center = { x: 140, y: 140 };
        // Build points like your loop
        const polygonPoints = makeRegularPolygon(center.x, center.y, radius, pointNum);
        // Brush and pen colors (brown stroke, green fill)
        pen._color = { r: 165, g: 42, b: 42 };     // Brown
        pen._width = 10;
        pen._lineJoin = PdfLineJoin.round;
        const greenBrush = new PdfBrush({ r: 0, g: 128, b: 0 });
        g.drawString('Polygon', headerFont, { x: 50, y: 0, width: 100, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
        g.drawPolygon(polygonPoints, pen, greenBrush);
        let rect = { x: 20, y: 280, width: 200, height: 200 };
        g.drawString('Pie shape', headerFont, { x: 50, y: 250, width: 100, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
        pen._color = { r: 165, g: 42, b: 42 }; // Brown stroke
        pen._width = 10;
        pen._lineJoin = PdfLineJoin.round;
        const brownBrush = new PdfBrush({ r: 165, g: 42, b: 42 });
        const green = new PdfBrush({ r: 0, g: 128, b: 0 });
        g.drawPie(rect, 180, 60, pen, green);
        g.drawPie(rect, 360 - 60, 60, pen, green);
        g.drawPie(rect, 60, 60, pen, green);
        g.drawString('Arcs', headerFont, { x: 330, y: 0, width: 100, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
        rect = { x: 310, y: 40, width: 200, height: 200 };
        g.drawArc(rect, 0, 90, new PdfPen({ r: 165, g: 42, b: 42 }, 11));
        g.drawArc({ x: rect.x - 10, y: rect.y, width: rect.width, height: rect.height }, 90, 90, new PdfPen({ r: 0, g: 100, b: 0 }, 11));
        g.drawArc({ x: rect.x - 10, y: rect.y - 10, width: rect.width, height: rect.height }, 180, 90, new PdfPen({ r: 165, g: 42, b: 42 }, 11));
        g.drawArc({ x: rect.x, y: rect.y - 10, width: rect.width, height: rect.height }, 270, 90, new PdfPen({ r: 0, g: 100, b: 0 }, 11));
        rect = { x: 310, y: 280, width: 200, height: 100 };
        g.drawString('Simple Rectangle', headerFont, { x: 310, y: 255, width: 150, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
        g.drawRectangle(rect, new PdfPen({ r: 165, g: 42, b: 42 }, 11), new PdfBrush({ r: 0, g: 128, b: 0 }));
        g.drawString('Shape with pagination', headerFont, { x: 300, y: 390, width: 200, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
        // Large ellipse on first page
        g.drawEllipse({ x: 300, y: 450, width: 160, height: 1100 }, brownBrush);
        g.drawEllipse({ x: 320, y: 480, width: 160, height: 1100 }, green);
        let page2 = doc.addPage();
        let g2 = page2.graphics;
        g2.drawEllipse({ x: 300, y: -480, width: 160, height: 1100 }, brownBrush);
        g2.drawEllipse({ x: 320, y: -450, width: 160, height: 1100 }, green);
        g2.drawString('Transparent Rectangles', headerFont, { x: 50, y: 80, width: 200, height: 100 }, new PdfBrush({ r: 0, g: 0, b: 139 }));
        let r = { x: 10, y: 150, width: 100, height: 100 };
        let p = new PdfPen({ r: 0, g: 0, b: 0 }, 1);
        let b: PdfBrush = new PdfBrush({ r: 0, g: 100, b: 0 }); // DarkGreen
        g2.drawRectangle(r, p, b);
        r = { x: r.x + 20, y: r.y + 20, width: r.width, height: r.height };
        p = new PdfPen({ r: 165, g: 42, b: 42 }, 1); // Brown
        b = new PdfBrush({ r: 165, g: 42, b: 42 });
        g2.setTransparency(0.7);
        g2.drawRectangle(r, p, b);
        r = { x: r.x + 20, y: r.y + 20, width: r.width, height: r.height };
        g2.setTransparency(0.5);
        g2.drawRectangle(r, p, new PdfBrush({ r: 0, g: 100, b: 0 }));
        r = { x: r.x + 20, y: r.y + 20, width: r.width, height: r.height };
        p = new PdfPen({ r: 0, g: 0, b: 255 }, 1); // Blue
        b = new PdfBrush({ r: 128, g: 128, b: 128 }); // Gray
        g2.setTransparency(0.25);
        g2.drawRectangle(r, p, b);
        r = { x: r.x + 20, y: r.y + 20, width: r.width, height: r.height };
        p = new PdfPen({ r: 0, g: 0, b: 0 }, 1); // Black
        b = new PdfBrush({ r: 0, g: 128, b: 0 }); // Green
        g2.setTransparency(0.1);
        g2.drawRectangle(r, p, b);
        // Save and download
        const bytes = doc.save();
        doc.destroy();
        const parsed: PdfDocument = new PdfDocument(bytes);
        const parsedPageOne: PdfPage = parsed.getPage(0);
        let contents = parsedPageOne._pageDictionary.get('Contents');
        let ref = contents[2];
        let stream = parsedPageOne._crossReference._fetch(ref);
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        //Font level check
        let resources: _PdfDictionary = parsedPageOne._pageDictionary.get('Resources');
        const fontDictionary: _PdfDictionary = resources.get('Font');
        const HelveticaBoldRef: string = result[11]._operands[0];
        const HelveticaBold: _PdfName = fontDictionary.get(HelveticaBoldRef.slice(1)).get('BaseFont');
        expect(HelveticaBold.name).toEqual('Helvetica-Bold');
        // Checking the page one shapes with font in overall content level
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands.length).toBe(0);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['40.000', '-40.000', '515.000', '-762.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands.length).toBe(0);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands.length).toBe(0);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands.length).toBe(0);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '40.00', '-40.00']);
        expect(result[7]._operator).toEqual('BT');
        expect(result[7]._operands.length).toBe(0);
        expect(result[8]._operator).toEqual('CS');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('cs');
        expect(result[9]._operands).toEqual(['/DeviceRGB']);
        expect(result[10]._operator).toEqual('rg');
        expect(result[10]._operands).toEqual(['0.000', '0.000', '0.545']);
        expect(result[11]._operator).toEqual('Tf');
        expect(result[11]._operands[0]).toEqual(HelveticaBoldRef);
        expect(result[11]._operands[1]).toEqual('14.000');
        expect(result[12]._operator).toEqual('Tr');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('Tc');
        expect(result[13]._operands).toEqual(['0.000']);
        expect(result[14]._operator).toEqual('Tw');
        expect(result[14]._operands).toEqual(['0.000']);
        expect(result[15]._operator).toEqual('Tz');
        expect(result[15]._operands).toEqual(['100.000']);
        expect(result[16]._operator).toEqual('Tm');
        expect(result[16]._operands).toEqual(['1.00', '.00', '.00', '1.00', '50.00', '-13.47']);
        expect(result[17]._operator).toEqual("'");
        expect(result[17]._operands).toEqual(['(Polygon)']);
        expect(result[18]._operator).toEqual('ET');
        expect(result[18]._operands.length).toBe(0);
        expect(result[19]._operator).toEqual('d');
        expect(result[19]._operands).toEqual(['[]', '0']);
        expect(result[20]._operator).toEqual('w');
        expect(result[20]._operands).toEqual(['10.000']);
        expect(result[21]._operator).toEqual('j');
        expect(result[21]._operands).toEqual(['1']);
        expect(result[22]._operator).toEqual('J');
        expect(result[22]._operands).toEqual(['0']);
        expect(result[23]._operator).toEqual('RG');
        expect(result[23]._operands).toEqual(['0.647', '0.165', '0.165']);
        expect(result[24]._operator).toEqual('rg');
        expect(result[24]._operands).toEqual(['0.000', '0.502', '0.000']);
        expect(result[25]._operator).toEqual('m');
        expect(result[25]._operands).toEqual(['240.000', '-140.000']);
        expect(result[26]._operator).toEqual('l');
        expect(result[26]._operands).toEqual(['232.388', '-178.268']);
        expect(result[27]._operator).toEqual('l');
        expect(result[27]._operands).toEqual(['210.711', '-210.711']);
        expect(result[28]._operator).toEqual('l');
        expect(result[28]._operands).toEqual(['178.268', '-232.388']);
        expect(result[29]._operator).toEqual('l');
        expect(result[29]._operands).toEqual(['140.000', '-240.000']);
        expect(result[30]._operator).toEqual('l');
        expect(result[30]._operands).toEqual(['101.732', '-232.388']);
        expect(result[31]._operator).toEqual('l');
        expect(result[31]._operands).toEqual(['69.289', '-210.711']);
        expect(result[32]._operator).toEqual('l');
        expect(result[32]._operands).toEqual(['47.612', '-178.268']);
        expect(result[33]._operator).toEqual('l');
        expect(result[33]._operands).toEqual(['40.000', '-140.000']);
        expect(result[34]._operator).toEqual('l');
        expect(result[34]._operands).toEqual(['47.612', '-101.732']);
        expect(result[35]._operator).toEqual('l');
        expect(result[35]._operands).toEqual(['69.289', '-69.289']);
        expect(result[36]._operator).toEqual('l');
        expect(result[36]._operands).toEqual(['101.732', '-47.612']);
        expect(result[37]._operator).toEqual('l');
        expect(result[37]._operands).toEqual(['140.000', '-40.000']);
        expect(result[38]._operator).toEqual('l');
        expect(result[38]._operands).toEqual(['178.268', '-47.612']);
        expect(result[39]._operator).toEqual('l');
        expect(result[39]._operands).toEqual(['210.711', '-69.289']);
        expect(result[40]._operator).toEqual('l');
        expect(result[40]._operands).toEqual(['232.388', '-101.732']);
        expect(result[41]._operator).toEqual('b');
        expect(result[41]._operands.length).toBe(0);
        expect(result[42]._operator).toEqual('BT');
        expect(result[42]._operands.length).toBe(0);
        expect(result[43]._operator).toEqual('rg');
        expect(result[43]._operands).toEqual(['0.000', '0.000', '0.545']);
        expect(result[44]._operator).toEqual('Tf');
        expect(result[44]._operands[0]).toEqual(HelveticaBoldRef);
        expect(result[44]._operands[1]).toEqual('14.000');
        expect(result[45]._operator).toEqual('Tm');
        expect(result[45]._operands).toEqual(['1.00', '.00', '.00', '1.00', '50.00', '-263.47']);
        expect(result[46]._operator).toEqual("'");
        expect(result[46]._operands).toEqual(['(Pie shape)']);
        expect(result[47]._operator).toEqual('ET');
        expect(result[47]._operands.length).toBe(0);
        expect(result[48]._operator).toEqual('d');
        expect(result[48]._operands).toEqual(['[]', '0']);
        expect(result[49]._operator).toEqual('w');
        expect(result[49]._operands).toEqual(['10.000']);
        expect(result[50]._operator).toEqual('j');
        expect(result[50]._operands).toEqual(['1']);
        expect(result[51]._operator).toEqual('J');
        expect(result[51]._operands).toEqual(['0']);
        expect(result[52]._operator).toEqual('RG');
        expect(result[52]._operands).toEqual(['0.647', '0.165', '0.165']);
        expect(result[53]._operator).toEqual('rg');
        expect(result[53]._operands).toEqual(['0.000', '0.502', '0.000']);
        expect(result[54]._operator).toEqual('m');
        expect(result[54]._operands).toEqual(['20.000', '-380.000']);
        expect(result[55]._operator).toEqual('c');
        expect(result[55]._operands).toEqual(['20.000', '-344.273', '39.060', '-311.261', '70.000', '-293.397']);
        expect(result[56]._operator).toEqual('l');
        expect(result[56]._operands).toEqual(['120.000', '-380.000']);
        expect(result[57]._operator).toEqual('b');
        expect(result[57]._operands.length).toBe(0);
        expect(result[58]._operator).toEqual('d');
        expect(result[58]._operands).toEqual(['[]', '0']);
        expect(result[59]._operator).toEqual('w');
        expect(result[59]._operands).toEqual(['10.000']);
        expect(result[60]._operator).toEqual('j');
        expect(result[60]._operands).toEqual(['1']);
        expect(result[61]._operator).toEqual('J');
        expect(result[61]._operands).toEqual(['0']);
        expect(result[62]._operator).toEqual('RG');
        expect(result[62]._operands).toEqual(['0.647', '0.165', '0.165']);
        expect(result[63]._operator).toEqual('rg');
        expect(result[63]._operands).toEqual(['0.000', '0.502', '0.000']);
        expect(result[64]._operator).toEqual('m');
        expect(result[64]._operands).toEqual(['170.000', '-293.397']);
        expect(result[65]._operator).toEqual('c');
        expect(result[65]._operands).toEqual(['200.940', '-311.261', '220.000', '-344.273', '220.000', '-380.000']);
        expect(result[66]._operator).toEqual('l');
        expect(result[66]._operands).toEqual(['120.000', '-380.000']);
        expect(result[67]._operator).toEqual('b');
        expect(result[67]._operands.length).toBe(0);
        expect(result[68]._operator).toEqual('d');
        expect(result[68]._operands).toEqual(['[]', '0']);
        expect(result[69]._operator).toEqual('w');
        expect(result[69]._operands).toEqual(['10.000']);
        expect(result[70]._operator).toEqual('j');
        expect(result[70]._operands).toEqual(['1']);
        expect(result[71]._operator).toEqual('J');
        expect(result[71]._operands).toEqual(['0']);
        expect(result[72]._operator).toEqual('RG');
        expect(result[72]._operands).toEqual(['0.647', '0.165', '0.165']);
        expect(result[73]._operator).toEqual('rg');
        expect(result[73]._operands).toEqual(['0.000', '0.502', '0.000']);
        expect(result[74]._operator).toEqual('m');
        expect(result[74]._operands).toEqual(['170.000', '-466.603']);
        expect(result[75]._operator).toEqual('c');
        expect(result[75]._operands).toEqual(['139.060', '-484.466', '100.940', '-484.466', '70.000', '-466.603']);
        expect(result[76]._operator).toEqual('l');
        expect(result[76]._operands).toEqual(['120.000', '-380.000']);
        expect(result[77]._operator).toEqual('b');
        expect(result[77]._operands.length).toBe(0);
        expect(result[78]._operator).toEqual('BT');
        expect(result[78]._operands.length).toBe(0);
        expect(result[79]._operator).toEqual('rg');
        expect(result[79]._operands).toEqual(['0.000', '0.000', '0.545']);
        expect(result[80]._operator).toEqual('Tf');
        expect(result[80]._operands[0]).toEqual(HelveticaBoldRef);
        expect(result[80]._operands[1]).toEqual('14.000');
        expect(result[81]._operator).toEqual('Tm');
        expect(result[81]._operands).toEqual(['1.00', '.00', '.00', '1.00', '330.00', '-13.47']);
        expect(result[82]._operator).toEqual("'");
        expect(result[82]._operands).toEqual(['(Arcs)']);
        expect(result[83]._operator).toEqual('ET');
        expect(result[83]._operands.length).toBe(0);
        expect(result[84]._operator).toEqual('d');
        expect(result[84]._operands).toEqual(['[]', '0']);
        expect(result[85]._operator).toEqual('w');
        expect(result[85]._operands).toEqual(['11.000']);
        expect(result[86]._operator).toEqual('j');
        expect(result[86]._operands).toEqual(['0']);
        expect(result[87]._operator).toEqual('J');
        expect(result[87]._operands).toEqual(['0']);
        expect(result[88]._operator).toEqual('RG');
        expect(result[88]._operands).toEqual(['0.647', '0.165', '0.165']);
        expect(result[89]._operator).toEqual('m');
        expect(result[89]._operands).toEqual(['510.000', '-140.000']);
        expect(result[90]._operator).toEqual('c');
        expect(result[90]._operands).toEqual(['510.000', '-195.228', '465.228', '-240.000', '410.000', '-240.000']);
        expect(result[91]._operator).toEqual('S');
        expect(result[91]._operands.length).toBe(0);
        expect(result[92]._operator).toEqual('d');
        expect(result[92]._operands).toEqual(['[]', '0']);
        expect(result[93]._operator).toEqual('w');
        expect(result[93]._operands).toEqual(['11.000']);
        expect(result[94]._operator).toEqual('j');
        expect(result[94]._operands).toEqual(['0']);
        expect(result[95]._operator).toEqual('J');
        expect(result[95]._operands).toEqual(['0']);
        expect(result[96]._operator).toEqual('RG');
        expect(result[96]._operands).toEqual(['0.000', '0.392', '0.000']);
        expect(result[97]._operator).toEqual('m');
        expect(result[97]._operands).toEqual(['400.000', '-240.000']);
        expect(result[98]._operator).toEqual('c');
        expect(result[98]._operands).toEqual(['344.772', '-240.000', '300.000', '-195.228', '300.000', '-140.000']);
        expect(result[99]._operator).toEqual('S');
        expect(result[99]._operands.length).toBe(0);
        expect(result[100]._operator).toEqual('d');
        expect(result[100]._operands).toEqual(['[]', '0']);
        expect(result[101]._operator).toEqual('w');
        expect(result[101]._operands).toEqual(['11.000']);
        expect(result[102]._operator).toEqual('j');
        expect(result[102]._operands).toEqual(['0']);
        expect(result[103]._operator).toEqual('J');
        expect(result[103]._operands).toEqual(['0']);
        expect(result[104]._operator).toEqual('RG');
        expect(result[104]._operands).toEqual(['0.647', '0.165', '0.165']);
        expect(result[105]._operator).toEqual('m');
        expect(result[105]._operands).toEqual(['300.000', '-130.000']);
        expect(result[106]._operator).toEqual('c');
        expect(result[106]._operands).toEqual(['300.000', '-74.772', '344.772', '-30.000', '400.000', '-30.000']);
        expect(result[107]._operator).toEqual('S');
        expect(result[107]._operands.length).toBe(0);
        expect(result[108]._operator).toEqual('d');
        expect(result[108]._operands).toEqual(['[]', '0']);
        expect(result[109]._operator).toEqual('w');
        expect(result[109]._operands).toEqual(['11.000']);
        expect(result[110]._operator).toEqual('j');
        expect(result[110]._operands).toEqual(['0']);
        expect(result[111]._operator).toEqual('J');
        expect(result[111]._operands).toEqual(['0']);
        expect(result[112]._operator).toEqual('RG');
        expect(result[112]._operands).toEqual(['0.000', '0.392', '0.000']);
        expect(result[113]._operator).toEqual('m');
        expect(result[113]._operands).toEqual(['410.000', '-30.000']);
        expect(result[114]._operator).toEqual('c');
        expect(result[114]._operands).toEqual(['465.228', '-30.000', '510.000', '-74.772', '510.000', '-130.000']);
        expect(result[115]._operator).toEqual('S');
        expect(result[115]._operands.length).toBe(0);
        expect(result[116]._operator).toEqual('BT');
        expect(result[116]._operands.length).toBe(0);
        expect(result[117]._operator).toEqual('rg');
        expect(result[117]._operands).toEqual(['0.000', '0.000', '0.545']);
        expect(result[118]._operator).toEqual('Tf');
        expect(result[118]._operands[0]).toEqual(HelveticaBoldRef);
        expect(result[118]._operands[1]).toEqual('14.000');
        expect(result[119]._operator).toEqual('Tm');
        expect(result[119]._operands).toEqual(['1.00', '.00', '.00', '1.00', '310.00', '-268.47']);
        expect(result[120]._operator).toEqual("'");
        expect(result[120]._operands).toEqual(['(Simple Rectangle)']);
        expect(result[121]._operator).toEqual('ET');
        expect(result[121]._operands.length).toBe(0);
        expect(result[122]._operator).toEqual('d');
        expect(result[122]._operands).toEqual(['[]', '0']);
        expect(result[123]._operator).toEqual('w');
        expect(result[123]._operands).toEqual(['11.000']);
        expect(result[124]._operator).toEqual('j');
        expect(result[124]._operands).toEqual(['0']);
        expect(result[125]._operator).toEqual('J');
        expect(result[125]._operands).toEqual(['0']);
        expect(result[126]._operator).toEqual('RG');
        expect(result[126]._operands).toEqual(['0.647', '0.165', '0.165']);
        expect(result[127]._operator).toEqual('rg');
        expect(result[127]._operands).toEqual(['0.000', '0.502', '0.000']);
        expect(result[128]._operator).toEqual('re');
        expect(result[128]._operands).toEqual(['310.000', '-280.000', '200.000', '-100.000']);
        expect(result[129]._operator).toEqual('B');
        expect(result[129]._operands.length).toBe(0);
        expect(result[130]._operator).toEqual('BT');
        expect(result[130]._operands.length).toBe(0);
        expect(result[131]._operator).toEqual('rg');
        expect(result[131]._operands).toEqual(['0.000', '0.000', '0.545']);
        expect(result[132]._operator).toEqual('Tf');
        expect(result[132]._operands[0]).toEqual(HelveticaBoldRef);
        expect(result[132]._operands[1]).toEqual('14.000');
        expect(result[133]._operator).toEqual('Tm');
        expect(result[133]._operands).toEqual(['1.00', '.00', '.00', '1.00', '300.00', '-403.47']);
        expect(result[134]._operator).toEqual("'");
        expect(result[134]._operands).toEqual(['(Shape with pagination)']);
        expect(result[135]._operator).toEqual('ET');
        expect(result[135]._operands.length).toBe(0);
        expect(result[136]._operator).toEqual('rg');
        expect(result[136]._operands).toEqual(['0.647', '0.165', '0.165']);
        expect(result[137]._operator).toEqual('m');
        expect(result[137]._operands).toEqual(['460.000', '-1000.000']);
        expect(result[138]._operator).toEqual('c');
        expect(result[138]._operands).toEqual(['460.000', '-1303.757', '424.183', '-1550.000', '380.000', '-1550.000']);
        expect(result[139]._operator).toEqual('c');
        expect(result[139]._operands).toEqual(['335.817', '-1550.000', '300.000', '-1303.757', '300.000', '-1000.000']);
        expect(result[140]._operator).toEqual('c');
        expect(result[140]._operands).toEqual(['300.000', '-696.243', '335.817', '-450.000', '380.000', '-450.000']);
        expect(result[141]._operator).toEqual('c');
        expect(result[141]._operands).toEqual(['424.183', '-450.000', '460.000', '-696.243', '460.000', '-1000.000']);
        expect(result[142]._operator).toEqual('h');
        expect(result[142]._operands.length).toBe(0);
        expect(result[143]._operator).toEqual('f');
        expect(result[143]._operands.length).toBe(0);
        expect(result[144]._operator).toEqual('rg');
        expect(result[144]._operands).toEqual(['0.000', '0.502', '0.000']);
        expect(result[145]._operator).toEqual('m');
        expect(result[145]._operands).toEqual(['480.000', '-1030.000']);
        expect(result[146]._operator).toEqual('c');
        expect(result[146]._operands).toEqual(['480.000', '-1333.757', '444.183', '-1580.000', '400.000', '-1580.000']);
        expect(result[147]._operator).toEqual('c');
        expect(result[147]._operands).toEqual(['355.817', '-1580.000', '320.000', '-1333.757', '320.000', '-1030.000']);
        expect(result[148]._operator).toEqual('c');
        expect(result[148]._operands).toEqual(['320.000', '-726.243', '355.817', '-480.000', '400.000', '-480.000']);
        expect(result[149]._operator).toEqual('c');
        expect(result[149]._operands).toEqual(['444.183', '-480.000', '480.000', '-726.243', '480.000', '-1030.000']);
        expect(result[150]._operator).toEqual('h');
        expect(result[150]._operands.length).toBe(0);
        expect(result[151]._operator).toEqual('f');
        expect(result[151]._operands.length).toBe(0);
        //Page 2
        const parsedPageTwo: PdfPage = parsed.getPage(1);
        resources = parsedPageTwo._pageDictionary.get('Resources');
        contents = parsedPageTwo._pageDictionary.get('Contents');
        ref = contents[2];
        stream = parsedPageTwo._crossReference._fetch(ref);
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        //Transperancy level check from 0.7 => 0.5 => 0.25 => 0.1
        let transparencyRef = result[43]._operands[0];
        let level: _PdfDictionary = resources.get('ExtGState').get(transparencyRef.slice(1));
        expect(level.get('CA')).toEqual(0.7);
        //For 0.5
        transparencyRef = result[52]._operands[0];
        level = resources.get('ExtGState').get(transparencyRef.slice(1));
        expect(level.get('CA')).toEqual(0.5);
        // For 0.25
        transparencyRef = result[61]._operands[0];
        level = resources.get('ExtGState').get(transparencyRef.slice(1));
        expect(level.get('CA')).toEqual(0.25);
        //For 0.1
        transparencyRef = result[70]._operands[0];
        level = resources.get('ExtGState').get(transparencyRef.slice(1));
        expect(level.get('CA')).toEqual(0.1);
        //Checking the page two shapes in overall content level
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands.length).toBe(0);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['40.000', '-40.000', '515.000', '-762.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands.length).toBe(0);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands.length).toBe(0);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands.length).toBe(0);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '40.00', '-40.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('rg');
        expect(result[9]._operands).toEqual(['0.647', '0.165', '0.165']);
        expect(result[10]._operator).toEqual('m');
        expect(result[10]._operands).toEqual(['460.000', '-70.000']);
        expect(result[11]._operator).toEqual('c');
        expect(result[11]._operands).toEqual(['460.000', '-373.757', '424.183', '-620.000', '380.000', '-620.000']);
        expect(result[12]._operator).toEqual('c');
        expect(result[12]._operands).toEqual(['335.817', '-620.000', '300.000', '-373.757', '300.000', '-70.000']);
        expect(result[13]._operator).toEqual('c');
        expect(result[13]._operands).toEqual(['300.000', '233.757', '335.817', '480.000', '380.000', '480.000']);
        expect(result[14]._operator).toEqual('c');
        expect(result[14]._operands).toEqual(['424.183', '480.000', '460.000', '233.757', '460.000', '-70.000']);
        expect(result[15]._operator).toEqual('h');
        expect(result[15]._operands.length).toBe(0);
        expect(result[16]._operator).toEqual('f');
        expect(result[16]._operands.length).toBe(0);
        expect(result[17]._operator).toEqual('rg');
        expect(result[17]._operands).toEqual(['0.000', '0.502', '0.000']);
        expect(result[18]._operator).toEqual('m');
        expect(result[18]._operands).toEqual(['480.000', '-100.000']);
        expect(result[19]._operator).toEqual('c');
        expect(result[19]._operands).toEqual(['480.000', '-403.757', '444.183', '-650.000', '400.000', '-650.000']);
        expect(result[20]._operator).toEqual('c');
        expect(result[20]._operands).toEqual(['355.817', '-650.000', '320.000', '-403.757', '320.000', '-100.000']);
        expect(result[21]._operator).toEqual('c');
        expect(result[21]._operands).toEqual(['320.000', '203.757', '355.817', '450.000', '400.000', '450.000']);
        expect(result[22]._operator).toEqual('c');
        expect(result[22]._operands).toEqual(['444.183', '450.000', '480.000', '203.757', '480.000', '-100.000']);
        expect(result[23]._operator).toEqual('h');
        expect(result[23]._operands.length).toBe(0);
        expect(result[24]._operator).toEqual('f');
        expect(result[24]._operands.length).toBe(0);
        expect(result[25]._operator).toEqual('BT');
        expect(result[25]._operands.length).toBe(0);
        expect(result[26]._operator).toEqual('rg');
        expect(result[26]._operands).toEqual(['0.000', '0.000', '0.545']);
        expect(result[27]._operator).toEqual('Tf');
        expect(result[27]._operands[0]).toEqual(HelveticaBoldRef);
        expect(result[27]._operands[1]).toEqual('14.000');
        expect(result[28]._operator).toEqual('Tr');
        expect(result[28]._operands).toEqual(['0']);
        expect(result[29]._operator).toEqual('Tc');
        expect(result[29]._operands).toEqual(['0.000']);
        expect(result[30]._operator).toEqual('Tw');
        expect(result[30]._operands).toEqual(['0.000']);
        expect(result[31]._operator).toEqual('Tz');
        expect(result[31]._operands).toEqual(['100.000']);
        expect(result[32]._operator).toEqual('Tm');
        expect(result[32]._operands).toEqual(['1.00', '.00', '.00', '1.00', '50.00', '-93.47']);
        expect(result[33]._operator).toEqual("'");
        expect(result[33]._operands).toEqual(['(Transparent Rectangles)']);
        expect(result[34]._operator).toEqual('ET');
        expect(result[34]._operands.length).toBe(0);
        expect(result[35]._operator).toEqual('d');
        expect(result[35]._operands).toEqual(['[]', '0']);
        expect(result[36]._operator).toEqual('w');
        expect(result[36]._operands).toEqual(['1.000']);
        expect(result[37]._operator).toEqual('j');
        expect(result[37]._operands).toEqual(['0']);
        expect(result[38]._operator).toEqual('J');
        expect(result[38]._operands).toEqual(['0']);
        expect(result[39]._operator).toEqual('RG');
        expect(result[39]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[40]._operator).toEqual('rg');
        expect(result[40]._operands).toEqual(['0.000', '0.392', '0.000']);
        expect(result[41]._operator).toEqual('re');
        expect(result[41]._operands).toEqual(['10.000', '-150.000', '100.000', '-100.000']);
        expect(result[42]._operator).toEqual('B');
        expect(result[42]._operands.length).toBe(0);
        expect(result[43]._operator).toEqual('gs');
        expect(result[44]._operator).toEqual('d');
        expect(result[44]._operands).toEqual(['[]', '0']);
        expect(result[45]._operator).toEqual('w');
        expect(result[45]._operands).toEqual(['1.000']);
        expect(result[46]._operator).toEqual('j');
        expect(result[46]._operands).toEqual(['0']);
        expect(result[47]._operator).toEqual('J');
        expect(result[47]._operands).toEqual(['0']);
        expect(result[48]._operator).toEqual('RG');
        expect(result[48]._operands).toEqual(['0.647', '0.165', '0.165']);
        expect(result[49]._operator).toEqual('rg');
        expect(result[49]._operands).toEqual(['0.647', '0.165', '0.165']);
        expect(result[50]._operator).toEqual('re');
        expect(result[50]._operands).toEqual(['30.000', '-170.000', '100.000', '-100.000']);
        expect(result[51]._operator).toEqual('B');
        expect(result[51]._operands.length).toBe(0);
        expect(result[52]._operator).toEqual('gs');
        expect(result[53]._operator).toEqual('d');
        expect(result[53]._operands).toEqual(['[]', '0']);
        expect(result[54]._operator).toEqual('w');
        expect(result[54]._operands).toEqual(['1.000']);
        expect(result[55]._operator).toEqual('j');
        expect(result[55]._operands).toEqual(['0']);
        expect(result[56]._operator).toEqual('J');
        expect(result[56]._operands).toEqual(['0']);
        expect(result[57]._operator).toEqual('RG');
        expect(result[57]._operands).toEqual(['0.647', '0.165', '0.165']);
        expect(result[58]._operator).toEqual('rg');
        expect(result[58]._operands).toEqual(['0.000', '0.392', '0.000']);
        expect(result[59]._operator).toEqual('re');
        expect(result[59]._operands).toEqual(['50.000', '-190.000', '100.000', '-100.000']);
        expect(result[60]._operator).toEqual('B');
        expect(result[60]._operands.length).toBe(0);
        expect(result[61]._operator).toEqual('gs');
        expect(result[62]._operator).toEqual('d');
        expect(result[62]._operands).toEqual(['[]', '0']);
        expect(result[63]._operator).toEqual('w');
        expect(result[63]._operands).toEqual(['1.000']);
        expect(result[64]._operator).toEqual('j');
        expect(result[64]._operands).toEqual(['0']);
        expect(result[65]._operator).toEqual('J');
        expect(result[65]._operands).toEqual(['0']);
        expect(result[66]._operator).toEqual('RG');
        expect(result[66]._operands).toEqual(['0.000', '0.000', '1.000']);
        expect(result[67]._operator).toEqual('rg');
        expect(result[67]._operands).toEqual(['0.502', '0.502', '0.502']);
        expect(result[68]._operator).toEqual('re');
        expect(result[68]._operands).toEqual(['70.000', '-210.000', '100.000', '-100.000']);
        expect(result[69]._operator).toEqual('B');
        expect(result[69]._operands.length).toBe(0);
        expect(result[70]._operator).toEqual('gs');
        expect(result[71]._operator).toEqual('d');
        expect(result[71]._operands).toEqual(['[]', '0']);
        expect(result[72]._operator).toEqual('w');
        expect(result[72]._operands).toEqual(['1.000']);
        expect(result[73]._operator).toEqual('j');
        expect(result[73]._operands).toEqual(['0']);
        expect(result[74]._operator).toEqual('J');
        expect(result[74]._operands).toEqual(['0']);
        expect(result[75]._operator).toEqual('RG');
        expect(result[75]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[76]._operator).toEqual('rg');
        expect(result[76]._operands).toEqual(['0.000', '0.502', '0.000']);
        expect(result[77]._operator).toEqual('re');
        expect(result[77]._operands).toEqual(['90.000', '-230.000', '100.000', '-100.000']);
        expect(result[78]._operator).toEqual('B');
        expect(result[78]._operands.length).toBe(0);
        parsed.destroy();
    });
    it('image insertion', () => {
        const document: PdfDocument = new PdfDocument();
        // Add a new page and get its PdfGraphics context
        const page: PdfPage = document.addPage();
        const g: PdfGraphics = page.graphics;
        // Embed a Helvetica bold font (size 12)
        const font: PdfFont = document.embedFont(PdfFontFamily.helvetica, 12, PdfFontStyle.bold);
        // Create a blue PdfBrush for headings
        const blueBrush: PdfBrush = new PdfBrush({ r: 0, g: 0, b: 255 });
        // Draw the "JPEG Image" heading at (0, 40)
        g.drawString('JPEG Image', font, { x: 0, y: 40, width: 100, height: 100 }, blueBrush);
        // Create a PdfBitmap from the JPEG bytes
        const jpgImage: PdfBitmap = new PdfBitmap(jpgBytes);
        // Draw the JPEG image at (0, 70) sized 515x215
        g.drawImage(jpgImage, { x: 0, y: 70, width: 515, height: 215 });
        //  Draw the "PNG Image" heading at (0, 355)
        g.drawString('PNG Image', font, { x: 0, y: 355, width: 100, height: 100 }, blueBrush);
        // Create a PdfBitmap from the PNG bytes
        const pngImage: PdfBitmap = new PdfBitmap(pngBytes);
        // Draw the PNG image at (0, 365) sized 199x300
        g.drawImage(pngImage, { x: 0, y: 365, width: 199, height: 300 });
        // Save and download PDF
        const bytes = document.save();
        const parsed: PdfDocument = new PdfDocument(bytes);
        const parsedPage: PdfPage = parsed.getPage(0);
        const contents = parsedPage._pageDictionary.get('Contents');
        const ref = contents[2];
        const stream = parsedPage._crossReference._fetch(ref);
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        //Font check
        const fontDictionary: _PdfDictionary = parsedPage._pageDictionary.get('Resources').get('Font');
        const HelveticaBoldRef: string = result[11]._operands[0];
        const Helveticabold: _PdfName = fontDictionary.get(HelveticaBoldRef.slice(1)).get('BaseFont');
        //Image reference check 
        const xObject = parsedPage._pageDictionary.get('Resources').get('XObject');
        const jpegRef = result[21]._operands[0];
        const pngRef = result[31]._operands[0];
        //Content level check
        expect(Helveticabold.name).toEqual('Helvetica-Bold');
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands.length).toBe(0);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['40.000', '-40.000', '515.000', '-762.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands.length).toBe(0);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands.length).toBe(0);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands.length).toBe(0);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '40.00', '-40.00']);
        expect(result[7]._operator).toEqual('BT');
        expect(result[7]._operands.length).toBe(0);
        expect(result[8]._operator).toEqual('CS');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('cs');
        expect(result[9]._operands).toEqual(['/DeviceRGB']);
        expect(result[10]._operator).toEqual('rg');
        expect(result[10]._operands).toEqual(['0.000', '0.000', '1.000']);
        expect(result[11]._operator).toEqual('Tf');
        expect(result[11]._operands[0]).toEqual(HelveticaBoldRef);
        expect(result[11]._operands[1]).toEqual('12.000');
        expect(result[12]._operator).toEqual('Tr');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('Tc');
        expect(result[13]._operands).toEqual(['0.000']);
        expect(result[14]._operator).toEqual('Tw');
        expect(result[14]._operands).toEqual(['0.000']);
        expect(result[15]._operator).toEqual('Tz');
        expect(result[15]._operands).toEqual(['100.000']);
        expect(result[16]._operator).toEqual('Tm');
        expect(result[16]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '-51.54']);
        expect(result[17]._operator).toEqual("'");
        expect(result[17]._operands).toEqual(['(JPEG Image)']);
        expect(result[18]._operator).toEqual('ET');
        expect(result[18]._operands.length).toBe(0);
        expect(result[19]._operator).toEqual('q');
        expect(result[19]._operands.length).toBe(0);
        expect(result[20]._operator).toEqual('cm');
        expect(result[20]._operands).toEqual(['515.00', '.00', '.00', '215.00', '.00', '-285.00']);
        expect(result[21]._operator).toEqual('Do');
        expect(result[21]._operands).toEqual([jpegRef]);
        expect(result[22]._operator).toEqual('Q');
        expect(result[22]._operands.length).toBe(0);
        expect(result[23]._operator).toEqual('BT');
        expect(result[23]._operands.length).toBe(0);
        expect(result[24]._operator).toEqual('rg');
        expect(result[24]._operands).toEqual(['0.000', '0.000', '1.000']);
        expect(result[25]._operator).toEqual('Tf');
        expect(result[25]._operands[0]).toEqual(HelveticaBoldRef);
        expect(result[25]._operands[1]).toEqual('12.000');
        expect(result[26]._operator).toEqual('Tm');
        expect(result[26]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '-366.54']);
        expect(result[27]._operator).toEqual("'");
        expect(result[27]._operands).toEqual(['(PNG Image)']);
        expect(result[28]._operator).toEqual('ET');
        expect(result[28]._operands.length).toBe(0);
        expect(result[29]._operator).toEqual('q');
        expect(result[29]._operands.length).toBe(0);
        expect(result[30]._operator).toEqual('cm');
        expect(result[30]._operands).toEqual(['199.00', '.00', '.00', '300.00', '.00', '-665.00']);
        expect(result[31]._operator).toEqual('Do');
        expect(result[31]._operands).toEqual([pngRef]);
        expect(result[32]._operator).toEqual('Q');
        expect(result[32]._operands.length).toBe(0);
        //check the image is present 
        const jpg: _PdfStream = xObject.get(jpegRef.slice(1));
        let type = jpg.dictionary.get('Subtype');
        expect(jpg.dictionary.get('Length')).toEqual(84272);
        expect(type.name).toEqual('Image');
        const png: _PdfStream = xObject.get(pngRef.slice(1));
        type = png.dictionary.get('Subtype')
        expect(type.name).toEqual('Image');
        expect(png.dictionary.get('Length')).toEqual(120774);
        // Destroy the PDF document instance
        document.destroy();
        parsed.destroy();
    });
});
