import { PdfDocument } from '../src/pdf/core/pdf-document';
import { PdfSignatureField } from '../src/pdf/core/form/field';
import { CryptographicStandard, DigestAlgorithm, SignatureStatus } from '../src/pdf/core/enumerator';
import { timestampInput_1, timestampInput_2, timestampInput_3, timestampInput_4, timestampInput_5, pfx2, rootCert, intermediate0, intermediate1  } from './signature-validation-input.spec';
import { _decode, _padStart } from '../src/pdf/core/utils';
describe('983221 - Timestamp Extraction and Parsing', () => {
    it('Timestamp - valid signature with timestamp 1 ', async () => {
        const loaded = new PdfDocument(timestampInput_1);
        let signature = loaded.form.fieldAt(0) as PdfSignatureField;
        const result = signature.validateSignature();
        expect(result.cryptographicStandard).toEqual(CryptographicStandard.cms);
        expect(result.digestAlgorithm).toEqual(DigestAlgorithm.sha256);
        expect(result.signatureAlgorithm).toEqual('RSA');
        expect(result.signatureName).toEqual('Signature');
        expect(result.signatureStatus).toEqual(SignatureStatus.invalid);
        expect(result.validityAtSignedTime).toEqual(false);
        expect(result.validityAtTimestampTime).toEqual(false);
        expect(result.isDocumentModified).toBeFalsy();
        expect(result.revocationResult).toBeDefined();
        expect(result.timestampInformation).toBeDefined();
        expect(result.timestampInformation.isValid).toEqual(true);
        expect(result.timestampInformation.certificate).toBeDefined();
        expect(result.timestampInformation.isDocumentTimestamp).toBeFalsy();
        expect(result.timestampInformation.signerCertificates).toBeDefined();
        expect(result.timestampInformation.timestampPolicyId).toBeDefined();
        loaded.destroy();
    });
    it('Timestamp - valid signature with timestamp 2', async () => {
        const loaded = new PdfDocument(timestampInput_2);
        let signature = loaded.form.fieldAt(0) as PdfSignatureField;
        const result = signature.validateSignature();
        expect(result.cryptographicStandard).toEqual(CryptographicStandard.cms);
        expect(result.digestAlgorithm).toEqual(DigestAlgorithm.sha256);
        expect(result.signatureAlgorithm).toEqual('RSA');
        expect(result.signatureName).toEqual('Signature');
        expect(result.signatureStatus).toEqual(SignatureStatus.invalid);
        expect(result.validityAtSignedTime).toEqual(false);
        expect(result.validityAtTimestampTime).toEqual(false);
        expect(result.isDocumentModified).toBeFalsy();
        expect(result.revocationResult).toBeDefined();
        expect(result.timestampInformation).toBeDefined();
        expect(result.timestampInformation.isValid).toEqual(true);
        expect(result.timestampInformation.certificate).toBeDefined();
        expect(result.timestampInformation.isDocumentTimestamp).toBeFalsy();
        expect(result.timestampInformation.signerCertificates).toBeDefined();
        expect(result.timestampInformation.timestampPolicyId).toBeDefined();
        loaded.destroy();
    });
    it('Timestamp - valid signature with timestamp 3', async () => {
        const loaded = new PdfDocument(timestampInput_3);
        let signature = loaded.form.fieldAt(0) as PdfSignatureField;
        const result = signature.validateSignature();
        expect(result.cryptographicStandard).toEqual(CryptographicStandard.cms);
        expect(result.digestAlgorithm).toEqual(DigestAlgorithm.sha256);
        expect(result.signatureAlgorithm).toEqual('RSA');
        expect(result.signatureName).toEqual('Signature');
        expect(result.signatureStatus).toEqual(SignatureStatus.invalid);
        expect(result.validityAtSignedTime).toEqual(false);
        expect(result.validityAtTimestampTime).toEqual(false);
        expect(result.isDocumentModified).toBeFalsy();
        expect(result.revocationResult).toBeDefined();
        expect(result.timestampInformation).toBeDefined();
        expect(result.timestampInformation.isValid).toEqual(true);
        expect(result.timestampInformation.certificate).toBeDefined();
        expect(result.timestampInformation.isDocumentTimestamp).toBeFalsy();
        expect(result.timestampInformation.signerCertificates).toBeDefined();
        expect(result.timestampInformation.timestampPolicyId).toBeDefined();
        loaded.destroy();
    });
    it('Timestamp - valid signature with timestamp 4', async () => {
        const loaded = new PdfDocument(timestampInput_4);
        let signature = loaded.form.fieldAt(0) as PdfSignatureField;
        const result = signature.validateSignature();
        expect(result.cryptographicStandard).toEqual(CryptographicStandard.cms);
        expect(result.digestAlgorithm).toEqual(DigestAlgorithm.sha256);
        expect(result.signatureAlgorithm).toEqual('RSA');
        expect(result.signatureName).toEqual('Signature');
        expect(result.signatureStatus).toEqual(SignatureStatus.invalid);
        expect(result.validityAtSignedTime).toEqual(false);
        expect(result.validityAtTimestampTime).toEqual(false);
        expect(result.isDocumentModified).toBeFalsy();
        expect(result.revocationResult).toBeDefined();
        expect(result.timestampInformation).toBeDefined();
        expect(result.timestampInformation.isValid).toEqual(true);
        expect(result.timestampInformation.certificate).toBeDefined();
        expect(result.timestampInformation.isDocumentTimestamp).toBeFalsy();
        expect(result.timestampInformation.signerCertificates).toBeDefined();
        expect(result.timestampInformation.timestampPolicyId).toBeDefined();
        loaded.destroy();
    });
    it('Timestamp - valid signature with timestamp 5', async () => {
        const loaded = new PdfDocument(timestampInput_5);
        let signature = loaded.form.fieldAt(0) as PdfSignatureField;
        const result = signature.validateSignature();
        expect(result.cryptographicStandard).toEqual(CryptographicStandard.cms);
        expect(result.digestAlgorithm).toEqual(DigestAlgorithm.sha256);
        expect(result.signatureAlgorithm).toEqual('RSA');
        expect(result.signatureName).toEqual('Signature');
        expect(result.signatureStatus).toEqual(SignatureStatus.invalid);
        expect(result.validityAtSignedTime).toEqual(false);
        expect(result.validityAtTimestampTime).toEqual(false);
        expect(result.isDocumentModified).toBeFalsy();
        expect(result.revocationResult).toBeDefined();
        expect(result.timestampInformation).toBeDefined();
        expect(result.timestampInformation.isValid).toEqual(false);
        expect(result.timestampInformation.certificate).toBeDefined();
        expect(result.timestampInformation.isDocumentTimestamp).toBeFalsy();
        expect(result.timestampInformation.signerCertificates).toBeDefined();
        expect(result.timestampInformation.timestampPolicyId).toBeDefined();
        loaded.destroy();
    });
});
