import { PdfPageOrientation } from "./../src/pdf/core/enumerator";
import { PdfFont, PdfFontFamily, PdfFontStyle } from "./../src/pdf/core/fonts/pdf-standard-font";
import { PdfBitmap } from "./../src/pdf/core/graphics/images/pdf-bitmap";
import { PdfBrush, PdfGraphics } from "./../src/pdf/core/graphics/pdf-graphics";
import { PdfDocument, PdfMargins, PdfPageSettings } from "./../src/pdf/core/pdf-document";
import { PdfPage } from "./../src/pdf/core/pdf-page";
import { cover } from "./image-input.spec";
import { PdfButtonField, PdfCheckBoxField, PdfComboBoxField, PdfRadioButtonListField, PdfSignatureField, PdfTextBoxField } from './../src/pdf/core/form/field';
import { PdfListItem, PdfListItemCollection } from './../src/pdf/core/list/pdf-list-item';
import { PdfListFieldItem } from "./../src/pdf/core/annotations/annotation";
import { _ContentParser, _PdfRecord } from "./../src/pdf/core/content-parser";
import { _PdfDictionary, _PdfName } from "./../src/pdf/core/pdf-primitives";
import { _PdfStream } from "./../src/pdf/core/base-stream";

describe('Product Showcase', () => {
    it('Job application', () => {
        const imageBytes = cover;
        // Create a new PdfDocument
        const pdfDoc: PdfDocument = new PdfDocument();
        // Define PdfPageSettings
        const setting: PdfPageSettings = new PdfPageSettings({
            orientation: PdfPageOrientation.landscape,
            margins: new PdfMargins(0),
            size: { width: 500, height: 310 }
        });
        // Add first page with the above settings
        const firstPage: PdfPage = pdfDoc.addPage(setting);
        // Get graphics for the page and draw the background image covering the full page
        const g: PdfGraphics = firstPage.graphics;
        const img = new PdfBitmap(imageBytes);
        g.drawImage(img, { x: 0, y: 0, width: setting.size.width, height: setting.size.height });
        //  Create embed font
        let pdfFont: PdfFont = pdfDoc.embedFont(PdfFontFamily.helvetica, 12, PdfFontStyle.bold);
        const orange: PdfBrush = new PdfBrush({ r: 213, g: 123, b: 19 });
        // Define brush
        const labelBrush: PdfBrush = new PdfBrush({ r: 124, g: 143, b: 166 });
        const gray = { r: 128, g: 128, b: 128 };
        // Draw section title "General Information"
        g.drawString('General Information', pdfFont, { x: 25, y: 40, width: 150, height: 100 }, orange);
        // Draw section title "Education Grade"
        g.drawString('Education Grade', pdfFont, { x: 25, y: 190, width: 100, height: 100 }, orange);
        pdfFont = pdfDoc.embedFont(PdfFontFamily.helvetica, 10, PdfFontStyle.regular);
        let bounds = { x: 180, y: 65, width: 156, height: 15 };
        g.drawString('First Name:', pdfFont, { x: 25, y: 65, width: 100, height: 100 }, labelBrush);
        // Create "First Name" label and a PdfTextBoxField
        const firstName = new PdfTextBoxField(firstPage, 'FirstName', bounds);
        firstName.setAppearance(true);
        firstName.toolTip = 'First Name';
        firstName.font = pdfDoc.embedFont(PdfFontFamily.helvetica, 10, PdfFontStyle.regular);
        firstName.borderColor = gray;
        pdfDoc.form.add(firstName);
        g.drawString('Last Name:', pdfFont, { x: 25, y: 83, width: 100, height: 100 }, labelBrush);
        bounds = { x: bounds.x, y: bounds.y + 18, width: bounds.width, height: bounds.height };
        // Create "Last Name" label and PdfTextBoxField (same styling), add to form
        const lastName = new PdfTextBoxField(firstPage, 'LastName', bounds, { toolTip: 'Last Name', font: firstName.font, borderColor: gray });
        lastName.setAppearance(true);
        pdfDoc.form.add(lastName);
        g.drawString('Email:', pdfFont, { x: 25, y: 103, width: 100, height: 100 }, labelBrush);
        bounds = { x: bounds.x, y: bounds.y + 18, width: bounds.width, height: bounds.height };
        // Create "Email" label and PdfTextBoxField (same styling), add to form
        const email = new PdfTextBoxField(firstPage, 'Email', bounds, { toolTip: 'Email', font: firstName.font, borderColor: gray });
        email.setAppearance(true);
        pdfDoc.form.add(email);
        g.drawString('Business Phone:', pdfFont, { x: 25, y: 123, width: 100, height: 100 }, labelBrush);
        bounds = { x: bounds.x, y: bounds.y + 18, width: bounds.width, height: bounds.height };
        // Create "Business Phone" label and PdfTextBoxField (same styling), add to form
        const business = new PdfTextBoxField(firstPage, 'Business', bounds, { toolTip: 'Business phone', font: firstName.font, borderColor: gray });
        business.setAppearance(true);
        pdfDoc.form.add(business);
        g.drawString('Which position are\nyou applying for?', pdfFont, { x: 25, y: 143, width: 100, height: 100 }, labelBrush);
        bounds = { x: bounds.x, y: bounds.y + 24, width: bounds.width, height: bounds.height };
        const jobTitle = new PdfComboBoxField(firstPage, 'JobTitle', { x: bounds.x, y: bounds.y, width: bounds.width, height: bounds.height }, { items: [], borderColor: gray, font: pdfFont, toolTip: 'Job Title' });
        jobTitle.setAppearance(true);
        jobTitle.addItem(new PdfListFieldItem('Development', 'development'));
        jobTitle.addItem(new PdfListFieldItem('Support', 'support'));
        jobTitle.addItem(new PdfListFieldItem('Documentation', 'documentation'));
        pdfDoc.form.add(jobTitle);
        g.drawString('Highest qualification', pdfFont, { x: 25, y: 217, width: 100, height: 100 }, labelBrush);
        const tinyFont: PdfFont = pdfDoc.embedFont(PdfFontFamily.helvetica, 8, PdfFontStyle.regular);
        let cbPos = { x: 25, y: 239, width: 10, height: 10 };
        let chb = new PdfCheckBoxField('Adegree', { x: cbPos.x, y: cbPos.y, width: cbPos.width, height: cbPos.height }, firstPage, { toolTip: 'Associate degree', borderColor: gray });
        chb.setAppearance(true);
        pdfDoc.form.add(chb);
        g.drawString('Associate degree', tinyFont, { x: cbPos.x + chb.bounds.height + 10, y: cbPos.y, width: 150, height: 100 }, labelBrush);
        cbPos = { x: cbPos.x + 90, y: cbPos.y, width: cbPos.width, height: cbPos.height };
        chb = new PdfCheckBoxField('Bdegree', { x: cbPos.x, y: cbPos.y, width: cbPos.width, height: cbPos.height }, firstPage, { borderColor: gray });
        chb.setAppearance(true);
        pdfDoc.form.add(chb);
        g.drawString('Bachelor degree', tinyFont, { x: cbPos.x + chb.bounds.height + 10, y: cbPos.y, width: 150, height: 100 }, labelBrush);

        cbPos = { x: cbPos.x + 90, y: cbPos.y, width: cbPos.width, height: cbPos.height };
        chb = new PdfCheckBoxField('College', { x: cbPos.x, y: cbPos.y, width: cbPos.width, height: cbPos.height }, firstPage, { toolTip: 'College', borderColor: gray });
        chb.setAppearance(true);
        pdfDoc.form.add(chb);
        g.drawString('College', tinyFont, { x: cbPos.x + chb.bounds.height + 10, y: cbPos.y, width: 100, height: 100 }, labelBrush);

        cbPos = { x: 25, y: cbPos.y + 20, width: cbPos.width, height: cbPos.height };
        chb = new PdfCheckBoxField('PG', { x: cbPos.x, y: cbPos.y, width: cbPos.width, height: cbPos.height }, firstPage, { borderColor: gray });
        chb.setAppearance(true);
        pdfDoc.form.add(chb);
        g.drawString('Post Graduate', tinyFont, { x: cbPos.x + chb.bounds.height + 10, y: cbPos.y, width: 150, height: 100 }, labelBrush);

        cbPos = { x: cbPos.x + 90, y: cbPos.y, width: cbPos.width, height: cbPos.height };
        chb = new PdfCheckBoxField('MBA', { x: cbPos.x, y: cbPos.y, width: cbPos.width, height: cbPos.height }, firstPage, { borderColor: gray });
        chb.setAppearance(true);
        pdfDoc.form.add(chb);
        g.drawString('MBA', tinyFont, { x: cbPos.x + chb.bounds.height + 10, y: cbPos.y, width: 100, height: 100 }, labelBrush);
        // Add second page with same settings and background image
        const secondPage: PdfPage = pdfDoc.addPage(setting);
        const g2: PdfGraphics = secondPage.graphics;
        g2.drawImage(img, { x: 0, y: 0, width: setting.size.width, height: setting.size.height });
        g2.drawString('Current position', pdfDoc.embedFont(PdfFontFamily.timesRoman, 10, PdfFontStyle.bold), { x: 25, y: 40, width: 100, height: 100 }, orange);
        // Add "I am not currently employed" checkbox (Cemp):
        let bounds2 = { x: 25, y: 65, width: 10, height: 10 };
        chb = new PdfCheckBoxField('Cemp', { x: bounds2.x, y: bounds2.y, width: bounds2.width, height: bounds2.height }, secondPage);
        chb.setAppearance(true);
        chb.font = pdfFont;
        chb.borderColor = gray;
        chb.border.width = 1;
        pdfDoc.form.add(chb);
        g2.drawString('I am not currently employed', pdfFont, { x: bounds2.x + chb.bounds.height + 10, y: bounds2.y, width: 200, height: 100 }, labelBrush);
        // Add "Job Title" label and PdfTextBoxField (Jtitle), add to form
        g2.drawString('Job Title', pdfFont, { x: 25, y: 85, width: 100, height: 100 }, labelBrush);
        const jobBounds = { x: 175, y: 85, width: 156, height: 15 };
        const font10 = pdfDoc.embedFont(PdfFontFamily.helvetica, 10, PdfFontStyle.regular);
        let jobTitle1 = new PdfTextBoxField(secondPage, 'Jtitle', jobBounds, { toolTip: 'Job title', font: font10, borderColor: gray });
        jobTitle1.setAppearance(true);
        pdfDoc.form.add(jobTitle1);
        // Add "Employer" label and PdfTextBoxField (Employer), add to form
        g2.drawString('Employer:', pdfFont, { x: 25, y: 103, width: 100, height: 100 }, labelBrush);
        let employer = new PdfTextBoxField(secondPage, 'Employer', { x: 175, y: 103, width: 156, height: 15 }, { toolTip: 'Employer', font: font10, borderColor: gray });
        employer.setAppearance(true);
        pdfDoc.form.add(employer);
        //  Add "Reason for leaving" label and PdfTextBoxField (Reason), add to form
        g2.drawString('Reason for leaving:', pdfFont, { x: 25, y: 123, width: 100, height: 100 }, labelBrush);
        let reason = new PdfTextBoxField(secondPage, 'Reason', { x: 175, y: 121, width: 156, height: 15 }, { toolTip: 'Reason for leaving', font: font10, borderColor: gray });
        reason.setAppearance(true);
        pdfDoc.form.add(reason);
        // Add "Total Annual salary" label and PdfTextBoxField (Asalary), add to form
        g2.drawString('Total Annual salary:', pdfFont, { x: 25, y: 143, width: 100, height: 100 }, labelBrush);
        let annualSalary = new PdfTextBoxField(secondPage, 'Asalary', { x: 175, y: 139, width: 156, height: 15 }, { toolTip: 'Annual salary', font: font10, borderColor: gray });
        annualSalary.setAppearance(true);
        pdfDoc.form.add(annualSalary);
        // Add "Duties" label and a multi-line PdfTextBoxField (Duties), add to form
        g2.drawString('Duties:', pdfFont, { x: 25, y: 168, width: 100, height: 100 }, labelBrush);
        let duties = new PdfTextBoxField(secondPage, 'Duties', { x: 25, y: 189, width: 156, height: 70 }, { toolTip: 'Duties', font: font10, borderColor: gray });
        duties.setAppearance(true);
        duties.multiLine = true;
        pdfDoc.form.add(duties);
        // Add "Employment type" label and a PdfComboBoxField (EmpType):
        g2.drawString('Employment type:', pdfFont, { x: 25, y: 268, width: 100, height: 100 }, labelBrush);
        const empType = new PdfComboBoxField(secondPage, 'EmpType', { x: 175, y: 263, width: 156, height: 20 });
        empType.setAppearance(true);
        empType.borderColor = gray;
        empType.font = pdfFont;
        empType.toolTip = 'Employment type';
        empType.addItem(new PdfListFieldItem('Full time', 'ft'));
        empType.addItem(new PdfListFieldItem('Part time', 'pt'));
        pdfDoc.form.add(empType);
        // Add third page with same settings and background image
        const thirdPage: PdfPage = pdfDoc.addPage(setting);
        const g3: PdfGraphics = thirdPage.graphics;
        g3.drawImage(img, { x: 0, y: 0, width: setting.size.width, height: setting.size.height });
        // Draw "Thank You" title and a message paragraph
        const bold12 = pdfDoc.embedFont(PdfFontFamily.helvetica, 12, PdfFontStyle.bold);
        g3.drawString('Thank You', bold12, { x: 25, y: 80, width: 100, height: 100 }, orange);
        const regular10 = pdfDoc.embedFont(PdfFontFamily.helvetica, 10, PdfFontStyle.regular);
        g3.drawString('Thanks for taking the time to complete this form.\nWe will be in contact with you shortly.', regular10, { x: 25, y: 110, width: 250, height: 100 }, labelBrush);
        // Create a PdfButtonField 
        const submitBtn = new PdfButtonField(thirdPage, 'SubmitButton', { x: 25, y: 160, width: 100, height: 20 }, { text: 'Apply', backColor: { r: 181, g: 191, b: 203 }, borderColor: { r: 0, g: 0, b: 0 } });
        submitBtn.font = regular10;
        submitBtn.setAppearance(true);
        pdfDoc.form.add(submitBtn);
        // Save and download the document
        const bytes = pdfDoc.save();
        // Destroy the document instance.
        pdfDoc.destroy();
        function CheckCommonCasesInTextBox(result: _PdfRecord[]) {
            let i = 0;
            expect(result[i]._operator).toEqual('BMC');
            expect(result[i]._operands).toEqual(['/Tx']);
            expect(result[i + 1]._operator).toEqual('cm');
            expect(result[i + 1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '15.00']);
            expect(result[i + 2]._operator).toEqual('CS');
            expect(result[i + 2]._operands).toEqual(['/DeviceRGB']);
            expect(result[i + 3]._operator).toEqual('cs');
            expect(result[i + 3]._operands).toEqual(['/DeviceRGB']);
            expect(result[i + 4]._operator).toEqual('rg');
            expect(result[i + 4]._operands).toEqual(['1.000', '1.000', '1.000']);
            expect(result[i + 5]._operator).toEqual('re');
            expect(result[i + 5]._operands).toEqual(['0.000', '0.000', '156.000', '-15.000']);
            expect(result[i + 6]._operator).toEqual('f');
            expect(result[i + 6]._operands).toEqual([]);
            expect(result[i + 7]._operator).toEqual('d');
            expect(result[i + 7]._operands).toEqual(['[]', '0']);
            expect(result[i + 8]._operator).toEqual('w');
            expect(result[i + 8]._operands).toEqual(['1.000']);
            expect(result[i + 9]._operator).toEqual('j');
            expect(result[i + 9]._operands).toEqual(['0']);
            expect(result[i + 10]._operator).toEqual('J');
            expect(result[i + 10]._operands).toEqual(['0']);
            expect(result[i + 11]._operator).toEqual('RG');
            expect(result[i + 11]._operands).toEqual(['0.502', '0.502', '0.502']);
            expect(result[i + 12]._operator).toEqual('re');
            expect(result[i + 12]._operands).toEqual(['0.500', '-0.500', '155.000', '-14.000']);
            expect(result[i + 13]._operator).toEqual('S');
            expect(result[i + 13]._operands).toEqual([]);
            expect(result[i + 14]._operator).toEqual('EMC');
            expect(result[i + 14]._operands).toEqual([]);
        }
        function checkCheckBox(result: _PdfRecord[]) {
            expect(result[0]._operator).toEqual('cm');
            expect(result[0]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '10.00']);
            expect(result[1]._operator).toEqual('CS');
            expect(result[1]._operands).toEqual(['/DeviceRGB']);
            expect(result[2]._operator).toEqual('cs');
            expect(result[2]._operands).toEqual(['/DeviceRGB']);
            expect(result[3]._operator).toEqual('rg');
            expect(result[3]._operands).toEqual(['1.000', '1.000', '1.000']);
            expect(result[4]._operator).toEqual('re');
            expect(result[4]._operands).toEqual(['0.000', '0.000', '10.000', '-10.000']);
            expect(result[5]._operator).toEqual('f');
            expect(result[5]._operands).toEqual([]);
            expect(result[6]._operator).toEqual('d');
            expect(result[6]._operands).toEqual(['[]', '0']);
            expect(result[7]._operator).toEqual('w');
            expect(result[7]._operands).toEqual(['1.000']);
            expect(result[8]._operator).toEqual('j');
            expect(result[8]._operands).toEqual(['0']);
            expect(result[9]._operator).toEqual('J');
            expect(result[9]._operands).toEqual(['0']);
            expect(result[10]._operator).toEqual('RG');
            expect(result[10]._operands).toEqual(['0.502', '0.502', '0.502']);
            expect(result[11]._operator).toEqual('re');
            expect(result[11]._operands).toEqual(['0.500', '-0.500', '9.000', '-9.000']);
            expect(result[12]._operator).toEqual('S');
            expect(result[12]._operands).toEqual([]);
            expect(result[13]._operator).toEqual('q');
            expect(result[13]._operands).toEqual([]);
            expect(result[14]._operator).toEqual('BT');
            expect(result[14]._operands).toEqual([]);
            expect(result[15]._operator).toEqual('rg');
            expect(result[15]._operands).toEqual(['0.000', '0.000', '0.000']);
            expect(result[16]._operator).toEqual('Tf');
            expect(result[16]._operands[1]).toEqual('8.000');
            expect(result[17]._operator).toEqual('Tr');
            expect(result[17]._operands).toEqual(['0']);
            expect(result[18]._operator).toEqual('Tc');
            expect(result[18]._operands).toEqual(['0.000']);
            expect(result[19]._operator).toEqual('Tw');
            expect(result[19]._operands).toEqual(['0.000']);
            expect(result[20]._operator).toEqual('Tz');
            expect(result[20]._operands).toEqual(['100.000']);
            expect(result[21]._operator).toEqual('Tm');
            expect(result[21]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '-7.71']);
            expect(result[22]._operator).toEqual('Td');
            expect(result[22]._operands).toEqual(['1.616', '0.000']);
            expect(result[23]._operator).toEqual("'");
            expect(result[23]._operands).toEqual(['(4)']);
            expect(result[24]._operator).toEqual('Td');
            expect(result[24]._operands).toEqual(['0.000', '-6.556']);
            expect(result[25]._operator).toEqual('ET');
            expect(result[25]._operands).toEqual([]);

        }
        function checkCoverImage(result: _PdfRecord[]) {
            expect(result[0]._operator).toEqual('q');
            expect(result[0]._operands).toEqual([]);
            expect(result[1]._operator).toEqual('cm');
            expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '310.00']);
            expect(result[2]._operator).toEqual('re');
            expect(result[2]._operands).toEqual(['0.000', '0.000', '500.000', '-310.000']);
            expect(result[3]._operator).toEqual('h');
            expect(result[3]._operands).toEqual([]);
            expect(result[4]._operator).toEqual('W');
            expect(result[4]._operands).toEqual([]);
            expect(result[5]._operator).toEqual('n');
            expect(result[5]._operands).toEqual([]);
            expect(result[6]._operator).toEqual('cm');
            expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '.00']);
            expect(result[7]._operator).toEqual('q');
            expect(result[7]._operands).toEqual([]);
            expect(result[8]._operator).toEqual('cm');
            expect(result[8]._operands).toEqual(['500.00', '.00', '.00', '310.00', '.00', '-310.00']);
            expect(result[9]._operator).toEqual('Do');
            expect(result[9]._operands).toEqual([imageRef]);
            expect(result[10]._operator).toEqual('Q');
        }
        const parsed = new PdfDocument(bytes);
        let parsedPage: PdfPage = parsed.getPage(0);
        let contents = parsedPage._pageDictionary.get('Contents');
        let ref = contents[2];
        let stream = parsedPage._crossReference._fetch(ref);
        let parser: _ContentParser = new _ContentParser(stream.getBytes());
        let result: _PdfRecord[] = parser._readContent();
        //Font check
        let fontDictionary: _PdfDictionary = parsedPage._pageDictionary.get('Resources').get('Font');
        let HelveticaBoldRef: string = result[15]._operands[0];
        let HelveticaBold: _PdfName = fontDictionary.get(HelveticaBoldRef.slice(1)).get('BaseFont');
        let HelveticaRef: string = result[31]._operands[0];
        let Helvetica: _PdfName = fontDictionary.get(HelveticaRef.slice(1)).get('BaseFont');
        //Content level check
        expect(HelveticaBold.name).toEqual('Helvetica-Bold');
        expect(Helvetica.name).toEqual('Helvetica');
        let imageRef = result[9]._operands[0];
        let xObject = parsedPage._pageDictionary.get('Resources').get('XObject');
        let image: _PdfStream = xObject.get(imageRef.slice(1));
        let type = image.dictionary.get('Subtype')
        expect(type.name).toEqual('Image');
        checkCoverImage(result);
        expect(result[10]._operands).toEqual([]);
        expect(result[11]._operator).toEqual('BT');
        expect(result[11]._operands).toEqual([]);
        expect(result[12]._operator).toEqual('CS');
        expect(result[12]._operands).toEqual(['/DeviceRGB']);
        expect(result[13]._operator).toEqual('cs');
        expect(result[13]._operands).toEqual(['/DeviceRGB']);
        expect(result[14]._operator).toEqual('rg');
        expect(result[14]._operands).toEqual(['0.835', '0.482', '0.075']);
        expect(result[15]._operator).toEqual('Tf');
        expect(result[15]._operands[1]).toEqual('12.000');
        expect(result[16]._operator).toEqual('Tr');
        expect(result[16]._operands).toEqual(['0']);
        expect(result[17]._operator).toEqual('Tc');
        expect(result[17]._operands).toEqual(['0.000']);
        expect(result[18]._operator).toEqual('Tw');
        expect(result[18]._operands).toEqual(['0.000']);
        expect(result[19]._operator).toEqual('Tz');
        expect(result[19]._operands).toEqual(['100.000']);
        expect(result[20]._operator).toEqual('Tm');
        expect(result[20]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-51.54']);
        expect(result[21]._operator).toEqual("'");
        expect(result[21]._operands).toEqual(['(General Information)']);
        expect(result[22]._operator).toEqual('ET');
        expect(result[22]._operands).toEqual([]);
        expect(result[23]._operator).toEqual('BT');
        expect(result[23]._operands).toEqual([]);
        expect(result[24]._operator).toEqual('rg');
        expect(result[24]._operands).toEqual(['0.835', '0.482', '0.075']);
        expect(result[25]._operator).toEqual('Tf');
        expect(result[25]._operands[1]).toEqual('12.000');
        expect(result[26]._operator).toEqual('Tm');
        expect(result[26]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-201.54']);
        expect(result[27]._operator).toEqual("'");
        expect(result[27]._operands).toEqual(['(Education Grade)']);
        expect(result[28]._operator).toEqual('ET');
        expect(result[28]._operands).toEqual([]);
        expect(result[29]._operator).toEqual('BT');
        expect(result[29]._operands).toEqual([]);
        expect(result[30]._operator).toEqual('rg');
        expect(result[30]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[31]._operator).toEqual('Tf');
        expect(result[31]._operands[1]).toEqual('10.000');
        expect(result[32]._operator).toEqual('Tm');
        expect(result[32]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-74.31']);
        expect(result[33]._operator).toEqual("'");
        expect(result[33]._operands).toEqual(['(First Name:)']);
        expect(result[34]._operator).toEqual('ET');
        expect(result[34]._operands).toEqual([]);
        expect(result[35]._operator).toEqual('BT');
        expect(result[35]._operands).toEqual([]);
        expect(result[36]._operator).toEqual('rg');
        expect(result[36]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[37]._operator).toEqual('Tf');
        expect(result[37]._operands[1]).toEqual('10.000');
        expect(result[38]._operator).toEqual('Tm');
        expect(result[38]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-92.31']);
        expect(result[39]._operator).toEqual("'");
        expect(result[39]._operands).toEqual(['(Last Name:)']);
        expect(result[40]._operator).toEqual('ET');
        expect(result[40]._operands).toEqual([]);
        expect(result[41]._operator).toEqual('BT');
        expect(result[41]._operands).toEqual([]);
        expect(result[42]._operator).toEqual('rg');
        expect(result[42]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[43]._operator).toEqual('Tf');
        expect(result[43]._operands[1]).toEqual('10.000');
        expect(result[44]._operator).toEqual('Tm');
        expect(result[44]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-112.31']);
        expect(result[45]._operator).toEqual("'");
        expect(result[45]._operands).toEqual(['(Email:)']);
        expect(result[46]._operator).toEqual('ET');
        expect(result[46]._operands).toEqual([]);
        expect(result[47]._operator).toEqual('BT');
        expect(result[47]._operands).toEqual([]);
        expect(result[48]._operator).toEqual('rg');
        expect(result[48]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[49]._operator).toEqual('Tf');
        expect(result[49]._operands[1]).toEqual('10.000');
        expect(result[50]._operator).toEqual('Tm');
        expect(result[50]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-132.31']);
        expect(result[51]._operator).toEqual("'");
        expect(result[51]._operands).toEqual(['(Business Phone:)']);
        expect(result[52]._operator).toEqual('ET');
        expect(result[52]._operands).toEqual([]);
        expect(result[53]._operator).toEqual('BT');
        expect(result[53]._operands).toEqual([]);
        expect(result[54]._operator).toEqual('rg');
        expect(result[54]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[55]._operator).toEqual('Tf');
        expect(result[55]._operands[1]).toEqual('10.000');
        expect(result[56]._operator).toEqual('Tm');
        expect(result[56]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-152.31']);
        expect(result[57]._operator).toEqual("'");
        expect(result[57]._operands).toEqual(['(Which position are)']);
        expect(result[58]._operator).toEqual('Tm');
        expect(result[58]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-163.87']);
        expect(result[59]._operator).toEqual("'");
        expect(result[59]._operands).toEqual(['(you applying for?)']);
        expect(result[60]._operator).toEqual('ET');
        expect(result[60]._operands).toEqual([]);
        expect(result[61]._operator).toEqual('BT');
        expect(result[61]._operands).toEqual([]);
        expect(result[62]._operator).toEqual('rg');
        expect(result[62]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[63]._operator).toEqual('Tf');
        expect(result[63]._operands[1]).toEqual('10.000');
        expect(result[64]._operator).toEqual('Tm');
        expect(result[64]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-226.31']);
        expect(result[65]._operator).toEqual("'");
        expect(result[65]._operands).toEqual(['(Highest qualification)']);
        expect(result[66]._operator).toEqual('ET');
        expect(result[66]._operands).toEqual([]);
        expect(result[67]._operator).toEqual('BT');
        expect(result[67]._operands).toEqual([]);
        expect(result[68]._operator).toEqual('rg');
        expect(result[68]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[69]._operator).toEqual('Tf');
        expect(result[69]._operands[1]).toEqual('8.000');
        expect(result[70]._operator).toEqual('Tm');
        expect(result[70]._operands).toEqual(['1.00', '.00', '.00', '1.00', '45.00', '-246.45']);
        expect(result[71]._operator).toEqual("'");
        expect(result[71]._operands).toEqual(['(Associate degree)']);
        expect(result[72]._operator).toEqual('ET');
        expect(result[72]._operands).toEqual([]);
        expect(result[73]._operator).toEqual('BT');
        expect(result[73]._operands).toEqual([]);
        expect(result[74]._operator).toEqual('rg');
        expect(result[74]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[75]._operator).toEqual('Tf');
        expect(result[75]._operands[1]).toEqual('8.000');
        expect(result[76]._operator).toEqual('Tm');
        expect(result[76]._operands).toEqual(['1.00', '.00', '.00', '1.00', '135.00', '-246.45']);
        expect(result[77]._operator).toEqual("'");
        expect(result[77]._operands).toEqual(['(Bachelor degree)']);
        expect(result[78]._operator).toEqual('ET');
        expect(result[78]._operands).toEqual([]);
        expect(result[79]._operator).toEqual('BT');
        expect(result[79]._operands).toEqual([]);
        expect(result[80]._operator).toEqual('rg');
        expect(result[80]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[81]._operator).toEqual('Tf');
        expect(result[81]._operands[1]).toEqual('8.000');
        expect(result[82]._operator).toEqual('Tm');
        expect(result[82]._operands).toEqual(['1.00', '.00', '.00', '1.00', '225.00', '-246.45']);
        expect(result[83]._operator).toEqual("'");
        expect(result[83]._operands).toEqual(['(College)']);
        expect(result[84]._operator).toEqual('ET');
        expect(result[84]._operands).toEqual([]);
        expect(result[85]._operator).toEqual('BT');
        expect(result[85]._operands).toEqual([]);
        expect(result[86]._operator).toEqual('rg');
        expect(result[86]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[87]._operator).toEqual('Tf');
        expect(result[87]._operands[1]).toEqual('8.000');
        expect(result[88]._operator).toEqual('Tm');
        expect(result[88]._operands).toEqual(['1.00', '.00', '.00', '1.00', '45.00', '-266.45']);
        expect(result[89]._operator).toEqual("'");
        expect(result[89]._operands).toEqual(['(Post Graduate)']);
        expect(result[90]._operator).toEqual('ET');
        expect(result[90]._operands).toEqual([]);
        expect(result[91]._operator).toEqual('BT');
        expect(result[91]._operands).toEqual([]);
        expect(result[92]._operator).toEqual('rg');
        expect(result[92]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[93]._operator).toEqual('Tf');
        expect(result[93]._operands[1]).toEqual('8.000');
        expect(result[94]._operator).toEqual('Tm');
        expect(result[94]._operands).toEqual(['1.00', '.00', '.00', '1.00', '135.00', '-266.45']);
        expect(result[95]._operator).toEqual("'");
        expect(result[95]._operands).toEqual(['(MBA)']);
        expect(result[96]._operator).toEqual('ET');
        expect(result[96]._operands).toEqual([]);
        let annotations = parsedPage._pageDictionary.get('Annots');
        let fieldResult = getAnnotationRecords(annotations[0], parsedPage);
        CheckCommonCasesInTextBox(fieldResult);
        fieldResult = getAnnotationRecords(annotations[1], parsedPage);
        CheckCommonCasesInTextBox(fieldResult);
        fieldResult = getAnnotationRecords(annotations[2], parsedPage);
        CheckCommonCasesInTextBox(fieldResult);
        fieldResult = getAnnotationRecords(annotations[3], parsedPage);
        CheckCommonCasesInTextBox(fieldResult);
        fieldResult = getAnnotationRecords(annotations[4], parsedPage);
        CheckCommonCasesInTextBox(fieldResult);
        let annotation = parsedPage._crossReference._fetch(annotations[5]);
        let checkbox = annotation.get('AP').get('N').get('Yes');
        expect(annotation.get('AP').get('D')).toBeDefined();
        expect(checkbox).toBeDefined();
        let fieldParser = new _ContentParser(checkbox.getBytes());
        fieldResult = fieldParser._readContent();
        checkCheckBox(fieldResult);
        annotation = parsedPage._crossReference._fetch(annotations[6]);
        checkbox = annotation.get('AP').get('N').get('Yes');
        expect(annotation.get('AP').get('D')).toBeDefined();
        expect(checkbox).toBeDefined();
        fieldParser = new _ContentParser(checkbox.getBytes());
        fieldResult = fieldParser._readContent();
        checkCheckBox(fieldResult);
        annotation = parsedPage._crossReference._fetch(annotations[7]);
        checkbox = annotation.get('AP').get('N').get('Yes');
        expect(annotation.get('AP').get('D')).toBeDefined();
        expect(checkbox).toBeDefined();
        fieldParser = new _ContentParser(checkbox.getBytes());
        fieldResult = fieldParser._readContent();
        checkCheckBox(fieldResult);
        annotation = parsedPage._crossReference._fetch(annotations[8]);
        checkbox = annotation.get('AP').get('N').get('Yes');
        expect(annotation.get('AP').get('D')).toBeDefined();
        expect(checkbox).toBeDefined();
        fieldParser = new _ContentParser(checkbox.getBytes());
        fieldResult = fieldParser._readContent();
        checkCheckBox(fieldResult);
        annotation = parsedPage._crossReference._fetch(annotations[9]);
        checkbox = annotation.get('AP').get('N').get('Yes');
        expect(annotation.get('AP').get('D')).toBeDefined();
        expect(checkbox).toBeDefined();
        fieldParser = new _ContentParser(checkbox.getBytes());
        fieldResult = fieldParser._readContent();
        checkCheckBox(fieldResult);
        //Check the contents and apperance in the page two
        parsedPage = parsed.getPage(1);
        contents = parsedPage._pageDictionary.get('Contents');
        ref = contents[2];
        stream = parsedPage._crossReference._fetch(ref);
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        //Font check in page 2
        fontDictionary = parsedPage._pageDictionary.get('Resources').get('Font');
        let timesBoldRef = result[15]._operands[0];
        let timesBold = fontDictionary.get(timesBoldRef.slice(1)).get('BaseFont');
        HelveticaRef = result[31]._operands[0];
        Helvetica = fontDictionary.get(HelveticaRef.slice(1)).get('BaseFont');
        //Content level check in page 2
        expect(timesBold.name).toEqual('Times-Bold');
        expect(Helvetica.name).toEqual('Helvetica');
        imageRef = result[9]._operands[0];
        xObject = parsedPage._pageDictionary.get('Resources').get('XObject');
        image = xObject.get(imageRef.slice(1));
        type = image.dictionary.get('Subtype')
        expect(type.name).toEqual('Image');
        checkCoverImage(result);
        expect(result[10]._operands).toEqual([]);
        expect(result[11]._operator).toEqual('BT');
        expect(result[11]._operands).toEqual([]);
        expect(result[12]._operator).toEqual('CS');
        expect(result[12]._operands).toEqual(['/DeviceRGB']);
        expect(result[13]._operator).toEqual('cs');
        expect(result[13]._operands).toEqual(['/DeviceRGB']);
        expect(result[14]._operator).toEqual('rg');
        expect(result[14]._operands).toEqual(['0.835', '0.482', '0.075']);
        expect(result[15]._operator).toEqual('Tf');
        expect(result[15]._operands[1]).toEqual('10.000');
        expect(result[16]._operator).toEqual('Tr');
        expect(result[16]._operands).toEqual(['0']);
        expect(result[17]._operator).toEqual('Tc');
        expect(result[17]._operands).toEqual(['0.000']);
        expect(result[18]._operator).toEqual('Tw');
        expect(result[18]._operands).toEqual(['0.000']);
        expect(result[19]._operator).toEqual('Tz');
        expect(result[19]._operands).toEqual(['100.000']);
        expect(result[20]._operator).toEqual('Tm');
        expect(result[20]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-49.35']);
        expect(result[21]._operator).toEqual("'");
        expect(result[21]._operands).toEqual(['(Current position)']);
        expect(result[22]._operator).toEqual('ET');
        expect(result[22]._operands).toEqual([]);
        expect(result[23]._operator).toEqual('BT');
        expect(result[23]._operands).toEqual([]);
        expect(result[24]._operator).toEqual('rg');
        expect(result[24]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[25]._operator).toEqual('Tf');
        expect(result[25]._operands[1]).toEqual('10.000');
        expect(result[26]._operator).toEqual('Tm');
        expect(result[26]._operands).toEqual(['1.00', '.00', '.00', '1.00', '45.00', '-74.31']);
        expect(result[27]._operator).toEqual("'");
        expect(result[27]._operands).toEqual(['(I am not currently employed)']);
        expect(result[28]._operator).toEqual('ET');
        expect(result[28]._operands).toEqual([]);
        expect(result[29]._operator).toEqual('BT');
        expect(result[29]._operands).toEqual([]);
        expect(result[30]._operator).toEqual('rg');
        expect(result[30]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[31]._operator).toEqual('Tf');
        expect(result[31]._operands[1]).toEqual('10.000');
        expect(result[32]._operator).toEqual('Tm');
        expect(result[32]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-94.31']);
        expect(result[33]._operator).toEqual("'");
        expect(result[33]._operands).toEqual(['(Job Title)']);
        expect(result[34]._operator).toEqual('ET');
        expect(result[34]._operands).toEqual([]);
        expect(result[35]._operator).toEqual('BT');
        expect(result[35]._operands).toEqual([]);
        expect(result[36]._operator).toEqual('rg');
        expect(result[36]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[37]._operator).toEqual('Tf');
        expect(result[37]._operands[1]).toEqual('10.000');
        expect(result[38]._operator).toEqual('Tm');
        expect(result[38]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-112.31']);
        expect(result[39]._operator).toEqual("'");
        expect(result[39]._operands).toEqual(['(Employer:)']);
        expect(result[40]._operator).toEqual('ET');
        expect(result[40]._operands).toEqual([]);
        expect(result[41]._operator).toEqual('BT');
        expect(result[41]._operands).toEqual([]);
        expect(result[42]._operator).toEqual('rg');
        expect(result[42]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[43]._operator).toEqual('Tf');
        expect(result[43]._operands[1]).toEqual('10.000');
        expect(result[44]._operator).toEqual('Tm');
        expect(result[44]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-132.31']);
        expect(result[45]._operator).toEqual("'");
        expect(result[45]._operands).toEqual(['(Reason for leaving:)']);
        expect(result[46]._operator).toEqual('ET');
        expect(result[46]._operands).toEqual([]);
        expect(result[47]._operator).toEqual('BT');
        expect(result[47]._operands).toEqual([]);
        expect(result[48]._operator).toEqual('rg');
        expect(result[48]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[49]._operator).toEqual('Tf');
        expect(result[49]._operands[1]).toEqual('10.000');
        expect(result[50]._operator).toEqual('Tm');
        expect(result[50]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-152.31']);
        expect(result[51]._operator).toEqual("'");
        expect(result[51]._operands).toEqual(['(Total Annual salary:)']);
        expect(result[52]._operator).toEqual('ET');
        expect(result[52]._operands).toEqual([]);
        expect(result[53]._operator).toEqual('BT');
        expect(result[53]._operands).toEqual([]);
        expect(result[54]._operator).toEqual('rg');
        expect(result[54]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[55]._operator).toEqual('Tf');
        expect(result[55]._operands[1]).toEqual('10.000');
        expect(result[56]._operator).toEqual('Tm');
        expect(result[56]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-177.31']);
        expect(result[57]._operator).toEqual("'");
        expect(result[57]._operands).toEqual(['(Duties:)']);
        expect(result[58]._operator).toEqual('ET');
        expect(result[58]._operands).toEqual([]);
        expect(result[59]._operator).toEqual('BT');
        expect(result[59]._operands).toEqual([]);
        expect(result[60]._operator).toEqual('rg');
        expect(result[60]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[61]._operator).toEqual('Tf');
        expect(result[61]._operands[1]).toEqual('10.000');
        expect(result[62]._operator).toEqual('Tm');
        expect(result[62]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-277.31']);
        expect(result[63]._operator).toEqual("'");
        expect(result[63]._operands).toEqual(['(Employment type:)']);
        expect(result[64]._operator).toEqual('ET');
        expect(result[64]._operands).toEqual([]);
        //Annotations of page two
        annotations = parsedPage._pageDictionary.get('Annots');
        annotation = parsedPage._crossReference._fetch(annotations[0]);
        checkbox = annotation.get('AP').get('N').get('Yes');
        expect(annotation.get('AP').get('D')).toBeDefined();
        expect(checkbox).toBeDefined();
        fieldParser = new _ContentParser(checkbox.getBytes());
        fieldResult = fieldParser._readContent();
        checkCheckBox(fieldResult);
        fieldResult = getAnnotationRecords(annotations[1], parsedPage);
        CheckCommonCasesInTextBox(fieldResult);
        fieldResult = getAnnotationRecords(annotations[2], parsedPage);
        CheckCommonCasesInTextBox(fieldResult);
        fieldResult = getAnnotationRecords(annotations[3], parsedPage);
        CheckCommonCasesInTextBox(fieldResult);
        fieldResult = getAnnotationRecords(annotations[4], parsedPage);
        CheckCommonCasesInTextBox(fieldResult);
        fieldResult = getAnnotationRecords(annotations[5], parsedPage);
        expect(fieldResult[12]._operands).toEqual(['0.500', '-0.500', '155.000', '-69.000']); //on;y change in the text area
        fieldResult = getAnnotationRecords(annotations[6], parsedPage);
        expect(fieldResult[0]._operator).toEqual('BMC');
        expect(fieldResult[0]._operands).toEqual(['/Tx']);
        expect(fieldResult[1]._operator).toEqual('cm');
        expect(fieldResult[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '20.00']);
        expect(fieldResult[2]._operator).toEqual('CS');
        expect(fieldResult[2]._operands).toEqual(['/DeviceRGB']);
        expect(fieldResult[3]._operator).toEqual('cs');
        expect(fieldResult[3]._operands).toEqual(['/DeviceRGB']);
        expect(fieldResult[4]._operator).toEqual('rg');
        expect(fieldResult[4]._operands).toEqual(['1.000', '1.000', '1.000']);
        expect(fieldResult[5]._operator).toEqual('re');
        expect(fieldResult[5]._operands).toEqual(['0.000', '0.000', '156.000', '-20.000']);
        expect(fieldResult[6]._operator).toEqual('f');
        expect(fieldResult[6]._operands).toEqual([]);
        expect(fieldResult[7]._operator).toEqual('d');
        expect(fieldResult[7]._operands).toEqual(['[]', '0']);
        expect(fieldResult[8]._operator).toEqual('w');
        expect(fieldResult[8]._operands).toEqual(['1.000']);
        expect(fieldResult[9]._operator).toEqual('j');
        expect(fieldResult[9]._operands).toEqual(['0']);
        expect(fieldResult[10]._operator).toEqual('J');
        expect(fieldResult[10]._operands).toEqual(['0']);
        expect(fieldResult[11]._operator).toEqual('RG');
        expect(fieldResult[11]._operands).toEqual(['0.502', '0.502', '0.502']);
        expect(fieldResult[12]._operator).toEqual('re');
        expect(fieldResult[12]._operands).toEqual(['0.500', '-0.500', '155.000', '-19.000']);
        expect(fieldResult[13]._operator).toEqual('S');
        expect(fieldResult[13]._operands).toEqual([]);
        expect(fieldResult[14]._operator).toEqual('EMC');
        expect(fieldResult[14]._operands).toEqual([]);
        //check the contents and the apperance in the page three
        parsedPage = parsed.getPage(2);
        contents = parsedPage._pageDictionary.get('Contents');
        ref = contents[2];
        stream = parsedPage._crossReference._fetch(ref);
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        //Font check in page 2
        fontDictionary = parsedPage._pageDictionary.get('Resources').get('Font');
        HelveticaBoldRef = result[15]._operands[0];
        HelveticaBold = fontDictionary.get(HelveticaBoldRef.slice(1)).get('BaseFont');
        HelveticaRef = result[25]._operands[0];
        Helvetica = fontDictionary.get(HelveticaRef.slice(1)).get('BaseFont');
        //Content level check in page 2
        expect(HelveticaBold.name).toEqual('Helvetica-Bold');
        expect(Helvetica.name).toEqual('Helvetica');
        imageRef = result[9]._operands[0];
        xObject = parsedPage._pageDictionary.get('Resources').get('XObject');
        image = xObject.get(imageRef.slice(1));
        type = image.dictionary.get('Subtype')
        expect(type.name).toEqual('Image');
        checkCoverImage(result);
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '310.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['0.000', '0.000', '500.000', '-310.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '.00']);
        expect(result[7]._operator).toEqual('q');
        expect(result[7]._operands).toEqual([]);
        expect(result[8]._operator).toEqual('cm');
        expect(result[8]._operands).toEqual(['500.00', '.00', '.00', '310.00', '.00', '-310.00']);
        expect(result[9]._operator).toEqual('Do');
        expect(result[10]._operator).toEqual('Q');
        expect(result[10]._operands).toEqual([]);
        expect(result[11]._operator).toEqual('BT');
        expect(result[11]._operands).toEqual([]);
        expect(result[12]._operator).toEqual('CS');
        expect(result[12]._operands).toEqual(['/DeviceRGB']);
        expect(result[13]._operator).toEqual('cs');
        expect(result[13]._operands).toEqual(['/DeviceRGB']);
        expect(result[14]._operator).toEqual('rg');
        expect(result[14]._operands).toEqual(['0.835', '0.482', '0.075']);
        expect(result[15]._operator).toEqual('Tf');
        expect(result[15]._operands[1]).toEqual('12.000');
        expect(result[16]._operator).toEqual('Tr');
        expect(result[16]._operands).toEqual(['0']);
        expect(result[17]._operator).toEqual('Tc');
        expect(result[17]._operands).toEqual(['0.000']);
        expect(result[18]._operator).toEqual('Tw');
        expect(result[18]._operands).toEqual(['0.000']);
        expect(result[19]._operator).toEqual('Tz');
        expect(result[19]._operands).toEqual(['100.000']);
        expect(result[20]._operator).toEqual('Tm');
        expect(result[20]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-91.54']);
        expect(result[21]._operator).toEqual("'");
        expect(result[21]._operands).toEqual(['(Thank You)']);
        expect(result[22]._operator).toEqual('ET');
        expect(result[22]._operands).toEqual([]);
        expect(result[23]._operator).toEqual('BT');
        expect(result[23]._operands).toEqual([]);
        expect(result[24]._operator).toEqual('rg');
        expect(result[24]._operands).toEqual(['0.486', '0.561', '0.651']);
        expect(result[25]._operator).toEqual('Tf');
        expect(result[25]._operands[1]).toEqual('10.000');
        expect(result[26]._operator).toEqual('Tm');
        expect(result[26]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-119.31']);
        expect(result[27]._operator).toEqual("'");
        expect(result[27]._operands).toEqual(['(Thanks for taking the time to complete this form.)']);
        expect(result[28]._operator).toEqual('Tm');
        expect(result[28]._operands).toEqual(['1.00', '.00', '.00', '1.00', '25.00', '-130.87']);
        expect(result[29]._operator).toEqual("'");
        expect(result[29]._operands).toEqual(['(We will be in contact with you shortly.)']);
        expect(result[30]._operator).toEqual('ET');
        expect(result[30]._operands).toEqual([]);
        //annotations check for page 3
        annotations = parsedPage._pageDictionary.get('Annots');
        fieldResult = getAnnotationRecords(annotations[0], parsedPage);
        expect(fieldResult[0]._operator).toEqual('cm');
        expect(fieldResult[0]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '20.00']);
        expect(fieldResult[1]._operator).toEqual('CS');
        expect(fieldResult[1]._operands).toEqual(['/DeviceRGB']);
        expect(fieldResult[2]._operator).toEqual('cs');
        expect(fieldResult[2]._operands).toEqual(['/DeviceRGB']);
        expect(fieldResult[3]._operator).toEqual('rg');
        expect(fieldResult[3]._operands).toEqual(['0.710', '0.749', '0.796']);
        expect(fieldResult[4]._operator).toEqual('re');
        expect(fieldResult[4]._operands).toEqual(['0.000', '0.000', '100.000', '-20.000']);
        expect(fieldResult[5]._operator).toEqual('f');
        expect(fieldResult[5]._operands).toEqual([]);
        expect(fieldResult[6]._operator).toEqual('d');
        expect(fieldResult[6]._operands).toEqual(['[]', '0']);
        expect(fieldResult[7]._operator).toEqual('w');
        expect(fieldResult[7]._operands).toEqual(['1.000']);
        expect(fieldResult[8]._operator).toEqual('j');
        expect(fieldResult[8]._operands).toEqual(['0']);
        expect(fieldResult[9]._operator).toEqual('J');
        expect(fieldResult[9]._operands).toEqual(['0']);
        expect(fieldResult[10]._operator).toEqual('RG');
        expect(fieldResult[10]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(fieldResult[11]._operator).toEqual('re');
        expect(fieldResult[11]._operands).toEqual(['0.500', '-0.500', '99.000', '-19.000']);
        expect(fieldResult[12]._operator).toEqual('S');
        expect(fieldResult[12]._operands).toEqual([]);
        expect(fieldResult[13]._operator).toEqual('BT');
        expect(fieldResult[13]._operands).toEqual([]);
        expect(fieldResult[14]._operator).toEqual('rg');
        expect(fieldResult[14]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(fieldResult[15]._operator).toEqual('Tf');
        expect(fieldResult[15]._operands[1]).toEqual('10.000');
        expect(fieldResult[16]._operator).toEqual('Tr');
        expect(fieldResult[16]._operands).toEqual(['0']);
        expect(fieldResult[17]._operator).toEqual('Tc');
        expect(fieldResult[17]._operands).toEqual(['0.000']);
        expect(fieldResult[18]._operator).toEqual('Tw');
        expect(fieldResult[18]._operands).toEqual(['0.000']);
        expect(fieldResult[19]._operator).toEqual('Tz');
        expect(fieldResult[19]._operands).toEqual(['100.000']);
        expect(fieldResult[20]._operator).toEqual('Tm');
        expect(fieldResult[20]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '-13.53']);
        expect(fieldResult[21]._operator).toEqual('Td');
        expect(fieldResult[21]._operands).toEqual(['37.495', '0.000']);
        expect(fieldResult[22]._operator).toEqual("'");
        expect(fieldResult[22]._operands).toEqual(['(Apply)']);
        expect(fieldResult[23]._operator).toEqual('Td');
        expect(fieldResult[23]._operands).toEqual(['0.000', '-7.340']);
        expect(fieldResult[24]._operator).toEqual('ET');
        expect(fieldResult[24]._operands).toEqual([]);
        parsed.destroy();
    });
});
function getAnnotationRecords(ref: any, parsedPage: PdfPage): _PdfRecord[] {
    let annotation = parsedPage._crossReference._fetch(ref);
    let appearance = annotation.get('AP').get('N');
    let parser: _ContentParser = new _ContentParser(appearance.getBytes());
    return parser._readContent();
}
