import { DocumentEditor } from '../../../src/document-editor/document-editor';
import { DocumentHelper, DropDownFormField, EditorHistory, SfdtExport } from '../../../src/index';
import { createElement } from '@syncfusion/ej2-base';
import { TestHelper } from '../../test-helper.spec';
import { Editor } from '../../../src/index';
import { Selection } from '../../../src/index';
import { DropDownFormFieldDialog } from '../../../src/document-editor/implementation/dialogs/form-field-drop-down-dialog';

describe('Form field Dropdown dialog', () => {
    let editor: DocumentEditor;
    let dialog: DropDownFormFieldDialog;
    beforeAll((): void => {
        editor = undefined;
        let ele: HTMLElement = createElement('div', { id: 'container' });
        document.body.appendChild(ele);
        DocumentEditor.Inject(Editor, Selection, DropDownFormFieldDialog);
        editor = new DocumentEditor({ enableEditor: true, enableSelection: true, isReadOnly: false });
        (editor.documentHelper as any).containerCanvasIn = TestHelper.containerCanvas;
        (editor.documentHelper as any).selectionCanvasIn = TestHelper.selectionCanvas;
        (editor.documentHelper.render as any).pageCanvasIn = TestHelper.pageCanvas;
        (editor.documentHelper.render as any).selectionCanvasIn = TestHelper.pageSelectionCanvas;
        editor.appendTo('#container');
        dialog = editor.dropDownFormFieldDialogModule;
        dialog.show();
        dialog.onCancelButtonClick();
    });
    beforeEach(() => {
        editor.openBlank();
    });
    afterAll((done) => {
        editor.destroy();
        document.body.removeChild(document.getElementById('container'));
        editor = undefined;
        document.body.innerHTML = '';
        setTimeout(function () {
            done();
        }, 2000);
    });
    it('Insert Form field Dropdown value updates', () => {
console.log('Insert Form field Dropdown value updates');
        editor.editorModule.insertFormField('DropDown');
        let arrValue: string[] = ['Sync', 'Syncfusion'];
        (dialog as any).dropDownItems = arrValue;
        (dialog as any).bookmarkInput.value = 'Test';
        (dialog as any).dropDownEnable.checked = false;
        (dialog as any).tooltipInput.value = 'testsync';
        editor.selection.selectAll();
        dialog.insertDropDownField();
        editor.selection.selectAll();
        let fieldData: DropDownFormField = editor.selection.getCurrentFormField().formFieldData as DropDownFormField;
        expect(fieldData.dropdownItems[0]).toBe('Sync');
        expect(fieldData.dropdownItems[1]).toBe('Syncfusion');
        expect(fieldData.name).toBe('Test');
        expect(fieldData.enabled).toBe(false);
        expect(fieldData.helpText).toBe('testsync');
    });
    it('Load Values - Form field Dropdown Dialog', () => {
console.log('Load Values - Form field Dropdown Dialog');
        editor.editorModule.insertFormField('DropDown');
        editor.selection.selectAll();
        dialog.loadDropDownDialog();
        editor.selection.selectAll();
        let fieldData: DropDownFormField = editor.selection.getCurrentFormField().formFieldData as DropDownFormField;
        expect(fieldData.dropdownItems.length).toBe(0);
        expect(fieldData.helpText).toBe((dialog as any).tooltipInput.value);
        expect(fieldData.name).toBe((dialog as any).bookmarkInput.value);
        expect(fieldData.enabled).toBe((dialog as any).dropDownEnable.checked);
    });
    it('add items - Form field Dropdown Dialog', () => {
console.log('add items - Form field Dropdown Dialog');
        editor.editorModule.insertFormField('DropDown');
        editor.selection.selectAll();
        (dialog as any).drpDownItemsInput.value = 'Sync';
        dialog.addItemtoList();
        expect((dialog as any).dropDownItems[0]).toBe('Sync');
    });
    it('remove items - Form field Dropdown Dialog', () => {
console.log('remove items - Form field Dropdown Dialog');
        editor.editorModule.insertFormField('DropDown');
        editor.selection.selectAll();
        (dialog as any).dropDownItems = [];
        (dialog as any).drpDownItemsInput.value = 'Sync';
        dialog.addItemtoList();
        dialog.removeItemFromList();
        expect((dialog as any).dropDownItems.length).toBe(0);
    });
    it('move Up items - Form field Dropdown Dialog', () => {
console.log('move Up items - Form field Dropdown Dialog');
        editor.editorModule.insertFormField('DropDown');
        editor.selection.selectAll();
        (dialog as any).dropDownItems = [];
        (dialog as any).drpDownItemsInput.value = 'Test1';
        dialog.addItemtoList();
        (dialog as any).drpDownItemsInput.value = 'Test2';
        dialog.addItemtoList();
        (dialog as any).drpDownItemsInput.value = 'Test3';
        dialog.addItemtoList();
        dialog.moveUpItem();
        expect((dialog as any).dropDownItems[1]).toBe('Test3');
        expect((dialog as any).dropDownItems[2]).toBe('Test2');
        dialog.moveUpItem();
        dialog.moveUpItem();
        expect((dialog as any).dropDownItems[2]).toBe('Test3');
    });
    it('move Down items - Form field Dropdown Dialog', () => {
console.log('move Down items - Form field Dropdown Dialog');
        editor.editorModule.insertFormField('DropDown');
        editor.selection.selectAll();
        (dialog as any).dropDownItems = [];
        (dialog as any).drpDownItemsInput.value = 'Test1';
        dialog.addItemtoList();
        (dialog as any).drpDownItemsInput.value = 'Test2';
        dialog.addItemtoList();
        (dialog as any).drpDownItemsInput.value = 'Test3';
        dialog.addItemtoList();
        dialog.moveDownItem();
        expect((dialog as any).dropDownItems[0]).toBe('Test3');
        expect((dialog as any).dropDownItems[1]).toBe('Test1');
        dialog.moveDownItem();
        expect((dialog as any).dropDownItems[1]).toBe('Test3');
    });
    it('Key up input- enable disable add button - Form field Dropdown Dialog', () => {
console.log('Key up input- enable disable add button - Form field Dropdown Dialog');
        editor.editorModule.insertFormField('DropDown');
        editor.selection.selectAll();
        (dialog as any).dropDownItems = [];
        (dialog as any).addButton.disabled = true;
        (dialog as any).drpDownItemsInput.value = 'Sync';
        dialog.onKeyUpOnTextBox();
        expect((dialog as any).addButton.disabled).toBe(false);
    });
});
describe('Check API to modify DropDown form field name in Inline mode', () => {
    let container: DocumentEditor;
    beforeAll(() => {
        document.body.innerHTML = '';
        let ele: HTMLElement = createElement('div', { id: 'container' });
        document.body.appendChild(ele);
        DocumentEditor.Inject(Editor, Selection, EditorHistory, SfdtExport);
        container = new DocumentEditor({ enableEditor: true, isReadOnly: false, enableEditorHistory: true, enableSfdtExport: true });
        (container.documentHelper as any).containerCanvasIn = TestHelper.containerCanvas;
        (container.documentHelper as any).selectionCanvasIn = TestHelper.selectionCanvas;
        (container.documentHelper.render as any).pageCanvasIn = TestHelper.pageCanvas;
        (container.documentHelper.render as any).selectionCanvasIn = TestHelper.pageSelectionCanvas;
        container.appendTo('#container');
    });
    afterAll((done): void => {
        container.destroy();
        document.body.removeChild(document.getElementById('container'));
        container = undefined;
        document.body.innerHTML = '';
        setTimeout(function () {
            done();
        }, 1000);
    });
    it('Check the number of form fields', () => {
        console.log('Check the number of form fields');
        container.openBlank();
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.enforceProtection('123', 'FormFieldsOnly');
        container.documentEditorSettings.formFieldSettings.formFillingMode = 'Inline';
        let formFieldNames1: any = container.getFormFieldNames();
        expect(formFieldNames1.length).toEqual(3);
        let field: any = container.getFormFieldInfo(formFieldNames1[1]);
        field.name = 'DropDown3';
        container.setFormFieldInfo(formFieldNames1[1], field);
        let formFieldNames2: any = container.getFormFieldNames();
        expect(formFieldNames2.length).toEqual(2);
        container.editor.stopProtection('123');
    });
    it('Check the names of Form Fields', () => {
        console.log('Check the names of form fields');
        container.openBlank();
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.enforceProtection('123', 'FormFieldsOnly');
        container.documentEditorSettings.formFieldSettings.formFillingMode = 'Inline';
        let formFieldNames1: any = container.getFormFieldNames();
        expect(formFieldNames1[0]).toEqual('DropDown1');
        expect(formFieldNames1[1]).toEqual('DropDown2');
        expect(formFieldNames1[2]).toEqual('DropDown3');
        let field: any = container.getFormFieldInfo(formFieldNames1[1]);
        field.name = 'DropDown3';
        container.setFormFieldInfo(formFieldNames1[1], field);
        let formFieldNames2: any = container.getFormFieldNames();
        expect(formFieldNames2[0]).toEqual('DropDown1');
        expect(formFieldNames2[1]).toEqual('DropDown3');
        container.editor.stopProtection('123');
    });
    it('Modifying form fields without modifying name', () => {
        console.log('modifying Form Field without changing name');
        container.openBlank();
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.enforceProtection('123', 'FormFieldsOnly');
        container.documentEditorSettings.formFieldSettings.formFillingMode = 'Inline';
        let formFieldNames1: any = container.getFormFieldNames();
        let field: any = container.getFormFieldInfo(formFieldNames1[1]);
        field.dropDownItems = ['One', 'Two', 'Three']
        field.type = "DropDown";
        container.setFormFieldInfo(formFieldNames1[1], field);
        let formFieldNames2: any = container.getFormFieldNames();
        expect(formFieldNames2.length).toEqual(3);
        container.editor.stopProtection('123');
    });
    it('Check new name for form fields', () => {
        console.log('Check unique name for form fields');
        container.openBlank();
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.enforceProtection('123', 'FormFieldsOnly');
        container.documentEditorSettings.formFieldSettings.formFillingMode = 'Inline';
        let formFieldNames1: any = container.getFormFieldNames();
        let field1: any = container.getFormFieldInfo(formFieldNames1[1]);
        field1.name = 'NewFormFieldName';
        container.setFormFieldInfo(formFieldNames1[1], field1);
        let field2: any = container.getFormFieldInfo("NewFormFieldName");
        let formFieldNames2: any = container.getFormFieldNames();
        expect(formFieldNames2).toContain("NewFormFieldName");
        expect(field2.name).toBeDefined();
        container.editor.stopProtection('123');
    });
});
describe('Check API to modify DropDown form field name in popup mode', () => {
    let container: DocumentEditor;
    beforeAll(() => {
        document.body.innerHTML = '';
        let ele: HTMLElement = createElement('div', { id: 'container' });
        document.body.appendChild(ele);
        DocumentEditor.Inject(Editor, Selection, EditorHistory, SfdtExport);
        container = new DocumentEditor({ enableEditor: true, isReadOnly: false, enableEditorHistory: true, enableSfdtExport: true });
        (container.documentHelper as any).containerCanvasIn = TestHelper.containerCanvas;
        (container.documentHelper as any).selectionCanvasIn = TestHelper.selectionCanvas;
        (container.documentHelper.render as any).pageCanvasIn = TestHelper.pageCanvas;
        (container.documentHelper.render as any).selectionCanvasIn = TestHelper.pageSelectionCanvas;
        container.appendTo('#container');
    });
    afterAll((done): void => {
        container.destroy();
        document.body.removeChild(document.getElementById('container'));
        container = undefined;
        document.body.innerHTML = '';
        setTimeout(function () {
            done();
        }, 1000);
    });
    it('Check the number of form fields', () => {
        console.log('Check the number of form fields');
        container.openBlank();
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.enforceProtection('123', 'FormFieldsOnly');
        let formFieldNames1: any = container.getFormFieldNames();
        expect(formFieldNames1.length).toEqual(3);
        let field: any = container.getFormFieldInfo(formFieldNames1[1]);
        field.name = 'DropDown3';
        container.setFormFieldInfo(formFieldNames1[1], field);
        let formFieldNames2: any = container.getFormFieldNames();
        expect(formFieldNames2.length).toEqual(2);
        container.editor.stopProtection('123');
    });
    it('Check the names of Form Fields', () => {
        console.log('Check the names of form fields');
        container.openBlank();
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        let formFieldNames1: any = container.getFormFieldNames();
        expect(formFieldNames1[0]).toEqual('DropDown1');
        expect(formFieldNames1[1]).toEqual('DropDown2');
        expect(formFieldNames1[2]).toEqual('DropDown3');
        container.editor.enforceProtection('123', 'FormFieldsOnly');
        let field: any = container.getFormFieldInfo(formFieldNames1[1]);
        field.name = 'DropDown3';
        container.setFormFieldInfo(formFieldNames1[1], field);
        let formFieldNames2: any = container.getFormFieldNames();
        expect(formFieldNames2[0]).toEqual('DropDown1');
        expect(formFieldNames2[1]).toEqual('DropDown3');
        container.editor.stopProtection('123');
    });
    it('Modifying form fields without modifying name', () => {
        console.log('modifying Form Field without changing name');
        container.openBlank();
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.enforceProtection('123', 'FormFieldsOnly');
        let formFieldNames1: any = container.getFormFieldNames();
        let field: any = container.getFormFieldInfo(formFieldNames1[1]);
        field.dropDownItems = ['One', 'Two', 'Three']
        field.type = "DropDown";
        container.setFormFieldInfo(formFieldNames1[1], field);
        let formFieldNames2: any = container.getFormFieldNames();
        expect(formFieldNames2.length).toEqual(3);
        container.editor.stopProtection('123');
    });
    it('Check new name for form fields', () => {
        console.log('Check unique name for form fields');
        container.openBlank();
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.insertFormField('DropDown');
        container.editor.enforceProtection('123', 'FormFieldsOnly');
        let formFieldNames1: any = container.getFormFieldNames();
        let field1: any = container.getFormFieldInfo(formFieldNames1[1]);
        field1.name = 'NewFormFieldName';
        container.setFormFieldInfo(formFieldNames1[1], field1);
        let field2: any = container.getFormFieldInfo("NewFormFieldName");
        let formFieldNames2: any = container.getFormFieldNames();
        expect(formFieldNames2).toContain("NewFormFieldName");
        expect(field2.name).toBeDefined();
        container.editor.stopProtection('123');
    });
});