//tslint:disable
export let CarSales: object[] = [
    {Continent: "China", Company: "Volkswagen", Sales: 3005994 },
    {Continent: "China", Company: "General Motors", Sales: 1230044 },
    {Continent: "China", Company: "Honda", Sales: 1197023 },
    {Continent: "United States", Company: "General Motors", Sales:3042775  },
    {Continent: "United States", Company: "Ford", Sales:2599193  },
    {Continent: "United States", Company: "Toyota", Sales:2449587  },
    {Continent: "Japan",Company: "Toyota", Sales:1527977  },
    {Continent: "Japan", Company: "Honda", Sales:706982 },
    {Continent: "Japan", Company: "Suzuki", Sales:623041  },
    {Continent: "Germany",Company: "Volkswagen", Sales:655977  },
    {Continent: "Germany", Company: "Mercedes", Sales:310845  },
    {Continent: "Germany", Company: "BMW", Sales:261931  },
    { Continent: "United Kingdom", Company: "Ford ", Sales:319442  },
	{Continent: "United Kingdom", Company: "Vauxhall", Sales: 251146 },
    { Continent: "United Kingdom", Company: "Volkswagen", Sales:206994  },
    {Continent: "India", Company: "Maruti Suzuki", Sales:1443654  },
     {Continent: "India", Company: "Hyundai", Sales:476241  },
    {Continent: "India", Company: "Mahindra", Sales:205041  },
    {Continent: "France", Company: "Renault", Sales:408183 },
    {Continent: "France", Company: "Peugeot", Sales:336242 },
    {Continent: "France", Company: "Citroen", Sales:194986  },
    { Continent: "Brazil", Company: "Flat Chrysler", Sales:368842  },
    { Continent: "Brazil", Company: "General Motors", Sales: 348351 },
    { Continent: "Brazil", Company: "Volkswagen", Sales: 245895 },
    {Continent: "Italy", Company: "Flat Chrysler", Sales:386260  },
    {Continent: "Italy", Company: "Volkswagen", Sales: 138984 },
    {Continent: "Italy", Company: "Ford", Sales: 125144 },
    {Continent: "Canada", Company: "Ford", Sales:305086},
    {Continent: "Canada", Company: "FCA", Sales:278011 },
    {Continent: "Canada", Company: "GM", Sales: 266884 },
       

]