import { _PdfContentStream } from '../../src/pdf/core/base-stream';
import { _ContentParser, _PdfRecord } from '../../src/pdf/core/content-parser';
import { PdfPageOrientation, PdfRotationAngle } from '../../src/pdf/core/enumerator';
import { PdfPen } from '../../src/pdf/core/graphics/pdf-graphics';
import { PdfDocumentInformation } from '../../src/pdf/core/pdf-document-information';
import { PdfPage } from '../../src/pdf/core/pdf-page';
import { PdfSection } from '../../src/pdf/core/pdf-section';
import { PdfDocument, PdfMargins, PdfPageSettings } from '../../src/pdf/core/pdf-document';
describe('PdfDocument Creation Section And PageSettings Test - 3', () => {
    it('multple doc page, multiple section, single _ multiple pages', () => {
        let document: PdfDocument = new PdfDocument();
        let page: PdfPage = document.addPage();
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(1);
        page = document.addPage();
        expect(document.pageCount).toEqual(2);
        let section: PdfSection = document.addSection();
        page = section.addPage();
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(3);
        page = section.addPage();
        expect(document.pageCount).toEqual(4);
        page = document.addPage();
        expect(document.pageCount).toEqual(5);
        page = document.addPage();
        expect(document.pageCount).toEqual(6);
        section = document.addSection();
        page = section.addPage();
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(7);
        page = section.addPage();
        expect(document.pageCount).toEqual(8);
        page = document.addPage();
        expect(document.pageCount).toEqual(9);
        page = document.addPage();
        expect(document.pageCount).toEqual(10);
        section = document.addSection();
        page = section.addPage();
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(11);
        page = document.addPage();
        page.graphics.drawRectangle({ x: 0, y: 0, width: page.graphics.clientSize.width, height: page.graphics.clientSize.height }, new PdfPen({ r: 0, g: 0, b: 0 }, 1));
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream._bytes);
        let result: _PdfRecord[] = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['40.000', '-40.000', '515.000', '-762.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '40.00', '-40.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '515.000', '-762.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        expect(document.pageCount).toEqual(12);
        let updatedData = document.save();
        document.destroy();
        document = new PdfDocument(updatedData);
        expect(document.pageCount).toEqual(12);
        page = document.getPage(0);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        page = document.getPage(11);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['40.000', '-40.000', '515.000', '-762.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00','.00', '1.00', '40.00', '-40.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '515.000', '-762.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        document.destroy();
    });
    it('multple doc page, multiple section, single _ multiple pages, 2', () => {
        let document: PdfDocument = new PdfDocument();
        expect(document.pageCount).toEqual(0);
        let page: PdfPage = document.addPage();
        page = document.addPage();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.margins = new PdfMargins(10);
        let section: PdfSection = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = document.addPage(settings);
        expect(settings.orientation).toEqual(PdfPageOrientation.portrait);
        expect(settings.size).toEqual({ width: 595, height: 842 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle0);
        let margin = settings.margins;
        expect(margin.left).toEqual(10);
        expect(margin.right).toEqual(10);
        expect(margin.top).toEqual(10);
        expect(margin.bottom).toEqual(10);
        expect(document.pageCount).toEqual(13);
        page.graphics.drawRectangle({ x: 0, y: 0, width: page.graphics.clientSize.width, height: page.graphics.clientSize.height }, new PdfPen({ r: 0, g: 0, b: 0 }, 1));
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream._bytes);
        let result: _PdfRecord[] = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['10.000', '-10.000', '575.000', '-822.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '10.00', '-10.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '575.000', '-822.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        let updatedData = document.save();
        document.destroy();
        document = new PdfDocument(updatedData);
        page = document.getPage(document.pageCount - 1);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(13);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['10.000', '-10.000', '575.000', '-822.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '10.00', '-10.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '575.000', '-822.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        document.destroy();
    });
    it('multple doc page, multiple section, single _ multiple pages, 3', () => {
        let document: PdfDocument = new PdfDocument();
        expect(document.pageCount).toEqual(0);
        let page: PdfPage = document.addPage();
        page = document.addPage();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.margins = new PdfMargins(20);
        let section: PdfSection = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = document.addPage(settings);
        expect(settings.orientation).toEqual(PdfPageOrientation.portrait);
        expect(settings.size).toEqual({ width: 595, height: 842 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle0);
        let margin = settings.margins;
        expect(margin.left).toEqual(20);
        expect(margin.right).toEqual(20);
        expect(margin.top).toEqual(20);
        expect(margin.bottom).toEqual(20);
        expect(document.pageCount).toEqual(13);
        page.graphics.drawRectangle({ x: 0, y: 0, width: page.graphics.clientSize.width, height: page.graphics.clientSize.height }, new PdfPen({ r: 0, g: 0, b: 0 }, 1));
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream._bytes);
        let result: _PdfRecord[] = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['20.000', '-20.000', '555.000', '-802.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '20.00', '-20.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '555.000', '-802.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        let updatedData = document.save();
        document.destroy();
        document = new PdfDocument(updatedData);
        page = document.getPage(document.pageCount - 1);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(13);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['20.000', '-20.000', '555.000', '-802.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '20.00', '-20.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0'])
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000'])
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '555.000', '-802.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        document.destroy();
    });
    it('multple doc page, multiple section, single _ multiple pages, 4', () => {
        let document: PdfDocument = new PdfDocument();
        expect(document.pageCount).toEqual(0);
        let page: PdfPage = document.addPage();
        page = document.addPage();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.margins = new PdfMargins(30);
        let section: PdfSection = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = document.addPage(settings);
        expect(settings.orientation).toEqual(PdfPageOrientation.portrait);
        expect(settings.size).toEqual({ width: 595, height: 842 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle0);
        let margin = settings.margins;
        expect(margin.left).toEqual(30);
        expect(margin.right).toEqual(30);
        expect(margin.top).toEqual(30);
        expect(margin.bottom).toEqual(30);
        expect(document.pageCount).toEqual(13);
        page.graphics.drawRectangle({ x: 0, y: 0, width: page.graphics.clientSize.width, height: page.graphics.clientSize.height }, new PdfPen({ r: 0, g: 0, b: 0 }, 1));
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream._bytes);
        let result: _PdfRecord[] = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['30.000', '-30.000', '535.000', '-782.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '30.00', '-30.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '535.000', '-782.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        let updatedData = document.save();
        document.destroy();
        document = new PdfDocument(updatedData);
        page = document.getPage(document.pageCount - 1);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(13);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['30.000', '-30.000', '535.000', '-782.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '30.00', '-30.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '535.000', '-782.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        document.destroy();
    });
    it('multple doc page, multiple section, single _ multiple pages, 5', () => {
        let document: PdfDocument = new PdfDocument();
        expect(document.pageCount).toEqual(0);
        let page: PdfPage = document.addPage();
        page = document.addPage();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.rotation = PdfRotationAngle.angle90;
        let section: PdfSection = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = document.addPage(settings);
        expect(settings.orientation).toEqual(PdfPageOrientation.portrait);
        expect(settings.size).toEqual({ width: 595, height: 842 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle90);
        expect(document.pageCount).toEqual(13);
        let updatedData = document.save();
        document.destroy();
        document = new PdfDocument(updatedData);
        page = document.getPage(document.pageCount - 1);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle90);
        expect(document.pageCount).toEqual(13);
        document.destroy();
    });
    it('multple doc page, multiple section, single _ multiple pages, 6', () => {
        let document: PdfDocument = new PdfDocument();
        expect(document.pageCount).toEqual(0);
        let page: PdfPage = document.addPage();
        page = document.addPage();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.rotation = PdfRotationAngle.angle180;
        let section: PdfSection = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = document.addPage(settings);
        expect(settings.orientation).toEqual(PdfPageOrientation.portrait);
        expect(settings.size).toEqual({ width: 595, height: 842 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle180);
        expect(document.pageCount).toEqual(13);
        let updatedData = document.save();
        document.destroy();
        document = new PdfDocument(updatedData);
        page = document.getPage(document.pageCount - 1);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle180);
        expect(document.pageCount).toEqual(13);
        document.destroy();
    });
    it('multple doc page, multiple section, single _ multiple pages, 7', () => {
        let document: PdfDocument = new PdfDocument();
        expect(document.pageCount).toEqual(0);
        let page: PdfPage = document.addPage();
        page = document.addPage();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.rotation = PdfRotationAngle.angle270;
        let section: PdfSection = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = document.addPage(settings);
        expect(settings.orientation).toEqual(PdfPageOrientation.portrait);
        expect(settings.size).toEqual({ width: 595, height: 842 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle270);
        expect(document.pageCount).toEqual(13);
        let updatedData = document.save();
        document.destroy();
        document = new PdfDocument(updatedData);
        page = document.getPage(document.pageCount - 1);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle270);
        expect(document.pageCount).toEqual(13);
        document.destroy();
    });
    it('multple doc page, multiple section, single _ multiple pages, 8', () => {
        let document: PdfDocument = new PdfDocument();
        expect(document.pageCount).toEqual(0);
        let page: PdfPage = document.addPage();
        page = document.addPage();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.orientation = PdfPageOrientation.landscape;
        let section: PdfSection = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = document.addPage(settings);
        expect(settings.orientation).toEqual(PdfPageOrientation.landscape);
        expect(settings.size).toEqual({ width: 842, height: 595 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(13);
        let updatedData = document.save();
        document.destroy();
        document = new PdfDocument(updatedData);
        page = document.getPage(document.pageCount - 1);
        expect(page.orientation).toEqual(PdfPageOrientation.landscape);
        expect(page.size).toEqual({ width: 842, height: 595 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(13);
        document.destroy();
    });
    it('multple doc page, multiple section, single _ multiple pages, 9', () => {
        let document: PdfDocument = new PdfDocument();
        expect(document.pageCount).toEqual(0);
        let page: PdfPage = document.addPage();
        page = document.addPage();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.size = { width: 500, height: 400 };
        let section: PdfSection = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = document.addPage(settings);
        expect(settings.orientation).toEqual(PdfPageOrientation.landscape);
        expect(settings.size).toEqual({ width: 500, height: 400 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(13);
        let updatedData = document.save();
        document.destroy();
        document = new PdfDocument(updatedData);
        page = document.getPage(document.pageCount - 1);
        expect(page.orientation).toEqual(PdfPageOrientation.landscape);
        expect(page.size).toEqual({ width: 500, height: 400 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(13);
        document.destroy();
    });
    it('multple doc page, multiple section, single _ multiple pages, 10', () => {
        let document: PdfDocument = new PdfDocument();
        expect(document.pageCount).toEqual(0);
        let page: PdfPage = document.addPage();
        page = document.addPage();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.size = { width: 500, height: 400 };
        settings.orientation = PdfPageOrientation.landscape;
        settings.rotation = PdfRotationAngle.angle90;
        let section: PdfSection = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = section.addPage();
        page = document.addPage();
        page = document.addPage();
        section = document.addSection(settings);
        page = section.addPage();
        page = document.addPage(settings);
        expect(settings.orientation).toEqual(PdfPageOrientation.landscape);
        expect(settings.size).toEqual({ width: 500, height: 400 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle90);
        expect(document.pageCount).toEqual(13);
        let updatedData = document.save();
        document.destroy();
        document = new PdfDocument(updatedData);
        page = document.getPage(document.pageCount - 1);
        expect(page.orientation).toEqual(PdfPageOrientation.landscape);
        expect(page.size).toEqual({ width: 500, height: 400 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle90);
        expect(document.pageCount).toEqual(13);
        document.destroy();
    });
    it('cross reference table - section with no page, document with single page and add page to section', () => {
        let document: PdfDocument = new PdfDocument();
        let section: PdfSection = document.addSection();
        expect(section).toBeDefined();
        let page: PdfPage = document.addPage();
        expect(document.pageCount).toEqual(1);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        page = section.addPage();
        expect(document.pageCount).toEqual(2);
        let data = document.save();
        expect(data.length > 0).toBeTruthy();
        document.destroy();
        document = new PdfDocument(data);
        expect(document.pageCount).toEqual(2);
        document.destroy();
    });
    it('cross reference table - section with no page, document with single page and add page to section 2', () => {
        let document: PdfDocument = new PdfDocument();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.margins = new PdfMargins(10);
        let section: PdfSection = document.addSection(settings);
        expect(section).toBeDefined();
        let page: PdfPage = document.addPage();
        expect(document.pageCount).toEqual(1);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        page = section.addPage();
        page.graphics.drawRectangle({ x: 0, y: 0, width: page.graphics.clientSize.width, height: page.graphics.clientSize.height }, new PdfPen({ r: 0, g: 0, b: 0 }, 1));
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream._bytes);
        let result: _PdfRecord[] = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['10.000', '-10.000', '575.000', '-822.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '10.00', '-10.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '575.000', '-822.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        expect(document.pageCount).toEqual(2);
        let data = document.save();
        expect(data.length > 0).toBeTruthy();
        document.destroy();
        document = new PdfDocument(data);
        page = document.getPage(0);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(2);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['10.000', '-10.000', '575.000', '-822.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '10.00', '-10.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '575.000', '-822.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        document.destroy();
    });
    it('cross reference table - section with no page, document with single page and add page to section 3', () => {
        let document: PdfDocument = new PdfDocument();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.margins = new PdfMargins(20);
        let section: PdfSection = document.addSection(settings);
        expect(section).toBeDefined();
        let page: PdfPage = document.addPage();
        expect(document.pageCount).toEqual(1);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        page = section.addPage();
        page.graphics.drawRectangle({ x: 0, y: 0, width: page.graphics.clientSize.width, height: page.graphics.clientSize.height }, new PdfPen({ r: 0, g: 0, b: 0 }, 1));
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream._bytes);
        let result: _PdfRecord[] = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['20.000', '-20.000', '555.000', '-802.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '20.00', '-20.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '555.000', '-802.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        expect(document.pageCount).toEqual(2);
        let data = document.save();
        expect(data.length > 0).toBeTruthy();
        document.destroy();
        document = new PdfDocument(data);
        page = document.getPage(0);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(2);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['20.000', '-20.000', '555.000', '-802.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '20.00', '-20.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '555.000', '-802.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        document.destroy();
    });
    it('cross reference table - section with no page, document with single page and add page to section 4', () => {
        let document: PdfDocument = new PdfDocument();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.margins = new PdfMargins(30);
        let section: PdfSection = document.addSection(settings);
        expect(section).toBeDefined();
        let page: PdfPage = document.addPage();
        expect(document.pageCount).toEqual(1);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        page = section.addPage();
        page.graphics.drawRectangle({ x: 0, y: 0, width: page.graphics.clientSize.width, height: page.graphics.clientSize.height }, new PdfPen({ r: 0, g: 0, b: 0 }, 1));
        let appearance: any = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        let stream: _PdfContentStream = appearance[2];
        let parser: _ContentParser = new _ContentParser(stream._bytes);
        let result: _PdfRecord[] = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['30.000', '-30.000', '535.000', '-782.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '30.00', '-30.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '535.000', '-782.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        expect(document.pageCount).toEqual(2);
        let data = document.save();
        expect(data.length > 0).toBeTruthy();
        document.destroy();
        document = new PdfDocument(data);
        page = document.getPage(0);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(2);
        appearance = page._pageDictionary.getArray('Contents');
        expect(appearance).not.toBeUndefined();
        stream = appearance[2];
        parser = new _ContentParser(stream.getBytes());
        result = parser._readContent();
        expect(result[0]._operator).toEqual('q');
        expect(result[0]._operands).toEqual([]);
        expect(result[1]._operator).toEqual('cm');
        expect(result[1]._operands).toEqual(['1.00', '.00', '.00', '1.00', '.00', '842.00']);
        expect(result[2]._operator).toEqual('re');
        expect(result[2]._operands).toEqual(['30.000', '-30.000', '535.000', '-782.000']);
        expect(result[3]._operator).toEqual('h');
        expect(result[3]._operands).toEqual([]);
        expect(result[4]._operator).toEqual('W');
        expect(result[4]._operands).toEqual([]);
        expect(result[5]._operator).toEqual('n');
        expect(result[5]._operands).toEqual([]);
        expect(result[6]._operator).toEqual('cm');
        expect(result[6]._operands).toEqual(['1.00', '.00', '.00', '1.00', '30.00', '-30.00']);
        expect(result[7]._operator).toEqual('CS');
        expect(result[7]._operands).toEqual(['/DeviceRGB']);
        expect(result[8]._operator).toEqual('cs');
        expect(result[8]._operands).toEqual(['/DeviceRGB']);
        expect(result[9]._operator).toEqual('d');
        expect(result[9]._operands).toEqual(['[]', '0']);
        expect(result[10]._operator).toEqual('w');
        expect(result[10]._operands).toEqual(['1.000']);
        expect(result[11]._operator).toEqual('j');
        expect(result[11]._operands).toEqual(['0']);
        expect(result[12]._operator).toEqual('J');
        expect(result[12]._operands).toEqual(['0']);
        expect(result[13]._operator).toEqual('RG');
        expect(result[13]._operands).toEqual(['0.000', '0.000', '0.000']);
        expect(result[14]._operator).toEqual('re');
        expect(result[14]._operands).toEqual(['0.000', '0.000', '535.000', '-782.000']);
        expect(result[15]._operator).toEqual('S');
        expect(result[15]._operands).toEqual([]);
        document.destroy();
    });
    it('cross reference table - section with no page, document with single page and add page to section 5', () => {
        let document: PdfDocument = new PdfDocument();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.rotation = PdfRotationAngle.angle90;
        let section: PdfSection = document.addSection(settings);
        expect(section).toBeDefined();
        let page: PdfPage = document.addPage();
        expect(document.pageCount).toEqual(1);
        expect(settings.orientation).toEqual(PdfPageOrientation.portrait);
        expect(settings.size).toEqual({ width: 595, height: 842 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle90);
        page = section.addPage();
        expect(document.pageCount).toEqual(2);
        let data = document.save();
        expect(data.length > 0).toBeTruthy();
        document.destroy();
        document = new PdfDocument(data);
        page = document.getPage(0);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle90);
        expect(document.pageCount).toEqual(2);
        document.destroy();
    });
    it('cross reference table - section with no page, document with single page and add page to section 6', () => {
        let document: PdfDocument = new PdfDocument();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.rotation = PdfRotationAngle.angle180;
        let section: PdfSection = document.addSection(settings);
        expect(section).toBeDefined();
        let page: PdfPage = document.addPage();
        expect(document.pageCount).toEqual(1);
        expect(settings.orientation).toEqual(PdfPageOrientation.portrait);
        expect(settings.size).toEqual({ width: 595, height: 842 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle180);
        page = section.addPage();
        expect(document.pageCount).toEqual(2);
        let data = document.save();
        expect(data.length > 0).toBeTruthy();
        document.destroy();
        document = new PdfDocument(data);
        page = document.getPage(0);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle180);
        expect(document.pageCount).toEqual(2);
        document.destroy();
    });
    it('cross reference table - section with no page, document with single page and add page to section 7', () => {
        let document: PdfDocument = new PdfDocument();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.rotation = PdfRotationAngle.angle270;
        let section: PdfSection = document.addSection(settings);
        expect(section).toBeDefined();
        let page: PdfPage = document.addPage();
        expect(document.pageCount).toEqual(1);
        expect(settings.orientation).toEqual(PdfPageOrientation.portrait);
        expect(settings.size).toEqual({ width: 595, height: 842 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle270);
        page = section.addPage();
        expect(document.pageCount).toEqual(2);
        let data = document.save();
        expect(data.length > 0).toBeTruthy();
        document.destroy();
        document = new PdfDocument(data);
        page = document.getPage(0);
        expect(page.orientation).toEqual(PdfPageOrientation.portrait);
        expect(page.size).toEqual({ width: 595, height: 842 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle270);
        expect(document.pageCount).toEqual(2);
        document.destroy();
    });
    it('cross reference table - section with no page, document with single page and add page to section 8', () => {
        let document: PdfDocument = new PdfDocument();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.orientation = PdfPageOrientation.landscape;
        let section: PdfSection = document.addSection(settings);
        expect(section).toBeDefined();
        let page: PdfPage = document.addPage();
        expect(document.pageCount).toEqual(1);
        expect(settings.orientation).toEqual(PdfPageOrientation.landscape);
        expect(settings.size).toEqual({ width: 842, height: 595 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle0);
        page = section.addPage();
        expect(document.pageCount).toEqual(2);
        let data = document.save();
        expect(data.length > 0).toBeTruthy();
        document.destroy();
        document = new PdfDocument(data);
        page = document.getPage(0);
        expect(page.orientation).toEqual(PdfPageOrientation.landscape);
        expect(page.size).toEqual({ width: 842, height: 595 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(2);
        document.destroy();
    });
    it('cross reference table - section with no page, document with single page and add page to section 9', () => {
        let document: PdfDocument = new PdfDocument();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.size = { width: 500, height: 400 };
        let section: PdfSection = document.addSection(settings);
        expect(section).toBeDefined();
        let page: PdfPage = document.addPage();
        expect(document.pageCount).toEqual(1);
        expect(settings.orientation).toEqual(PdfPageOrientation.landscape);
        expect(settings.size).toEqual({ width: 500, height: 400 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle0);
        page = section.addPage();
        expect(document.pageCount).toEqual(2);
        let data = document.save();
        expect(data.length > 0).toBeTruthy();
        document.destroy();
        document = new PdfDocument(data);
        page = document.getPage(0);
        expect(page.orientation).toEqual(PdfPageOrientation.landscape);
        expect(page.size).toEqual({ width: 500, height: 400 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle0);
        expect(document.pageCount).toEqual(2);
        document.destroy();
    });
    it('cross reference table - section with no page, document with single page and add page to section 910', () => {
        let document: PdfDocument = new PdfDocument();
        let settings: PdfPageSettings = new PdfPageSettings();
        settings.size = { width: 500, height: 400 };
        settings.orientation = PdfPageOrientation.landscape;
        settings.rotation = PdfRotationAngle.angle90;
        let section: PdfSection = document.addSection(settings);
        expect(section).toBeDefined();
        let page: PdfPage = document.addPage();
        expect(document.pageCount).toEqual(1);
        expect(settings.orientation).toEqual(PdfPageOrientation.landscape);
        expect(settings.size).toEqual({ width: 500, height: 400 });
        expect(settings.rotation).toEqual(PdfRotationAngle.angle90);
        page = section.addPage();
        expect(document.pageCount).toEqual(2);
        let data = document.save();
        expect(data.length > 0).toBeTruthy();
        document.destroy();
        document = new PdfDocument(data);
        page = document.getPage(0);
        expect(page.orientation).toEqual(PdfPageOrientation.landscape);
        expect(page.size).toEqual({ width: 500, height: 400 });
        expect(page.rotation).toEqual(PdfRotationAngle.angle90);
        expect(document.pageCount).toEqual(2);
        document.destroy();
    });
});
describe('982009 - PdfDocumentInformation Support', () => {
    it('982009 - TC01 - create new doc, set all metadata, verify before and after save/load', () => {
        const creation = new Date('2015-01-18T12:00:00');
        const modification = new Date('2015-01-18T12:00:00');
        const doc: PdfDocument = new PdfDocument();
        const info: PdfDocumentInformation = {
            title: 'Essential PDF Sample',
            author: 'Syncfusion',
            subject: 'Document information DEMO',
            keywords: 'PDF,ej2',
            creator: 'Essential PDF',
            producer: 'Syncfusion PDF',
            language: 'en-us',
            creationDate: creation,
            modificationDate: modification
        };
        doc.setDocumentInformation(info);
        const before: PdfDocumentInformation = doc.getDocumentInformation();
        expect(before.title).toEqual('Essential PDF Sample');
        expect(before.author).toEqual('Syncfusion');
        expect(before.subject).toEqual('Document information DEMO');
        expect(before.keywords).toEqual('PDF,ej2');
        expect(before.creator).toEqual('Essential PDF');
        expect(before.producer).toEqual('Syncfusion PDF');
        expect(before.language).toEqual('en-us');
        expect(before.creationDate instanceof Date).toEqual(true);
        expect(before.modificationDate instanceof Date).toEqual(true);
        expect((before.creationDate as Date).toISOString()).toEqual(creation.toISOString());
        expect((before.modificationDate as Date).toISOString()).toEqual(modification.toISOString());
        const bytes = doc.save();
        doc.destroy();
        const loadedDocument: PdfDocument = new PdfDocument(bytes);
        const after: PdfDocumentInformation = loadedDocument.getDocumentInformation();
        expect(after.title).toEqual('Essential PDF Sample');
        expect(after.author).toEqual('Syncfusion');
        expect(after.subject).toEqual('Document information DEMO');
        expect(after.keywords).toEqual('PDF,ej2');
        expect(after.creator).toEqual('Essential PDF');
        expect(after.producer).toEqual('Syncfusion PDF');
        expect(after.language).toEqual('en-us');
        expect(after.creationDate instanceof Date).toEqual(true);
        expect(after.modificationDate instanceof Date).toEqual(true);
        expect((after.creationDate as Date).toISOString()).toEqual(creation.toISOString());
        expect((after.modificationDate as Date).toISOString()).toEqual(modification.toISOString());
        loadedDocument.destroy();
    });
    it('982009 - TC05 - create and parse metadata with Unicode strings', () => {
        const doc = new PdfDocument();
        doc.setDocumentInformation({
            title: '测试文档',
            author: '作者名称',
            subject: 'Sven Björk',
            keywords: '关键字,PDF',
            creator: '创建者',
            producer: 'Николаева Анна Борисовна'
        });
        const info = doc.getDocumentInformation();
        expect(info.title).toEqual('测试文档');
        expect(info.author).toEqual('作者名称');
        expect(info.subject).toEqual('Sven Björk');
        expect(info.keywords).toEqual('关键字,PDF');
        expect(info.creator).toEqual('创建者');
        expect(info.producer).toEqual('Николаева Анна Борисовна');
        let updatedData = doc.save();
        doc.destroy();
        let loadedDocument = new PdfDocument(updatedData);
        const documentInformation: PdfDocumentInformation = loadedDocument.getDocumentInformation();
        expect(documentInformation.title).toEqual('测试文档');
        expect(documentInformation.author).toEqual('作者名称');
        expect(documentInformation.subject).toEqual('Sven Björk');
        expect(documentInformation.keywords).toEqual('关键字,PDF');
        expect(documentInformation.creator).toEqual('创建者');
        expect(documentInformation.producer).toEqual('Николаева Анна Борисовна');
        loadedDocument.destroy();
    });
    it('982009 - TC07 - set each metadata field individually', () => {
        const creation = new Date('2015-01-18T12:00:00');
        const modification = new Date('2015-01-18T12:00:00');
        let doc: PdfDocument = new PdfDocument();
        doc.setDocumentInformation({ title: 'Title Only' });
        expect(doc.getDocumentInformation().title).toEqual('Title Only');
        doc.setDocumentInformation({ author: 'Author Only' });
        expect(doc.getDocumentInformation().author).toEqual('Author Only');
        doc.setDocumentInformation({ subject: 'Subject Only' });
        expect(doc.getDocumentInformation().subject).toEqual('Subject Only');
        doc.setDocumentInformation({ keywords: 'Keywords Only' });
        expect(doc.getDocumentInformation().keywords).toEqual('Keywords Only');
        doc.setDocumentInformation({ creator: 'Creator Only' });
        expect(doc.getDocumentInformation().creator).toEqual('Creator Only');
        doc.setDocumentInformation({ producer: 'Producer Only' });
        expect(doc.getDocumentInformation().producer).toEqual('Producer Only');
        doc.setDocumentInformation({ language: 'Language Only' });
        expect(doc.getDocumentInformation().language).toEqual('Language Only');
        doc.setDocumentInformation({ creationDate: creation });
        expect(doc.getDocumentInformation().creationDate instanceof Date).toEqual(true);
        doc.setDocumentInformation({ modificationDate: modification });
        expect(doc.getDocumentInformation().modificationDate instanceof Date).toEqual(true);
        let data = doc.save();
        doc.destroy();
        doc = new PdfDocument(data);
        const after: PdfDocumentInformation = doc.getDocumentInformation();
        // Verify after reloading from bytes
        expect(after.title).toEqual('Title Only');
        expect(after.author).toEqual('Author Only');
        expect(after.subject).toEqual('Subject Only');
        expect(after.keywords).toEqual('Keywords Only');
        expect(after.creator).toEqual('Creator Only');
        expect(after.producer).toEqual('Producer Only');
        expect(after.language).toEqual('Language Only');
    });
    it('982009 - TC08 - manipulate metadata multiple times and verify final values', () => {
        let doc = new PdfDocument();
        doc.setDocumentInformation({ title: 'Initial Title' });
        doc.setDocumentInformation({ title: 'Updated Title' });
        expect(doc.getDocumentInformation().title).toEqual('Updated Title');
        let updatedData = doc.save();
        doc.destroy();
        doc = new PdfDocument(updatedData);
        expect(doc.getDocumentInformation().title).toEqual('Updated Title');
        doc.destroy();
    });
    it('982009 - TC09 - validate metadata field types', () => {
        const doc = new PdfDocument();
        const createDate = new Date();
        const modifiedDate = new Date();
        doc.setDocumentInformation({
            title: 'Title',
            author: 'Author',
            subject: 'Subject',
            keywords: 'Keywords',
            creator: 'Creator',
            producer: 'Producer',
            creationDate: createDate,
            modificationDate: modifiedDate
        });
        const info = doc.getDocumentInformation();
        expect(typeof info.title).toEqual('string');
        expect(typeof info.author).toEqual('string');
        expect(typeof info.subject).toEqual('string');
        expect(typeof info.keywords).toEqual('string');
        expect(typeof info.creator).toEqual('string');
        expect(typeof info.producer).toEqual('string');
        expect(info.creationDate instanceof Date).toEqual(true);
        expect(info.modificationDate instanceof Date).toEqual(true);
        doc.destroy();
    });
    it('982009 - TC10 - should handle invalid types gracefully', () => {
        let doc = new PdfDocument();
        // Set invalid title (number instead of string)
        doc.setDocumentInformation({ title: 123 as any });
        expect(doc.getDocumentInformation().title).toBeUndefined();
        // Set invalid creationDate (string instead of Date)
        doc.setDocumentInformation({ creationDate: 'invalid-date' as any });
        expect(doc.getDocumentInformation().creationDate).toBeUndefined();
        doc.setDocumentInformation({ author: ''});
        expect(doc.getDocumentInformation().author).toEqual('');
        let updatedData = doc.save();
        doc.destroy();
        doc = new PdfDocument(updatedData);
        expect(doc.getDocumentInformation().author).toEqual('');
        doc.destroy();
    });
    it('982009 - TC11 - handle null/undefined values in metadata fields gracefully', () => {
        const doc = new PdfDocument();
        doc.setDocumentInformation({
            title: null as any,
            author: undefined as any
        });
        const info = doc.getDocumentInformation();
        expect(info.title).toBeUndefined();
        expect(info.author).toBeUndefined();
        doc.destroy();
    });
    it('982009 - TC13 - ensure metadata persists across multiple save/load cycles', () => {
        const doc = new PdfDocument();
        doc.setDocumentInformation({ title: 'Persistent Title' });
        let bytes = doc.save();
        doc.destroy();
        for (let i = 0; i < 3; i++) {
            const tempDoc = new PdfDocument(bytes);
            expect(tempDoc.getDocumentInformation().title).toEqual('Persistent Title');
            bytes = tempDoc.save();
            tempDoc.destroy();
        }
    });
    it('982009 - TC14 - handle large metadata strings without truncation or error', () => {
        const longTitle = 'A'.repeat(1000);
        const doc = new PdfDocument();
        doc.setDocumentInformation({ title: longTitle });
        const info = doc.getDocumentInformation();
        expect(info.title).toEqual(longTitle);
        const bytes = doc.save();
        const reloaded = new PdfDocument(bytes);
        expect(reloaded.getDocumentInformation().title).toEqual(longTitle);
        doc.destroy();
        reloaded.destroy();
    });
});